### ISSUE TITLE
Camera page camera highlight

### ISSUE THREAD

**Issue by Tinbum1** [VorlonCD/bi-aidetection#10]
Observation. When viewing the cameras page if you click on a camera in the list it is nicely highlighted blue. If you the click on the details /settings /custom tabs when you come back off that page the camera is no longer highlighted in blue.

**Comment by VorlonCD** [comment]
This is expected behavior - whenever the listview is not 'active' it shows a gray background on the selected item rather than blue.  If you cant even see the gray your monitor contrast is wrong.

**Comment by Tinbum1** [comment]
Thanks, Better have a look at my monitor!!
