### ISSUE TITLE
Night time detection

### ISSUE THREAD

**Issue by Yonny24** [VorlonCD/bi-aidetection#101]
Been having nightly issues with object detection with certain objects that pass through my garden at low light.
I have the BI contrast at the max so it detects the animal but when AI processes the image I get a false alert.
Dark animal at nighttime.

I have the infrared vision on the camera in high def also so views well.

Is there anyway of tweaking/improvement the detection of objects at night time?
(apart from illumintaing the garden with led lights) (will try this option tonight where the animal passes - might just produce enough contrast)

Thanks

**Comment by Yonny24** [comment]
I have adjusted the MODE to High which helps quite a bit. 
Think I needed to buy better cameras with the function to adjust contrast and brightness

**Comment by VorlonCD** [comment]
Also try setting up Amazon Rekognition in the latest version - it *may* do better night time detection.
And I'm planning a feature to apply a contrast/brightness setting to images before sending to the AI.  May be a few weeks.

**Comment by Yonny24** [comment]
> Also try setting up Amazon Rekognition in the latest version - it _may_ do better night time detection.
> And I'm planning a feature to apply a contrast/brightness setting to images before sending to the AI. May be a few weeks.

Great I'll look into that. Not sure how the Amazon works yet. 
Would be awesome if the contrast and brightness could be set

**Comment by Yonny24** [comment]
yeahh finally found the advanced settings for the cameras! Had to download the desktop studio for ezviz and then modify the config file to open the advanced settings!! They do not have it enabled by default.

Now I can adjust everything - contrast/brightness/fps etc etc
We'll see tonight in the dark if the higher contrast helps

**Comment by balucanb** [comment]
> yeahh finally found the advanced settings for the cameras! Had to download the desktop studio for ezviz and then modify the config file to open the advanced settings!! They do not have it enabled by default.
> 
> Now I can adjust everything - contrast/brightness/fps etc etc
> We'll see tonight in the dark if the higher contrast helps

Hey Yonny24 I also have Ezviz's cameras

**Comment by Yonny24** [comment]
> 
> 
> > yeahh finally found the advanced settings for the cameras! Had to download the desktop studio for ezviz and then modify the config file to open the advanced settings!! They do not have it enabled by default.
> > Now I can adjust everything - contrast/brightness/fps etc etc
> > We'll see tonight in the dark if the higher contrast helps
> 
> Hey Yonny24 I also have Ezviz cameras and the studio app you're talking about did you just make the adjustments inside the app or did you actually rewrite a configuration file?

You need to go to program files, find the 
C:\Program Files (x86)\Ezviz Studio\config\Appconfig.ini
open in notepad++ 
add
[LocalOperation]
Show=1

Save and reopen the studio app.
Then you'll see under all device settings all the advanced settings!! :)

**Comment by balucanb** [comment]
> > > yeahh finally found the advanced settings for the cameras! Had to download the desktop studio for ezviz and then modify the config file to open the advanced settings!! They do not have it enabled by default.
> > > Now I can adjust everything - contrast/brightness/fps etc etc
> > > We'll see tonight in the dark if the higher contrast helps
> > 
> > 
> > Hey Yonny24 I also have Ezviz cameras and the studio app you're talking about did you just make the adjustments inside the app or did you actually rewrite a configuration file?
> 
> You need to go to program files, find the
> C:\Program Files (x86)\Ezviz Studio\config\Appconfig.ini
> open in notepad++
> add
> [LocalOperation]
> Show=1
> 
> Save and reopen the studio app. (assuming you have downloaded the ezviz windows studio )
> Then you'll see under all device settings all the advanced settings!! :)

Cool Beans Man! Thanks.

**Comment by Yonny24** [comment]
> 
> 
> > > > yeahh finally found the advanced settings for the cameras! Had to download the desktop studio for ezviz and then modify the config file to open the advanced settings!! They do not have it enabled by default.
> > > > Now I can adjust everything - contrast/brightness/fps etc etc
> > > > We'll see tonight in the dark if the higher contrast helps
> > > 
> > > 
> > > Hey Yonny24 I also have Ezviz cameras and the studio app you're talking about did you just make the adjustments inside the app or did you actually rewrite a configuration file?
> > 
> > 
> > You need to go to program files, find the
> > C:\Program Files (x86)\Ezviz Studio\config\Appconfig.ini
> > open in notepad++
> > add
> > [LocalOperation]
> > Show=1
> > Save and reopen the studio app. (assuming you have downloaded the ezviz windows studio )
> > Then you'll see under all device settings all the advanced settings!! :)
> 
> Cool Beans Man! Thanks.

Next challenge is to find a way to use the BI preset profiles/presets to change the ezviz settings!! Asking for the moon on a stick?? I wanted to increase the contrast in the dark. I have a profile that changes at dusk but need it to update the ezviz cameras. hmmmm

**Comment by balucanb** [comment]
> > > > > yeahh finally found the advanced settings for the cameras! Had to download the desktop studio for ezviz and then modify the config file to open the advanced settings!! They do not have it enabled by default.
> > > > > Now I can adjust everything - contrast/brightness/fps etc etc
> > > > > We'll see tonight in the dark if the higher contrast helps
> > > > 
> > > > 
> > > > Hey Yonny24 I also have Ezviz cameras and the studio app you're talking about did you just make the adjustments inside the app or did you actually rewrite a configuration file?
> > > 
> > > 
> > > You need to go to program files, find the
> > > C:\Program Files (x86)\Ezviz Studio\config\Appconfig.ini
> > > open in notepad++
> > > add
> > > [LocalOperation]
> > > Show=1
> > > Save and reopen the studio app. (assuming you have downloaded the ezviz windows studio )
> > > Then you'll see under all device settings all the advanced settings!! :)
> > 
> > 
> > Cool Beans Man! Thanks.
> 
> Next challenge is to find a way to use the BI preset profiles/presets to change the ezviz settings!! Asking for the moon on a stick?? I wanted to increase the contrast in the dark. I have a profile that changes at dusk but need it to update the ezviz cameras. hmmmm
> 
> Think we need onvif cams for this. Ezviz most likely don't have this interaction.

Dude! if you can figure that you will be my hero :) been fighting that since I bought them. Overall I really like the EZVIZ cameras
 but there are things just like what you are talking about that drive me crazy.

**Comment by Yonny24** [comment]
Must be a config file for each camera settings somewhere. Would probably involve more like a bat script on task scheduler to update the config settings at times.
I will dig around the program files as they might be local unless the Chinese have put those in their cloud!!

**Comment by Yonny24** [comment]
Managed to get rid of the time and ezviz stamp on each camera also with the advanced settings. The seconds were triggering my detection unless I added a mask!!! 

![image](https://user-images.githubusercontent.com/64428686/103380638-3d762680-4ac8-11eb-8232-baab1f138f47.png)

**Comment by Yonny24** [comment]
Awesome work @VorlonCD  thanks.

Just set up a custom model for a cat that it would miss at nighttime on one of the cameras which is quite high up, even with the contrast/brightness high. Used about 30 photos in train.

Now the snapshots are analyzed by both servers and the cat was spotted many times last night.

**Comment by Yonny24** [comment]
89% confidence also!
![image](https://user-images.githubusercontent.com/64428686/112150282-aa2c2900-8bbe-11eb-848c-9da0c4cf4058.png)
