### ISSUE TITLE
System.BadImageFormatException

### ISSUE THREAD

**Issue by fretzy99** [VorlonCD/bi-aidetection#103]
Running on Windows 10 pro OS build 19041.685 and switched from v1.67 to this fork v2.0.37.7608 and whenever a new image is posted to the folder, the following error occurs:
 getting next URL: System.BadImageFormatException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
File name: 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
   at AITool.ClsURLItem..ctor(String url, Int32 Order, Int32 Count, URLTypeEnum type)
   at AITool.AITOOL.<WaitForNextURL>d__22.MoveNext() in D:\Documents\Projects\_GIT\VorlonCD\bi-aidetection\src\UI\AITOOL.cs:line 276

**Comment by VorlonCD** [comment]
This is the correct install procedure:

1) Download the ZIP
2) Right-click > Properties > UNBLOCK
3) Backup the old AITOOLS folder somewhere
4) Unzip everything, overwriting all the files in the original folder

Here is the latest, but nothing relating to that error was fixed (I think you just didnt unblock or have all of the latest DLL files updated)

[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5737439/AITOOL-VORLONCD.zip)
