### ISSUE TITLE
Selection/list location is reset on reload of list

### ISSUE THREAD

**Issue by peppelorum** [VorlonCD/bi-aidetection#105]
The history list is reset when there is a new image in the history, would be good if it remembered the scrollbar position and selection of the image.

![Screen Recording 2020-12-14 at 09 30 05](https://user-images.githubusercontent.com/133687/102058399-b5b5ca00-3def-11eb-902f-9665c55a5923.gif)

**Comment by VorlonCD** [comment]
I think the latest is working better in that respect.   And also if may matter if you have History Settings > Follow enabled or not.

[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5737427/AITOOL-VORLONCD.zip)
