### ISSUE TITLE
Telegram Caption not send

### ISSUE THREAD

**Issue by douglasfl** [VorlonCD/bi-aidetection#106]
Hi,
i am using VorlonCD/bi-aidetection and sending alert on Telegram.

On camera setting, i have set a Caption, but i only recive the image, te caption that i have setting is not sent on telegram.

**Comment by VorlonCD** [comment]
I fixed that in the latest version:
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5737418/AITOOL-VORLONCD.zip)
