### ISSUE TITLE
AITool loosing access to folder

### ISSUE THREAD

**Issue by apedance** [VorlonCD/bi-aidetection#107]
Hello there,

great software. Thank you so much for this stuff.

Sadly, I currently have the issue that AITool is loosing access to the "Default Input Path"
It does work when I set it up fresh. After some time I get this error mesasge:

> 2020-12-18 02:23:50.947089|Error|AITOOLS.EXE|CreateFileWatcherAsync|None|None|None|   Path does not exist: S:\BlueIrisAux2|50|2||8
2020-12-18 02:28:50.948090|Error|AITOOLS.EXE|CreateFileWatcherAsync|None|None|None|   Path does not exist: S:\BlueIrisAux2|53|2||6
2020-12-18 02:33:50.961089|Error|AITOOLS.EXE|CreateFileWatcherAsync|None|None|None|   Path does not exist: S:\BlueIrisAux2|56|2||9

This is not correct, since the path does exist. Windows Explorer can access it without issues.
The hdd the pictures are stored on is on a remote machine. I connect it as a mapped network drive.
No matter what path I use, the tool looses access after some time. (using mapped network and network path)
 
> \\\IPAdresse\Blueiris@IP\BlueIrisAux2
> S:\BlueIrisAux2

**Comment by VorlonCD** [comment]
It must be a temporary failure of the network connection.   Firewall, antivirus, wifi, who knows.

The latest version now retries failed connections every 30 mins I think.  Controllable with setting in JSON file but I dont remember off the top of my head.

[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5737414/AITOOL-VORLONCD.zip)
