### ISSUE TITLE
Adding 2 deepstack urls - http 403 error on additional ports

### ISSUE THREAD

**Issue by Yonny24** [VorlonCD/bi-aidetection#108]
Tying to add 2 ports via the AI tool:

Deepstack URL(s): 192.168.1.249:83;192.168.1.249:84

`
19/12/2020 12:14:46 | DetectObjects | Got http status code 'Forbidden' (403) in 11ms: Forbidden | Error | AITOOLS.EXE | 192.168.1.249:84 | Frontyard | 
19/12/2020 12:14:46 | DetectObjects | Empty string returned from HTTP post. | Error | AITOOLS.EXE | 192.168.1.249:84 | Frontyard | 

`

Post works fine in Postman with port 84 (custom model)

**Comment by VorlonCD** [comment]
This was talked about in the 'future of' thread - closing
