### ISSUE TITLE
MQTT payloads truncated after [Summary] and [SummaryNonEscaped]

### ISSUE THREAD

**Issue by brewtangclan** [VorlonCD/bi-aidetection#109]
I am looking to publish a JSON payload including a timestamp, summary, and image filename. I saw a previous issue regarding %date% and %time% so I removed that but the issue persists. Running on the latest 2.0 prerelease build (b186d49).

Payload is configured as follows (from AITool.settings.JSON):
`"action_mqtt_payload": "{\"summary\":\"[SummaryNonEscaped]\",\"alert_image_path\":\"[ImageFilename]\"}",`
The payload actually being published: `{"summary":"Person (62%)`

Obeservations:
- If I click the "Test" button from the MQTT Settings window, the full JSON payload is published. But if I test from the Actions window (or it actually detects things in the configured input_path), then it gets truncated.
- If I reverse the order of ImageFilename and Summary in the payload, it still truncates immediately after [Summary]
- Same issue using [Summary] as with [SummaryNonEscaped]
- ~~Using [summaryNonEscaped] instead of [SummaryNonEscaped] (capitalization) does not truncate~~ That worked for a few minutes, then went back to truncating. Tried [summarynonescaped] and even [summary] and it is truncating consistently.

Happy to provide additional info/troubleshooting as needed. Thanks!

**Comment by VorlonCD** [comment]
What do the logs look like?

That build is pretty old.  How does the latest behave?
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5732748/AITOOL-VORLONCD.zip)

**Comment by brewtangclan** [comment]
I'd have to go hunting. I have it set up for two cameras, each dumping snapshots every 5s. I set up a workaround for now of using [camera] as the alert image filename, and only publishing [SummaryNonEscaped] instead of a full JSON string, and there are no hits in the not-yet-zipped logs for 'error', 'mqtt', etc. I know at one point I was getting some sort of MQTT error that listed the truncated json payload, but the error was nonspecific (just something like `Unrecognized Topic: whatever Payload: whatever` but nothing specific about the actual issue, and the error wasn't getting logged every time it published.

I'll grab the build you linked in the morning, try the json payload again, and post an update with logs if need be.

Thanks for what you do! Awesome tool!

**Comment by brewtangclan** [comment]
Updated to the build you provided (2.0.289.7661) and it still appears to be occurring. Same as before - I get the expected payload if I test from the MQTT Settings window, but not from the Actions window or from normal detection.

In case any of this is relevant to this issue, after updating to the latest build:
- At startup I am getting a log entry from LoadAsync of `Reverting to REGISTRY backup settings...`. Since updating, I have adjusted settings and restarted the app several times, so I don't suspect it's loading settings from the 2.0 prerelease build I was running previously, but I suppose I could be wrong.
- WaitForFileAccess logs a file-not-found error for .\\_Settings\LastCamImages\\[Camera]-Last.jpg for every image it processes. That directory is empty and I don't see anything in the configuration specifying that path.

AITool.Settings.JSON and latest log file are attached (credentials redacted). For this test run I started with a fresh log file, started the app, walked out on the patio just long enough for it to detect me, then walked back inside and closed the app.
[AITool.[2020-12-23].log](https://github.com/VorlonCD/bi-aidetection/files/5736546/AITool.2020-12-23.log)
[AITool.Settings.JSON.txt](https://github.com/VorlonCD/bi-aidetection/files/5736559/AITool.Settings.JSON.txt)

**Comment by VorlonCD** [comment]
* Fixed - mqtt payload was being truncated when the detection summary contains a semi-colon such as "DOG ; BIRD".   To fix, you are now only allowed to use a PIPE | symbol if you need to have MQTT send multiple topics/payloads. 
* Fixed - the harmless file not found error

[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5737302/AITOOL-VORLONCD.zip)

**Comment by brewtangclan** [comment]
Can confirm that this build (2.0.298.7662) fixes both listed issues.

Thanks again for all you do, and especially for the quick responses! Happy holidays!
