### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Bisquit4407** [VorlonCD/bi-aidetection#11]
Would it be possible to put a button to enable sending the photo with the detection overlay to Telegram instead of the plain photo? Then the user may choose which one to notify with. Thanks for the great work. Awesome programming!

**Comment by Tinbum1** [comment]
+1

**Comment by VorlonCD** [comment]
@Bisquit4407, @Tinbum1 - This version lets you merge the detection's into the image before sending/copying.   Let me know how works.
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5235773/AITOOL-VORLONCD.zip)

**Comment by Bisquit4407** [comment]
Working great so far. Awesome work! Does this zip also contain the text size modification parameter or should i compile the latest for that mod?

**Comment by Tinbum1** [comment]
Thanks Chris, works brilliantly.

**Comment by VorlonCD** [comment]
@Bisquit4407 - You may need to compile the latest for that last text size setting I added.   Are you using this feature with Telegram?  If so, how is it working for that?

**Comment by Tinbum1** [comment]
I am in telegram and works well.
