### ISSUE TITLE
Copying alert images to folder fails

### ISSUE THREAD

**Issue by jf19742016** [VorlonCD/bi-aidetection#110]
Version 2.0.150.7623 - works fine for a while then for some reason it starts reporting "Could not copy image c:\aiinput\Front.20201223_091407529.jpg to network path z:\Front.20201223_091407529.jpg: Could not find a part of the path 'z:\'. [DirectoryNotFoundException] Mod: CopyImage(ClsTriggerActionQueueItem AQI, String& dest_path) Line:734:21".  Within Windows you can copy to the image fine, restarting AI tool makes no difference.  The only way it clears is to reboot the Blue Iris machine.  Is there any debugging I can turn on over the log to determine the issue?

**Comment by VorlonCD** [comment]
Dont copy to the root folder, make a subfolder z:\images.
When it starts giving that error are you SURE the Z: drive is still correctly connected?   If it wasnt thats why a reboot would fix, nothing to do with AITOOL.
Always best to use all local paths when possible in any case.

**Comment by jf19742016** [comment]
Yes absolutely still correctly connected.  Will try and make a subfolder to see if it makes any difference.  Thanks

**Comment by VorlonCD** [comment]
This version corrects the 'could not find part of path' error I think, but if there is an underlying connection issue there is not much I can do.  Let me know if keeping files in a subfolder helps.   Also, there IS a limit to the number of files that can be in a ROOT folder on a machine, you would have to google to find out.

[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5737321/AITOOL-VORLONCD.zip)
