### ISSUE TITLE
[Feature request] AI-Servers : Add Support for Sighthound

### ISSUE THREAD

**Issue by sankeerthb** [VorlonCD/bi-aidetection#112]
The support for multiple AI Servers and the total work done on this tool is outstanding. Thank you @VorlonCD 

Sighthound is an online service that can do Vehicle Detection & Recognition and People faces etc.  Similar to AWK Rek, Sighound Cloud accounts can use the free, development service for up to 5,000 API calls per month.

https://docs.sighthound.com/cloud/detection/

Being able to only reprocess certain labels like ( Car, Truck ) from one AI-Server with another Service helps stay within the 5k limit as we reduce the false alerts is a great capability. Even if not, just able to add Sighthound to the list of AI-Servers would be super cool.

Below is an alert from my Camera for a  'Car' detection on telegram. I reprocessed the same image manually on the sighthound online demo and it clearly labels it a 'USPS Delivery Truck'. 

Pic 1 - Alert from Camera - Processed through Deepstack
![AI_Tool_Car_Alert](https://user-images.githubusercontent.com/43680299/103059330-ca722a80-4572-11eb-8d56-88c6d226ea06.png)

Pic 2 - Manually uploaded above alert image on Sighthound https://www.sighthound.com/products/cloud#content
![AI_Tool_Car_Alert_Reprocess](https://user-images.githubusercontent.com/43680299/103059341-d1993880-4572-11eb-80c7-84b612cdde8b.jpg)

**Comment by petermai6655** [comment]
I was thinking of training a custom model in DeepStack to detect if I have a package, but this would also be a cool thing to try. I think Sighthound does license plates as well, so that would be an awesome interesting capability to add to AI Tool.

**Comment by VorlonCD** [comment]
Getting there....  Is my label formatting appropriate for whatever you need to do with it?

`Truck [White, Toyota, Tundra, Plate=Greece 27W131]`

![image](https://user-images.githubusercontent.com/7512113/103489545-5261fb00-4de3-11eb-823b-8168a3a04889.png)

**Comment by balucanb** [comment]
That's impressive.

**Comment by VorlonCD** [comment]
If you want to do some initial testing, here is a build that works for basic sighthound person/face/vehicle detection.   

It does NOT support only calling SightHound if Deepstack already detected certain objects, that will be in a few days hopefully.

Sign up and go to https://accounts.sighthound.com/#/sighthound-cloud to get the API key that will be requested.

[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5762466/AITOOL-VORLONCD.zip)

**Comment by sankeerthb** [comment]
Super Awesome!! Thank you. Thank you.

I did some testing for a day, configured it for three cameras. Had around 500 calls to Signhound Api ( as seen on the sighthound website) Wasn't able to get total alerts in the same time. My observations using Version 2.0.429.7675 Built on 1/5/2021 3:02:10 PM as below :

1) As you said, Sighthound detections didn't trigger with the Refinement server checked. Had to uncheck.

2) Because of above, I didn't understand - when an image is run against Deepstack AI local or Sighthound AI or if both are run every time time as I only saw few alerts in the telegram and history tab in AI Tool for Sighthound. ( In AI Server - 1 is Deepstack and 2 is Sighhound Vehicle )

3) Reprocess from History Tab for a UPS truck alert from the previous day, didn't run it against Sighhound. Ran it only through Deepstack which is 1. AI Server.

3) Looks like Sighthound is run for masked alerts too as I see in the history tab. Guessing this wouldn't be the case after 1 is taken care of.

4) Nice to have - Include AI Server Name or CustomName in telegram Alerts.

5) Nice to have but not a priority  - Include Filter by AI Servers in Stats Tab and History to see specific alerts and counts. 

Got below alert to my telegram at 7.44 pm; I'm guessing it's the same alert that triggered detections from Deepstack and Sighthound. The second image is missing the actual vehicle in the image. Do you think it's something I need to adjust for a vehicle in it? or because the sighthound alert is picking the current image and not the detection image when sending an alert.
![doorbell_alert](https://user-images.githubusercontent.com/43680299/103789549-25456080-500e-11eb-9ca4-acfc5d82e2e1.png)

This is a false alert, as it's below the threshold - just love how accurate it shows all vehicles. I"m going to raise the camera up to just identify all vehicles with more confidence. Loving this, thank you. 
![false_alert](https://user-images.githubusercontent.com/43680299/103789565-2aa2ab00-500e-11eb-8d25-397ab6a56eb3.jpg)

**Comment by sankeerthb** [comment]
Last 10 days - I had about 4,600 hits out 5,000 limit. I have disabled it for now. 
Still didn't understand when the service gets triggered. Hopefully, this will be tweaked.
Thank you @VorlonCD

**Comment by VorlonCD** [comment]
I'll get back to refinement server feature sometime.  That is how SightHound is really intended to be used so it only uses sighthound if a vehicle was detected to begin with, reducing the number of API calls.   On settings, if you have "Queued" checked, each URL takes turns, so sometimes sighthound would be used in sometimes others.   If you uncheck queued, it will always use the FIRST url UNLESS there are multiple images waiting in which case it would use #2, #3, etc as needed.
On history tab, you can sort the columns headers or group based on the AI server.

**Comment by VorlonCD** [comment]
@sankeerthb - I think I got it working correctly now. (along with Amazon Rekognition face detection, and a few others).
In the URL edit screen, click **Use as Refinement server** and Sighthound should only work if a vehicle is detected by Deepstack FIRST.

[AITool-VorlonCD-v2.0.626.zip](https://github.com/VorlonCD/bi-aidetection/files/5895206/AITool-VorlonCD-v2.0.626.zip)

![image](https://user-images.githubusercontent.com/7512113/106306259-c9947e80-622b-11eb-87bf-f058c9fb1688.png)

**Comment by VorlonCD** [comment]
FYI this version has a number of fixes for linked and refinement servers.    For LINKED, I tested with the example deepstack **custom model** "license plates" and it seems to work as expected.  it waits for results from both servers when running in this mode:
[AITool-VorlonCD-v2.0.700.zip](https://github.com/VorlonCD/bi-aidetection/files/5978621/AITool-VorlonCD-v2.0.700.zip)
