### ISSUE TITLE
Irrelevant objects in detection summary and annotated images

### ISSUE THREAD

**Issue by brewtangclan** [VorlonCD/bi-aidetection#113]
Running version 2.0.298.7662.

It appears that when a relevant object is detected, *any* objects detected in the image are listed in [Summary] and [Detections] and get annotated in the alert image, regardless of whether it is selected as relevant -- including objects in statically- and dynamically-masked areas.

This does not appear to cause any false detections, but it does obfuscate things for my use case: when relevant objects are detected, send the annotated alert image as push notification, with a title like "Person (85%) detected on Front Yard Camera". Obviously, this is less than ideal when your detection summary is something like `Cat (43%); Chair (84%); Chair (75%); Tv (59%); Potted plant (50%)`, and each of those objects is boxed in the annotated image. 

Not sure if this behavior is by design, but it would be great if it were possible to distinguish (relevant and unmasked objects, i.e. what triggered the alert) vs (relevant but masked objects) vs (irrelevant/inanimate objects).

**Comment by VorlonCD** [comment]
Maybe enable History tab > Settings > Show only relevant?   That mimics the way the old version worked, but I left it disabled so everyone could see all objects found by the AI at first.

**Comment by brewtangclan** [comment]
Aha! That solves the issue of everything showing in [Summary].

Would love to see an option to have separate variables for the "relevant and unmasked" objects, the "relevant but dynamically masked" objects, and the "not relevant" objects. Especially if they could have their own position values (bounding boxes for each detection,  so for example, I can programmatically distinguish between a car in the street and a car in the driveway). I may take a stab at that myself, as I also want to explore the possibility of identifying specific vehicles and faces to drive home automations.

Thanks again for the quick response!
