### ISSUE TITLE
Feature Request: Ability to change time stamp to 24 hour

### ISSUE THREAD

**Issue by balucanb** [VorlonCD/bi-aidetection#114]
I would assume you could simply change the code in the JSON setting file to do this, but for those that don't code a option button to choose one over the other would be nice.

**Comment by VorlonCD** [comment]
You mean in the History tab date column?   Yeah I should allow better control over that and make it easy to control.    I believe it defaults to your LOCAL date/time settings - have you tried setting WINDOWS itself to display the time in 24 hour format?  Might work.  

For variables that expand in ACTIONS you can use %datetime% and it will use AITool.Settings.JSON > DateFormat

It defaults to "dd.MM.yy, HH:mm:ss" but you can change it to anything referenced here:

https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings

**Comment by balucanb** [comment]
> You mean in the History tab date column? Yeah I should allow better control over that and make it easy to control. I believe it defaults to your LOCAL date/time settings - have you tried setting WINDOWS itself to display the time in 24 hour format? Might work.
> 
> For variables that expand in ACTIONS you can use %datetime% and it will use AITool.Settings.JSON > DateFormat
> 
> It defaults to "dd.MM.yy, HH:mm:ss" but you can change it to anything referenced here:
> 
> https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings

I was talking about the time stamp that shows on the snapshot sent to telegram, I changed the windows system format as you suggested and that actually changed it on the snapshot, checked the History tab, AI log, Docker Log and no change there. So I'm happy! :)
