### ISSUE TITLE
With deepstack new GPU for windows

### ISSUE THREAD

**Issue by chiller86** [VorlonCD/bi-aidetection#116]
Hello,

Deepstack released a beta for windows GPU. My problem is it can analyze a image way faster in 30ms - 60ms only using 1% of a Nvidia GPU. Is there a way to send multiple images to deepstack at once and maybe have a option to limit amount of que per second depending how powerfully your GPU is. My point is I can't even warm up my GPU with deepstack and it seems to do one image at a time instead of multiple images at the same time. Thanks

**Comment by Tinbum1** [comment]
I also noticed that only about 1% of my GPU is used as well.

**Comment by VorlonCD** [comment]
They can only do one image at a time.   BUT maybe you could get the docker GPU version going on a different port and have it send requests to both windows gpu version and docker gpu version?   It would only process 2 at a time if there was more than one image waiting in the queue of course.   I think the docker (or linux?) gpu version was harder to get going - I think there were instructions somewhere on the "Future of Deepquest" issue thread here.

And can you have more than one docker instance spun up at the same time??

**Comment by Tinbum1** [comment]
I didn't have a lot of luck with Docker GPU on a windows machine unfortunately, if i did i would imagine you probably could run more than one at a time. I've asked on the DeepStack forum if it would be possible to run multiple images of the Windows GPU DeepStack.

**Comment by chiller86** [comment]
Thanks love your version of the AI tools works great! I'm using cross zone on BI to filter 99% of false alerts if anyone steps on to my property and of course head lights or major sun light changes was the weakest part of crosszone and now I have AI tools analyzing the 1% of alerts and if a human or car is on my property it triggers the alert sound on my phone. So I only process like 20 images in a hour since I turned the sensitivity a little higher on all the outside cams. So far 5 days 0 false alerts and 100% alerts reported.

**Comment by Tinbum1** [comment]
From @OlafenwaMoses

You can run N number of DeepStack instances as far as you use different ports for each of the instances.

e.g

deepstack --VISION-DETECTION True --PORT 81

deepstack --VISION-DETECTION True --PORT 82

deepstack --VISION-DETECTION True --PORT 83

deepstack --VISION-DETECTION True --PORT 84

deepstack --VISION-DETECTION True --PORT 85

**Comment by Yonny24** [comment]
How are the photos queued in this case? Can you configure each camara to use a different deepstack?

**Comment by VorlonCD** [comment]
@Tinbum1 - Very cool!  Have you tried it?

@Yonny24  - Same as always.   You would have to add a URL for each deepstack instance you have running.   And if needed you can set each URL to only work with images from specific cameras.  (with recent builds only)

Note that AITOOL currently only knows how to start ONE instance from the deepstack tab so you would have to start the rest manually for now.

**Comment by balqosz** [comment]
I'm using this option, three instances of Deepstack on three different ports on same PC. Three instances running in parallel as services using "The non-sucking service manager" nsmm.exe utility. I have also disabled deepstack starting from AI Tool.


> From @OlafenwaMoses
> 
> You can run N number of DeepStack instances as far as you use different ports for each of the instances.
> 
> e.g
> 
> deepstack --VISION-DETECTION True --PORT 81
> 
> deepstack --VISION-DETECTION True --PORT 82
> 
> deepstack --VISION-DETECTION True --PORT 83
> 
> deepstack --VISION-DETECTION True --PORT 84
> 
> deepstack --VISION-DETECTION True --PORT 85

**Comment by Yonny24** [comment]
Awesome so you could in theory have the custom model deepstack running in parallel with the vision detection deepstack? Understood from the other thread you could not queue images to both in parallel. What's the syntax for the deepstack url for specific camaras? Sorry not at my pc today. Thanks

**Comment by OlafenwaMoses** [comment]
@Yonny24 For each instance of DeepStack you run, you can enable all APIs including custom model detection. See details in link below.

https://docs.deepstack.cc/windows/index.html#run-with-all-apis

**Comment by Yonny24** [comment]
Sorry but how is each camara listed in the AI tool bound to specific deepstack ports?

**Comment by Tinbum1** [comment]
![image](https://user-images.githubusercontent.com/66704787/103221883-9a80a980-491b-11eb-95df-6b7431c4c20d.png)

**Comment by balqosz** [comment]
![image](https://user-images.githubusercontent.com/24378221/103225193-30aad480-4908-11eb-8af6-000922c852e2.png)

**Comment by Yonny24** [comment]
Nice. This evening I'll have a look
Thanks

**Comment by Tinbum1** [comment]
Yes but I don't know that the same image can be sent to 2 URL's.  VorlonCD?

**Comment by VorlonCD** [comment]
@Tinbum1 - one image can only be processed by one URL and assigned to one camera right now.   Partly because the history DB has a unique key assigned to the filename, so only one history entry can be created per image.    But if there is still a need after they update deepstack to support custom model + builtin, I might be able to call two URLs at the same time and wait for the combined results with some work.

**Comment by Yonny24** [comment]
> 
> 
> I'm using this option, three instances of Deepstack on three different ports on same PC. Three instances running in parallel as services using "The non-sucking service manager" nsmm.exe utility. I have also disabled deepstack starting from AI Tool.
> 
> > From @OlafenwaMoses
> > You can run N number of DeepStack instances as far as you use different ports for each of the instances.
> > e.g
> > deepstack --VISION-DETECTION True --PORT 81
> > deepstack --VISION-DETECTION True --PORT 82
> > deepstack --VISION-DETECTION True --PORT 83
> > deepstack --VISION-DETECTION True --PORT 84
> > deepstack --VISION-DETECTION True --PORT 85

How did you enable MODE High?

**Comment by balqosz** [comment]
I think MODE High is not available in 0.1 beta version, maybe next one.

**Comment by Yonny24** [comment]
Perfect. Set up 2 extra deepstacks running on nssm and 1 with the windows docker with mode=high for now.
Still tweaking them.

Thanks!

**Comment by Yonny24** [comment]
ok that did not go well with the other deepstacks.

![image](https://user-images.githubusercontent.com/64428686/103245229-3d4a1f80-493e-11eb-874f-56ab35cc6118.png)

**Comment by Yonny24** [comment]
I changed the activation to 192.168.1.249:84 instead of localhost:84 and seems to be adding the images to the queue now

**Comment by Yonny24** [comment]
Can't understand why I keep getting this deepstack partially running:
I have the desktop cpu beta running (reinstalled just in case).
and 3 deepstack ports all activated.

![image](https://user-images.githubusercontent.com/64428686/103248408-3ffe4200-4949-11eb-9d4e-2deb8cb242fe.png)

**Comment by VorlonCD** [comment]
I'll get the deepstack tab straighted out in a day or two.  It is easy for it to be confused about the deepstack processes running.

You CAN set mode in the new windows version but you have to do it from a batch file or powershell script.
In batch file set the MODE environment variable like this `SET MODE=High` just before running deepstack.exe's's's.

**Comment by VorlonCD** [comment]
@Yonny24 - try 0.0.0.0 also.   'localhost' resolves to ipv6 and COULD be a factor.   Although I see deepstack does listen on ::

![image](https://user-images.githubusercontent.com/7512113/103251823-83a47c00-4948-11eb-8158-4efffc31e3bf.png)

Another factor might be if you open/close AITOOL and it leaves the deepstack processes running.    After closing AITOOL (AND any service!), try manually killing deepstack.exe, python.exe and redis-server.exe in task manager, then start it up fresh.

**Comment by VorlonCD** [comment]
Actually I dont think 0.0.0.0 works but 127.0.0.1 does (the ipv4 version of 'localhost')

**Comment by Yonny24** [comment]
Better - almost there. Thanks
Picks up the image but gets stuck on 'processing'.

![image](https://user-images.githubusercontent.com/64428686/103253173-cf622000-495e-11eb-8d80-6cf01542dc54.png)

**Comment by balqosz** [comment]
I think it's also possible using nsmm:

![image](https://user-images.githubusercontent.com/24378221/103253834-8e1f3f80-4961-11eb-92e4-e7cb4bf8e0a0.png)

> 
> You CAN set mode in the new windows version but you have to do it from a batch file or powershell script.
> In batch file set the MODE environment variable like this `SET MODE=High` just before running deepstack.exe's's'

**Comment by balqosz** [comment]
Service starts, but I think it's stuck...

> I think it's also possible using nsmm:
> 
> ![image](https://user-images.githubusercontent.com/24378221/103253834-8e1f3f80-4961-11eb-92e4-e7cb4bf8e0a0.png)
> 
> > You CAN set mode in the new windows version but you have to do it from a batch file or powershell script.
> > In batch file set the MODE environment variable like this `SET MODE=High` just before running deepstack.exe's's'

**Comment by balqosz** [comment]
I don't know what the real problem is. But, just adding FDEWS to instance 4, AI Tool hangs with image queue at 100 (increase and never goes to 0 again).
In the second example, when not using FDEWS, all is ok, AI Tool increase the queue, but afterwars returns to 0. I think there may be a bug on setting cameras names there.. Everytime I add FDEWS, AI Tool hangs. 

![image](https://user-images.githubusercontent.com/24378221/103254312-90829900-4963-11eb-9b82-33dae2347c11.png)

![image](https://user-images.githubusercontent.com/24378221/103254338-ad1ed100-4963-11eb-90f2-100f28057973.png)

![image](https://user-images.githubusercontent.com/24378221/103254376-d5a6cb00-4963-11eb-8972-d1906e131929.png)

![image](https://user-images.githubusercontent.com/24378221/103254417-f2430300-4963-11eb-9b6a-20a171935638.png)
