### ISSUE TITLE
Feature Request: Create "zones" to detect certain things from certain parts of the image

### ISSUE THREAD

**Issue by tripp396** [VorlonCD/bi-aidetection#117]
Hey there, been loving the work you are doing on AITool. I've been wondering if there is any way to implement a "zones" like feature so that an alert is only triggered, for example, if a person walks in one part of the frame, but not another.

An example would be that I want to only capture a person walking up to my house (lower 40% of the frame) but not people walking by (upper 60% or so of the frame).

Not sure if that's even possible, or if anyone else has the use case, but it was a thought I had.

**Comment by sankeerthb** [comment]
This already exists in Blue Iris. You can specify the Zone of the camera or section of camera image where you want to be monitored ..also based on different profiles. Only the specified zone will trigger a motion alert that will a file to be processed.  Zones makes more sense in BI and AI part in AI tool. This is just my thought. 

Any reason, you don't want to use it in BI and rather in AI tool.

**Comment by tripp396** [comment]
You know I hadn't thought of that but it makes sense. I suppose I could set the zone name in the file name with macros and then setup different versions of the same camera in aitool to monitor for those.

If that works then I think that solves my issue. Thanks for the direction @sankeerthb

**Comment by tripp396** [comment]
Unfortunately it seems you can't specify the motion zone in a filepath in blue iris, so there for you can't really do it that way. Wondering if there is another way to accomplish this.

**Comment by tripp396** [comment]
I realized I can probably use masks within AITool to accomplish this
