### ISSUE TITLE
Error when start Deepstack!

### ISSUE THREAD

**Issue by wowueh** [VorlonCD/bi-aidetection#118]
I got error when start Deepstack (DeepStack-Installer-CPU.2020.12.beta) as log below:
![error](https://user-images.githubusercontent.com/19222815/103164785-160e2800-4842-11eb-9f0f-b4224dc12dd5.png)
Please help!

**Comment by VorlonCD** [comment]
Deepstack must not be installed

**Comment by jonadis** [comment]
Same issue here... DeepStack is definitely installed.

**Comment by VorlonCD** [comment]
This version does a little better job at detecting deepstack and starting it.  Let me know how it works:
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5745170/AITOOL-VORLONCD.zip)

**Comment by johncoles** [comment]
I had the same issue as well. Starting Deepstack in PowerShell seemed to work but the file that was linked as a possible fix has also fixed the issue.

**Comment by wowueh** [comment]
Solved! I have re-installed Python and it worked! Thanks for all!
