### ISSUE TITLE
History- image not available

### ISSUE THREAD

**Issue by Tinbum1** [VorlonCD/bi-aidetection#12]
Possibly related to previous issue.

![image](https://user-images.githubusercontent.com/66704787/92574338-de717500-f27e-11ea-9fd5-3d20cf7e8c05.png)

**Comment by VorlonCD** [comment]
How is the latest push?   Made it more aggressive finding an image file to use if it can no longer find the original used to create the mask.    The log tells you if it found the original or another.

**Comment by Tinbum1** [comment]
Looks good, Thanks Chris.
