### ISSUE TITLE
Ability to change the DeepStack URI to cater for custom models

### ISSUE THREAD

**Issue by asknoone** [VorlonCD/bi-aidetection#122]
Currently you only define the hostname and port number for the DeepStack URL(s).

It would be great if you can modify the "/v1/vision/detection" portion of the path.

This would use of the DeepStack custom api "/v1/vision/custom/{model-folder}". For example it would allow use of the more accurate yolov5x model on a Jetson.

**Comment by clarkhaskins** [comment]
This would be a great feature, I am trying to get mine to spot UPS, Fedex, and USPS trucks.

**Comment by Tinbum1** [comment]
Have you tried altering it in the JSON settings file?

"curSrv": "127.0.0.1:85",
        "port": 80,
        "httpClientTimeoutSeconds": 0,
        "defaultURL": "http://127.0.0.1:80/v1/vision/detection"

**Comment by VorlonCD** [comment]
@asknoone - any of the newer builds posted in recent issues *should* let the path change.
[AITool-VorlonCD-v2.0.581.zip](https://github.com/VorlonCD/bi-aidetection/files/5843049/AITool-VorlonCD-v2.0.581.zip)

Be aware it only returns results from one server, so you would have to train your custom model with EVERYTHING you want detected.  I hope to be able to combine results from more than one server in a future version.

**Comment by asknoone** [comment]
> @asknoone - any of the newer builds posted in recent issues _should_ let the path change.
> [AITool-VorlonCD-v2.0.581.zip](https://github.com/VorlonCD/bi-aidetection/files/5843049/AITool-VorlonCD-v2.0.581.zip)
> 
> Be aware it only returns results from one server, so you would have to train your custom model with EVERYTHING you want detected. I hope to be able to combine results from more than one server in a future version.

Great, thank you. I will give it a try!

**Comment by VorlonCD** [comment]
This one should be working for custom models now.     In your MAIN deepstack server, pick LINK, then pick your DEEPSTACK_CUSTOM server.  That way it waits for results from both servers before it processes the results:
[AITool-VorlonCD-v2.0.700.zip](https://github.com/VorlonCD/bi-aidetection/files/5978621/AITool-VorlonCD-v2.0.700.zip)

**Comment by asknoone** [comment]
Looks good to me and thanks very much! Closing.

**Comment by VorlonCD** [comment]
@asknoone - you want the latest version installer.   Its always kept here:  https://github.com/VorlonCD/bi-aidetection/tree/master/src/UI/Installer
