### ISSUE TITLE
Possibility to create a prediction on a false alert?

### ISSUE THREAD

**Issue by Yonny24** [VorlonCD/bi-aidetection#123]
This is almost like asking for custom modelling but on the vision detection.
In this log where an object is missed several times is there a way in the new AI tool to add a flag/index to trigger this next time?

Asking for the moon on a stick I guess and probably be closed.

![image](https://user-images.githubusercontent.com/64428686/103283146-8473f700-49b6-11eb-83c5-c70fa7d6facd.png)

**Comment by Yonny24** [comment]
I guess once we're able to run the custom model version and standard vision detection in parallel this will be solved.
Fingers crossed for the development soon

**Comment by VorlonCD** [comment]
combing results from custom and standard have been doable for a number of versions, but here is the latest:
https://github.com/VorlonCD/bi-aidetection/files/6176514/AITool-VorlonCD-v2.0.988.zip
