### ISSUE TITLE
Deepstack path changed

### ISSUE THREAD

**Issue by opa-rudi** [VorlonCD/bi-aidetection#127]
Hi,

I just reinstalled deepstack for Windows. aitool takes the path [INSTALL_FOLDER]/server/server.exe but this path is not up to date anymore. Now the path seems to be like [INSTALL_FOLDER]/deepstack.exe or [INSTALL_FOLDER]/server/deepstack.exe

**Comment by zepanv** [comment]
Seeing the same here, I copied the deepstack.exe and renamed it server.exe

**Comment by VorlonCD** [comment]
any new version of AITOOL you can find here posted in recent Issue threads here requires the latest beta version of Deepstack for windows, and that expects c:\deepstack\server\deepstack.exe (yes the path is hardcoded on the deepstack side so you dont need to reference [install_folder].)

**Comment by zepanv** [comment]
I downloaded the latest "release" of aitool today along with DeepStack-Installer-CPU.2021.01.beta. I will try the one I see in another issue post (https://github.com/VorlonCD/bi-aidetection/files/5826993/AITool-VorlonCD-v2.0.569.zip)
