### ISSUE TITLE
Dynamic and static masks not working as designed in version="2.0.389.7670"

### ISSUE THREAD

**Issue by balucanb** [VorlonCD/bi-aidetection#130]
Since updating to the Version in the title I have noticed that the masking seems to be broke or just as possible user error. Here is what is going on. I have a PTZ camera that watches my driveway where my car is parked I can not seem to get this version to ignore the cars that are masked. I have used the "Draw Mask" (camera tab) feature to mask out the area but when I go back to check it the mask has been removed. I have also used the "details" button and created static masks here, they remain if I go back and check but the system still is not ignoring them. I have also made masks from the "History" tab using the buttons on that page. Because it is a PTZ camera with active pre-sets do I need to make separate masks for each pre set ( I have discussed this previously with you but as of yet I have not got it to work- maybe I need to keep trying?) If you think that is the problem after making the mask in paint, Photoshop, etc. saving as a BMP which folder do I need to drop it into? I have had similar issues with non-PTZ cameras but much less frequently. TIA.

**Comment by VorlonCD** [comment]
My bad - this should fully respect the Cameras "**Custom Mask File**" name set for each camera...
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5772329/AITOOL-VORLONCD.zip)

When you use the Draw Mask CUSTOM button (or Edit Image Mask) look at the top of the window - it should tell you the filename it is using.

You will also have to **delete/create new static masks** if you have any and you have renamed cameras.   It doesnt rename the camera for the static masks yet.

**Comment by Tinbum1** [comment]
I have found that a couple of my custom masks had changed. Don't quite know how as I didn't alter them or rename anything.

**Comment by balucanb** [comment]
> My bad - this should fully respect the Cameras "**Custom Mask File**" name set for each camera...
> [AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5772329/AITOOL-VORLONCD.zip)
> 
> When you use the Draw Mask CUSTOM button (or Edit Image Mask) look at the top of the window - it should tell you the filename it is using.
> 
> You will also have to **delete/create new static masks** if you have any and you have renamed cameras. It doesn't rename the camera for the static masks yet.

Thanks I will give it a try, just noticed that I did not mention another issue. When (with the current version, not the one you posted above) you click on Custom (Draw Mask) the picture changes it's size. i.e. Click custom, picture is normal size as always, you draw on the picture to make your mask, makes no difference if you use rectangles or the brush, you click save and the picture size reduces by 1/3 or maybe a 1/2 but the areas you just drew do not resulting in the masks being in the wrong position on the picture. I will try the new version (above) today and see how it goes.

**Comment by balucanb** [comment]
See pics. Same issue.
Camera Tab (for Ref)
Dynamic mask tab- deleted everything that was there
Mask tab before drawing anything
Mask tab as soon as I released the mouse after drawing.
No pic but I then saved it and result was the same.

![camera tab](https://user-images.githubusercontent.com/34525580/103784563-b5c87480-4fff-11eb-9441-f7bd9c8cce27.JPG)
![DMD](https://user-images.githubusercontent.com/34525580/103784565-b6610b00-4fff-11eb-985c-5bc3b75ac6e8.JPG)
![cm1](https://user-images.githubusercontent.com/34525580/103784567-b6610b00-4fff-11eb-8b00-5bf707b00fd9.JPG)
![cm2](https://user-images.githubusercontent.com/34525580/103784568-b6f9a180-4fff-11eb-8e73-87d3adb46a33.JPG)

**Comment by VorlonCD** [comment]
In Dynamic Mask, "Original mask image not found" just means BI already deleted that original JPG with a detection during a cleanup process.   And AITOOL is just using the last available image.

You cannot create the mask until at least one image has been processed by the camera.  (after you have made a new camera or renamed)

In Custom Masking, the BMP mask file may not exist until you hit OK.  Thats normal.   You may also have to wait until at least one image has been processed by the camera.   AND **If you have renamed a camera, you have to delete/recreate the custom dynamic/static masks.**

This update fixes a few things relating to adding, using APPLY TO and updating cameras.

[AITool-VorlonCD-v2.0.447.zip](https://github.com/VorlonCD/bi-aidetection/files/5778270/AITool-VorlonCD-v2.0.447.zip)

**Comment by balucanb** [comment]
This seems to have fixed the mask moving and the pic resizing I checked the image from my last post and the masks are exactly where they should be now. Thanks.

**Comment by balucanb** [comment]
MMM.   got this error.  The resolution of the mask 'C:\Users\baluc\Downloads\AI-Tool\_Settings\RSyardsd.bmp' does not equal the resolution of the processed image. Skipping privacy mask feature. Image: 768x432, Mask: 1920x1080
Checked the image mask and got the below. So it shown the original size, did the click ok, close the window, go back in and pic is resized, draw the mask all looks OK. wait 30 min or so camera triggers get the error above and see what the mask did below... It appears as if the mask is now sized as it would have originally been if the whole pic resize thing was not going on.

![mask issue](https://user-images.githubusercontent.com/34525580/103831166-13c97c00-5041-11eb-998d-f04fb4259c20.JPG)

**Comment by VorlonCD** [comment]
right just hit CLEAR and re-create the mask.  Or manually delete the BMP file and go back into custom mask to re-create it.

**Comment by balucanb** [comment]
@VorlonCD Running the version from above and have noticed a couple things. Deepstack will stop (error out) after some time and now  I am getting this error non stop in the log- 
  Object reference not set to an instance of an object. [NullReferenceException] Mod: AddImageToQueue(String Filename) Line:946:29

Tried to just re install but the problem persists

**Comment by VorlonCD** [comment]
Let me know how this new version works. Mask BMP files now are automatically renamed as filenameWidthxHeight.bmp and the Draw Custom mask lets you scan your image folder for all known resolutions for the snapshots, then create a mask for each resolution you might encounter.

Note that no changes where made with DYNAMIC MASKING, only the regular custom mask.

[AITool-VorlonCD-v2.0.569.zip](https://github.com/VorlonCD/bi-aidetection/files/5826993/AITool-VorlonCD-v2.0.569.zip)

**Comment by Yonny24** [comment]
Thanks for the new version. Mine stopped working 2 days ago (version only about 3/4 weeks old), even after several reboots, installed this version and all processing again.

Thanks a lot!

**Comment by balucanb** [comment]
@VorlonCD My masking issues are now GTG after the changes you suggested and the changes you made to the program.

**Comment by VorlonCD** [comment]
@balucanb ok thanks for letting me know.   Occasional timeouts should be ok unless you dont want to see errors at all.   It is true that deepstack just isn't completely stable with more than one instance running.

**Comment by xjustbmw** [comment]
i have the same issue with masking even with 2.0.569 version
once i click an image it resizes to lower image and dont know where to draw anymore

**Comment by xjustbmw** [comment]
in registry editor i found Frm_CustomMasking_Size to be : {Width=925, Height=517}
changing this to the right values does not fix the error

**Comment by balucanb** [comment]
@xjustbmw make sure and read all the info in this ticket if you have not done so, I would suggest you 1st make sure you are using the latest AI-Tool and newest version of Deepstack, if you are then you may want to uninstall it all and then reinstall, I know that is a bit of pain but if you are working from a clean install and still get the errors then that may make easier for the Devs to figure out what is going on. hope this helps.

**Comment by xjustbmw** [comment]
I even installed this on another computer and it behaves different. there the image gets bigger when i click on it
running version 2.0.570
where do i download the latest version ? the releases has an older version from 30 october 2020

**Comment by xjustbmw** [comment]
i figured it out
the only coincidence was that i am running 4k displays on both computers where i tested this
in the end i checked the box on disabling high dpi settings for this program in compatbility tab

**Comment by VorlonCD** [comment]
You shouldn't have to do that anyway.   My monitor is 4k.   Perhaps you are using an old or tweaked version of aitool.exe.config file?   Make sure using one from the zip and leave compatibility tab default settings.

**Comment by xjustbmw** [comment]
no. brand new install on both computers with windows 10 pro 20H2 19042.746
i even compiled the latest verison in visual studio
glad it works this way though

**Comment by xjustbmw** [comment]
little update, 
on the secondary computer I had manual scalling set in windows to 125
disabling the high dpi settings didnt do anything on that one
