### ISSUE TITLE
Request - AI Tool Status

### ISSUE THREAD

**Issue by DM-AU** [VorlonCD/bi-aidetection#131]
Hi,

Firstly thanks for improving this tool, it has been invaluable! 

My request is can you add the option for AI Tool to send MQTT system status messages? This way i can monitor that and create automations in Home Assistant. If AI Tool fails to start or crashes for whatever reason I would know about it due to lack of messages (and dont need to keep manually checking its running). 

Much appreciated!
Thanks

**Comment by MissMusic** [comment]
Do you experience lots of crashes? I don't since last update. I just run a simple PS-script on an interval that checks for the process and starts it if it's not running.

**Comment by DM-AU** [comment]
Nah its been pretty flawless, but I am preparing for the time when it may not be. I would rather be notified if possible so I can be aware of the issue.

**Comment by VorlonCD** [comment]
Right now telegram is the only way to receive errors that happen WITHIN the program, but you would have to use another external tool to send messages if AITOOL crashes.  

@MissMusic - what would this loop look like with a powershell script?

start AITOOL.EXE and wait until it exits for any reason
Send MQTT error message with [MQTT-CLI](https://github.com/hivemq/mqtt-cli)
Loop

**Comment by MissMusic** [comment]
I'm not sending any notifications, just checking if AI-tool is running, if not, check that the input folder exists (i'm using a ramdisk to save SSD wear, so no persistant storage on reboot, and AI-tool fails to monitor the folder if it's not there when it starts).

Just wrote it quickly, no variables or nothing so you have to edit the paths according to your setup.

I'm sure you can get PowerShell to send an MQTT message too if the process isn't running/getting restarted by the script, i have not looked in to it.

I created a task in task scheduler to run the script on startup and then on a 5min interval indefinitely. 
```

# Check if AI-tool process is running:
if((Get-Process -Name AITool -ErrorAction SilentlyContinue) -eq $null){
# If not:
# Check if input folder exists
    if(Test-Path X:\aiinput3){
    Write-Host "AI-input folder exists"
    }
# If the folder does not exist, create it before starting AI-tool or it will fail to monitor for new images.
    else {
    Write-Host "Creating AI-input folder"
    New-Item -Path "X:\" -Name "aiinput3" -ItemType "directory"    
    }
# After creating folder, start AI-tool
    Write-Host "Starting AITool now"
    ."C:\AI-Tool\AITool.exe"
}
# If AI-Tool process is already running, print messege and do nothing else
else {
    Write-Host "AITool is running"
    }
exit

```

**Comment by digiblur** [comment]
> Right now telegram is the only way to receive errors that happen WITHIN the program, but you would have to use another external tool to send messages if AITOOL crashes.
> 
> @MissMusic - what would this loop look like with a powershell script?
> 
> start AITOOL.EXE and wait until it exits for any reason
> Send MQTT error message with [MQTT-CLI](https://github.com/hivemq/mqtt-cli)
> Loop

Since AI logs into the MQTT server, it could just push a retained LWT Online payload to a topic with the Payload of Offline when it fails, then if AITool falls off somehow the MQTT server will automatically post Offline.  Any project should use the LWT.

**Comment by VorlonCD** [comment]
@digiblur @DM-AU - This version will use the "Last Will" feature of MQTT.   When it first connects it will send a LWT "**AITool/status**" topic with payload of "**Offline**".   So you should see that message if AITOOL ever crashes and you are using MQTT.    When it connects it now sends "Online" to the same topic.   If you want to change this, close the program, edit AITOOL.SETTINGS.JSON and change "**mqtt_LastWillTopic**" and "**Mqtt_LastWillPayload**" settings.

[AITool-VorlonCD-v2.0.569.zip](https://github.com/VorlonCD/bi-aidetection/files/5826993/AITool-VorlonCD-v2.0.569.zip)

Let me know how it works.

**Comment by digiblur** [comment]
> @digiblur @DM-AU - This version will use the "Last Will" feature of MQTT. When it first connects it will send a LWT "**AITool/status**" topic with payload of "**Offline**". So you should see that message if AITOOL ever crashes and you are using MQTT. When it connects it now sends "Online" to the same topic. If you want to change this, close the program, edit AITOOL.SETTINGS.JSON and change "**mqtt_LastWillTopic**" and "**Mqtt_LastWillPayload**" settings.
> 
> [AITool-VorlonCD-v2.0.569.zip](https://github.com/VorlonCD/bi-aidetection/files/5826993/AITool-VorlonCD-v2.0.569.zip)
> 
> Let me know how it works.

Nice job!!

**Comment by DM-AU** [comment]
Thanks - absolutely perfect!

**Comment by Nierka4** [comment]
Tested - works like a charm. Thanks @VorlonCD
