### ISSUE TITLE
Unclear instructions for preparing custom model dataset

### ISSUE THREAD

**Issue by Yonny24** [VorlonCD/bi-aidetection#133]
Sorry guys but these end-to-end instructions are really not clear..

https://docs.deepstack.cc/custom-models/datasetprep/index.html#step-2-organize-your-dataset

Its says:

https://docs.deepstack.cc/custom-models/datasetprep/index.html#step-4-annotate-your-dataset

Annotate Your Test Dataset
**Repeat the process above for your test folder as well.**

But then also:

https://docs.deepstack.cc/custom-models/datasetprep/index.html#step-2-organize-your-dataset
Your Directory Structure should look like this

 My-Dataset:

 - - - - - train (90% of your images goes here)

 - - - - - test (put about 10% of your images here)

If the process for the test folder is repeated for annotation then how can the test folder only contain 10% of your images?

I've been repeating the process for test and train so they are identical.

Please can these instructions be cleared up?

Do I only put a few photos in the test folder and most in the train?
Is this where I've been going wrong?

Thanks

**Comment by VorlonCD** [comment]
This should be logged over in deepstack issues:
https://github.com/johnolafenwa/DeepStack/issues
