### ISSUE TITLE
BI Camera Name bug v2.0.414.7674

### ISSUE THREAD

**Issue by xdreamwalker** [VorlonCD/bi-aidetection#134]
The BI Camera Name for one camera will save to other cameras when using the 'Apply To' button to save settings to those other cameras.

Example; I will make an adjustment to the 'Actions' settings and want to apply those to other cameras. The image below is what happened to the BackyardNorth camera when I used the 'Apply To' button from the Backyard camera to apply 'Actions' settings to the BackyardNorth camera.

![image](https://user-images.githubusercontent.com/24192512/103771026-fe2e6500-4ff4-11eb-9dff-0800f30d968e.png)

**Comment by 42ism** [comment]
Yes, can confirm, if you use the "Apply to" say to copy Actions only, it makes all destination "BI Camera Name" same as the source one used. Build 2.0.414.7674

**Comment by VorlonCD** [comment]
This should fix that issue:
[AITool-VorlonCD-v2.0.441.zip](https://github.com/VorlonCD/bi-aidetection/files/5778130/AITool-VorlonCD-v2.0.441.zip)

**Comment by xdreamwalker** [comment]
Yep, this version does not have this bug. 👍
