### ISSUE TITLE
Feature request: add another similar 'queue time'

### ISSUE THREAD

**Issue by JayL-F1** [VorlonCD/bi-aidetection#135]
First off: awesome job

Now,question: would it be possible to add, in addition to the avg time in queue info on main page, the time from when the jpg was taken/timestamped to the time the camera url was called?

Thank you for considering.

**Comment by VorlonCD** [comment]
For this version you will see a "Image life time" stat in the LOG after each image is processed.   It uses the image CREATE DATE to calculate.  Almost never any different from the queue wait time though.
[AITool-VorlonCD-v2.0.534.zip](https://github.com/VorlonCD/bi-aidetection/files/5811534/AITool-VorlonCD-v2.0.534.zip)
