### ISSUE TITLE
[Feature Request] Timer function

### ISSUE THREAD

**Issue by balucanb** [VorlonCD/bi-aidetection#137]
(This is really in the nice to have category) If there is another way to do this please let me know as if you get any busier working on this project we are all going to need to pool our $$$ and start paying you! Here is what I am asking for, I have 1 indoor camera that only is active during the evening, it is tied to schedule/profile in BI, works great but as it is in my office it is constantly pushing alerts to telegram B/C I am sitting at my desk, it would be nice if I could set some kind of timer/schedule in AI-Tool where it would only send alerts after X-time. I do understand I can pause the camera in BI and accomplish this but there is no way to automate this as far as I can tell. Thanks so much for being smarter than the rest us.. OK me and all the work on this project!!

**Comment by Nierka4** [comment]
If you using MQTT you can do it right now. Send alerts to MQTT and with it, you can control when and where to "forward" alerts. You can use your phone GPS to let MQTT enable/disable those alerts when you are in the office or use the time of the day...

**Comment by VorlonCD** [comment]
The latest version i posted over in pushover issue thread ads the ability to schedule

**Comment by balucanb** [comment]
Thanks so much!
