### ISSUE TITLE
DeepStack URLs tagged "In Use" and never cleared

### ISSUE THREAD

**Issue by edalquist** [VorlonCD/bi-aidetection#138]
Not sure how to further debug this but I have DeepStack running on two computers, one instance on the same Windows install that AITool and BI are on and another on a remote computer.

Periodically the remote URL gets flagged as InUse in the server URLs and never gets reset. I end up having to remove the URL and re-add it to fix the problem.

Version 2.0.312.7665 built on 12/26/2020

**Comment by Tinbum1** [comment]
I had that a couple of times in the past around the date you mentioned as your build date. I'm running a later version and haven't seen it again. Perhaps worth running a later version.

**Comment by VorlonCD** [comment]
In newer versions I don't save the "in use" property which i think fixed.  Just posted a new one in the pushover issue thread.
