### ISSUE TITLE
another instance is already running

### ISSUE THREAD

**Issue by cooper7012** [VorlonCD/bi-aidetection#139]
Accessing the UI is not user friendly.

If I click minimize the app disappears from the screen. There's no clear way to maximize the app. It's still running in task manager but it appears to be closed because there's no way to open the UI again.

If I click on the AITool.exe I get an error, "Another instance is already running". If I stop and close the app by clicking the X in the top right corner and kill the first instance of AITool in task manager. I get the following error message when I open the app again "Program did not shutdown gracefully".

It would be nice if you could just minimize and maximize the app like normal.

**Comment by JuraasicCoasterNerd** [comment]
When you minimize it, it goes to the system tray so its out of the way. To pull its back up, click the icon on the tray. You may need to click the little up arrow first. 

![image](https://user-images.githubusercontent.com/16529122/104387506-42de6280-5505-11eb-8a91-4a4988212d15.png)

**Comment by cooper7012** [comment]
Thank you for the feedback!!!

**Comment by VorlonCD** [comment]
This version has a checkbox you can disable if you dont want the program to minimize to the task tray.

[AITool-VorlonCD-v2.0.569.zip](https://github.com/VorlonCD/bi-aidetection/files/5826993/AITool-VorlonCD-v2.0.569.zip)
