### ISSUE TITLE
Warning in logs with disabled camera 

### ISSUE THREAD

**Issue by DM-AU** [VorlonCD/bi-aidetection#146]
Hi,

I have disabled a camera for testing and am getting spammed with errors in the logs:

![image](https://user-images.githubusercontent.com/66342521/104991487-f9e15d80-5a72-11eb-8cce-a6c087803df7.png)

Any chance this can be changed from an error to a warning or just informational? 

Thanks

**Comment by balqosz** [comment]
Hi,

 I would disable the snapshots from blueiris, instead of disabling the camera in AI Tool.

**Comment by DM-AU** [comment]
Hi,

Thanks for the suggestion but I am still using the snapshots in Blue Iris. I could remove the camera from AITool but I would lose my current config for when I re-enable it, but also this defeats the purpose of having a disable camera option in AITools. I guess I am more pointing out the logic flaw in being able to disable something only to have it flag it as an error instead of an expected result.

**Comment by balqosz** [comment]
Maybe you can rename it?

![image](https://user-images.githubusercontent.com/24378221/105122066-48fbb280-5ab4-11eb-8fa2-a69ec131ac1c.png)

**Comment by DM-AU** [comment]
Thanks, that is a good workaround.

**Comment by DM-AU** [comment]
Not good workaround unfortunately:
![image](https://user-images.githubusercontent.com/66342521/105131797-c586a380-5b3d-11eb-8a04-dba7753c95a3.png)

**Comment by VorlonCD** [comment]
This one removes the skipping error and should do a better job at detecting what camera the image belongs to:
[AITool-VorlonCD-v2.0.581.zip](https://github.com/VorlonCD/bi-aidetection/files/5843049/AITool-VorlonCD-v2.0.581.zip)

The preview jpg wont always be accurate.

You could also create a camera called DEFAULT with no "Input file begins with" value so in stranger configurations it always gets assigned to at least one camera.

**Comment by DM-AU** [comment]
Thanks - seems to have calmed down now :)
