### ISSUE TITLE
"DEEPSTACK URL(s)"

### ISSUE THREAD

**Issue by chiller86** [VorlonCD/bi-aidetection#147]
I'm trying to run multiple GPU window versions since deepstack only process one image at a time. Since the new release of the windows GPU hardly uses the GPU power I want to run like 5 or 10 instances of deepstack. I tried adding in the settings windows under "DEEPSTACK URL(s)" as a example 192.168.1.100:1001,192.168.1.100:1002,192.168.1.100:1003,192.168.1.100:1004,192.168.1.100:1005 Then I paste like a 100 images in the folder and  just having two url's it knocks the over all time down but any more url's it doesn't improve am I doing this correctly?

**Comment by chiller86** [comment]
I tried it again with two URL's with deepstack two instance open with 50 ish images. 45 of them went to the first URL of deep stack and 5 went to the second URL and the process time is the same on both deepstacks running.

**Comment by Tinbum1** [comment]
It seems not that easy to run multiple instances as the memory requirement is so high. 

I've just had problems running multiple instances and found it was because I added some cameras to be processed by the GPU.

**Comment by chiller86** [comment]
> It seems not that easy to run multiple instances as the memory requirement is so high.
> 
> I've just had problems running multiple instances and found it was because I added some cameras to be processed by the GPU.

I'm using a 11 year old I7 with 32 GB ram and a 2070 8GB with 15 camera's I'm barely using 20% of ram and on the GPU 8GB vram like 8% when it's processing images. Trying to find the bottleneck or if it's software issue. 

I use cross zone on BI takes away 97% of the false alerts and AI tool to process the 3% of alerts. Then have duplicate cameras just to record any motion with no alerts so I don't miss anything.

**Comment by Tinbum1** [comment]
I run an Intel Core i7-8700K CPU @ 3.70GHz with 32Gb ram and a GTX 1050 4Gb Card and have troubles. I tried with 14x 2mp cameras on the GPU card and all the values looked ok but it wouldn't even run 1 instance of the windows GPU DeepStack stably.

**Comment by chiller86** [comment]
> I run an Intel Core i7-8700K CPU @ 3.70GHz with 32Gb ram and a GTX 1050 4Gb Card and have troubles. I tried with 14x 2mp cameras on the GPU card and all the values looked ok but it wouldn't even run 1 instance of the windows GPU DeepStack stably.

I tried it on a test computer with a GTX 1060 3gb ran 1 instance just fine 40 to 80 ms for a downscaled saved image at 1280x720 for AI Tool. One instance open jumps up about 15% Vram usage once deepstack is open and can probably could run at least 5 deepstacks on that card as the Vram on the GPU doesn't increase when it's processing only open. I use the Intel quicksync for all the camera's decoding and save GPU for deepstack. I feel there is room on the table for deepstack to improve multi image proccessing for GPU. I did see deepstack announce a new version soon that's supposed to be even faster and lighter.

**Comment by VorlonCD** [comment]
@chiller86 - if you havent tried a recent version of deepstack it seems to be a little more stable.  One was released last week I think.    And here is the latest version of AITOOL that may make it smoother to deal with multiple deepstack instances, but it cant really fix issues where they are simply unstable.
[AITool-VorlonCD-v2.0.700.zip](https://github.com/VorlonCD/bi-aidetection/files/5978621/AITool-VorlonCD-v2.0.700.zip)
