### ISSUE TITLE
Timeline (low priority)

### ISSUE THREAD

**Issue by balqosz** [VorlonCD/bi-aidetection#148]
Hi! 

 This issue may be low priority. Is it normal timeline always showing as this? 

![image](https://user-images.githubusercontent.com/24378221/105251791-e90c1700-5b5a-11eb-814a-78beb01e83a7.png)

**Comment by VorlonCD** [comment]
Did you only have activity today starting around 1900 hours for the first time?
Did you start a fresh copy that didnt have a history database pre-populated around 1900 hours?

If yes, its normal, if no its not normal.

**Comment by balqosz** [comment]
I always see the same graphic, matching the current time. For example, I see this now:

![image](https://user-images.githubusercontent.com/24378221/105257960-8ff6b000-5b67-11eb-9d60-a84dcacda1d1.png)

**Comment by VorlonCD** [comment]
See what happens if you change your windows time to display 12 hour format rather than 24 hour.

**Comment by balqosz** [comment]
I will try and comment later. Thx.

**Comment by balqosz** [comment]
Changes applied. Also reset stats. I see the mountain moving, with its peak at the current time.

![image](https://user-images.githubusercontent.com/24378221/105349907-1db6b780-5bc9-11eb-86cf-cf76387870a1.png)

**Comment by balqosz** [comment]
Hi Vorlon:

This is what I did. **Sure it will bring a problem**, but what I mean is that it's possibly the problem is in the code, and not in regional settings.


SQLiteHistory.cs (near line 776)

                 Stopwatch dsw = Stopwatch.StartNew();
                                    **//rowsdeleted = this.sqlite_conn.Delete(hist);
                                    this.DeleteTimeCalc.AddToCalc(dsw.ElapsedMilliseconds);
                                   // if (rowsdeleted != 1)
                                   // {
                                   //     failedcnt++;
                                   //     Log($"Error: When trying to delete database entry, RowsDeleted count was {rowsdeleted} but we expected 1.");
                                   // }**
                                }


And here, near line 84:

private void HistoryJobQueueLoop()
        {
            //this runs forever and blocks if nothing is in the queue

            foreach (DBQueueHistoryItem hitm in this.DBQueueHistory.GetConsumingEnumerable())
            {
                if (MasterCTS.IsCancellationRequested)
                    break;

                string file = "";
                try
                {
                    if (hitm == null || hitm.hist == null || string.IsNullOrEmpty(hitm.hist.Filename))
                    {
                        Log("Error: hist should not be null?");
                    }
                    else
                    {
                        file = hitm.hist.Filename;
                        if (hitm.add)
                            this.InsertHistoryItem(hitm.hist);
                       **// else
                        //    this.DeleteHistoryItem(hitm.hist);  //Getting nullreferenceexception here and cant figure out why**
                    }
                }
                catch (Exception ex)
                {
                    Log($"Error: ({file})" + ex.ToString());
                }
            }
            Log($"Debug: HistoryJobQueueLoop canceled.");
        }


Here is the result of those changes, after 6 hours runtime:

![image](https://user-images.githubusercontent.com/24378221/105635471-b2c3e580-5e41-11eb-8e6b-2943fa65be6e.png)



Also, I think here **public void UpdateTimeline()**, the originally "minute > 30" should be to "minute >= 30". If I'm not wrong, minutes go from 0 to 59, so 0 to 29 would be first part, and 30 to 59 the second part.

     //get minute
                    int minute = hist.Date.Minute;

                    int halfhour; //stores the half hour in which the alert occurred

                    //add +1 to counter for corresponding half-hour
                    **if (minute >= 30) //if alert occurred after half o clock**
                    {
                        halfhour = hour * 2 + 1;

Thank you

**Comment by balqosz** [comment]
What I was observing previous to those changes, is that history (database) always has few data, I mean recent data, the last minutes. AI Tool is erasing recent data from history, so the graph cannot show a real timeline of 24 hours. I hope you can understand what I'm trying to explain..

Best regards.

**Comment by VorlonCD** [comment]
Compile with debug not release.   Causes sql db 32 vs 64bit compatibility issue so nothing can be saved

**Comment by balqosz** [comment]
Yes, it is compiled with debug, always using that option. The images from previous posts are using the zip you distributed here...

**Comment by balqosz** [comment]
Hi Vorlon. 

Sorry to create confusion to you. I think I've found the culprit (of course excluding myself 😉). This BI setting was causing the problems I've been reporting here:

![image](https://user-images.githubusercontent.com/24378221/105862376-7a9ddd80-5fce-11eb-9d59-79fec94210f1.png)

Limit size must not be zero. Initially I thought that AI Tool was the one deleting files in aainput folder, making some kind of maintenance. But I was wrong, it was BI when using "limit size"=0 for Clips & Archiving. Also I was assuming that leaving 0 in that field, would be equivalent to infinite size and BI would only use clip age, but I was wrong in my interpretation.

Finally, it's working! 

**The only minor thing I would change in the code is in section "public void UpdateTimeline()"**

if (**minute > 30**) //if alert occurred after half o clock

**I think "minute >= 30" should be used instead of "minute > 30"** (0 to 29, 30 to 59) but perhaps I'm wrong here too.

Best regards.

(Your AI Tool is a **perfect tool** for BI!)

**Comment by VorlonCD** [comment]
Oh wow, I had a message queued that was going to suggest making sure BI wasnt deleting all the files too soon.   As soon as BI deletes a file, it is removed from the AITOOL database so it makes complete sense.  You solved your own problem!

The comment for the code is 'if alert occurred after half o clock' and the logic is right for that.   If you or @gentlepumpkin know a reason why it messes with the stats I'm happy to change.

**Comment by balqosz** [comment]
Thank you Vorlon. 

About the code: minutes go from 0 to 59, so the first part of that half is from 0 to 29. I think that using > 30 is not the real half, in such case from 0 to 30 you get 31 minutes, and from 31 to 59 you get 29.


I close this thread as solved!
