### ISSUE TITLE
Log scroll button

### ISSUE THREAD

**Issue by Tinbum1** [VorlonCD/bi-aidetection#15]
If you have the Scroll log button un-ticked and right click on the log it scrolls.

**Comment by VorlonCD** [comment]
For now, just dont click inside the blue log window or use mousewheel to scroll.   If you use the scrollbar on the side to move up and down in the log window it will not re-trigger autoscroll.   As soon as you click in side it gets messed up.   Still have no idea why this is happening, but probably multithreading issue of some sort.

**Comment by Tinbum1** [comment]
Sorted with new logging. Thank you.
