### ISSUE TITLE
Custom object detection question

### ISSUE THREAD

**Issue by LostSoulfly** [VorlonCD/bi-aidetection#150]
So, I'm planning on training a model to recognize Fedex, USPS, and UPS logos so I can get targeted notifications on packages and mail (that's not what this issue is about as I know that's outside of scope for this repo).

My plan is to do [something similar to this.](https://towardsdatascience.com/building-a-real-time-fedex-ups-usps-detection-system-with-yolo-1cc72382088a) I'll be using the Win10 version most likely on the same host as BI.

Anyway, my question is: How can I specify a custom "Relevant object" in the UI? If I understand correctly, I will need to [label a bunch of images and then train them](https://www.youtube.com/watch?v=wQKUQ6Y2n3Q), adding the resultant model to DQAI. After that, how do I get those results into bi-aidetection if there is no option to specify a custom object?

From the ipct thread, these are the only objects that appear to be valid. This is where my question is.
![image](https://user-images.githubusercontent.com/9120519/105267475-77829780-5b5f-11eb-875f-c971b19ce59d.png)

And of course, if I'm able to achieve good results I will happily share this with everyone.

**Comment by balucanb** [comment]
Just FYI before you get to far into this. Currently there is no way to run a custom detection AND the "normal" model. it is all or nothing. If you only care about the logo's ( I would think not) then you are golden otherwise you would need to train your custom model to ID everything you want detection on. Really does not answer the question you posed but thought it might be good to know.

**Comment by Yonny24** [comment]
Yep I'm wiating for the time when we can run both at the same time. Put the custom model on the backburner for now.

**Comment by VorlonCD** [comment]
@LostSoulfly @balucanb @Yonny24  - this version should work fine for custom models.    Add the custom model URL as a secondary URL, then when you edit your "regular" deepstack URL, pick the LINK option and link it with the custom model URL.    This will wait for combined results of both servers before validating everything.
https://github.com/VorlonCD/bi-aidetection/files/5978621/AITool-VorlonCD-v2.0.700.zip

![image](https://user-images.githubusercontent.com/7512113/107892462-3463dc00-6ef3-11eb-8138-b540447ab122.png)

And you have been able to specify custom objects for a number of builds:

![image](https://user-images.githubusercontent.com/7512113/107892487-637a4d80-6ef3-11eb-8813-ba411754206a.png)

And if using the latest WINDOWS version of Deepstack, AITOOL will automatically generate and add the URL for you along with starting the deepstack instance:

![image](https://user-images.githubusercontent.com/7512113/107892512-9f151780-6ef3-11eb-9dd7-16e881440e34.png)


Let me know how it works!

**Comment by antb33** [comment]
@VorlonCD this works fantastically! Thank you for efforts on AITool. I can't speak for OP but I personally now have a custom model detecting my cat with a 100% hit rate compared to 60% on the default DeepStack model. This is now running alongside the default Person detection.

**Comment by Yonny24** [comment]
I need to find the time to set up a custom model also for a specific cat although my default model picks it up most of the time.
@antb33  how many custom photos did you use to create your custom cat model?
The AI tool is looking great now and improved so much in such a short time.
Thanks @VorlonCD

**Comment by antb33** [comment]
@Yonny24 probably not enough tbh, about 30 with 3 for validation (10%). Its indoor looking at the kitchen counter so there are only ever going to be 2 similar looking cats and a few people. So I think it will be ok. Will see how it copes over the next few weeks.

**Comment by Yonny24** [comment]
@antb33
I still haven't grasped the steps to take with the 2 folders, test and validation (don't quite recall the folder names) 
What photos to put in which folder and which ones do I need to validate.

**Comment by antb33** [comment]
@Yonny24 this isn't a good place for this discussion as its unrelated to this software issue page. I suggest reading the deepstack custom models pages https://deepstack.cc/custom-models and if you're still stuck post up on their forum. 

Off the top of my head they recommend you put 90% of your images in 'test' folder and the remaining 10% in 'validation' folder. Don't put any of the same image in both folders. The training script will do the validation automatically at the end.

**Comment by antb33** [comment]
@Yonny24 glad I could help! The forums are a better place for these discussions also because its much more visible to other people searching for similar help. Good luck with it

**Comment by Yonny24** [comment]
@antb33 

Been there and tried but appeared to be unlucky as nobody gave an answer. Gave up and left the custom model idea. Not sure which one it was now as it was quite some time ago.
Might well try the custom model again when time permits. Have to save some of those cat snapshots.

Thanks
