### ISSUE TITLE
BI Craches on record through MQTT

### ISSUE THREAD

**Issue by MissMusic** [VorlonCD/bi-aidetection#151]
I know this isn't an AI-tool issue, just wanted to check if others have problems with BI craches on latest releases when triggered by MQTT?

**Comment by balucanb** [comment]
Not MQTT but the latest release of BI (yesterday) was crashing everytime it loaded. I just went back to the stable version and sent BI a error report

**Comment by VorlonCD** [comment]
Yeah not just MQTT - I had to revert back to last stable BI version in December too.    A temp fix is to delete the DB folder and let it re-create, then it works for a while.

If using the GPU version of deepstack on same machine and have hardware acceleration enabled for any of the cameras in BI it may be a factor but I didnt test too long before reverting back.

**Comment by Yonny24** [comment]
Good to know - I clicked cancel last night luckily!

**Comment by MissMusic** [comment]
Ok, not just me who have problems. I downgraded to latest stable. AI-tool with GPU DeepStack works fine, and video is recorded in BI on detection, but my BI database seems messed up, it won't show any new clips at all. I tried a DB repair but no change.

**Comment by Yonny24** [comment]
I'm on release 5.3.7.12 (05/01/2021).
Seems to be behaving luckily, mqtt and snapshots/clips working

**Comment by MissMusic** [comment]
@Yonny24 I upgraded to 5.3.7.13 (12 is no longer availabe in the list) and it seems to work well. I fixed my "clips not showing" by opening the dialogue-box for the DB-folder location and selecting the same folder again. Everything seems to work on 5.3.7.x so far.

**Comment by Tinbum1** [comment]
My BI has just updated and it gone to 5.3.8.12

**Comment by balucanb** [comment]
Let us know if it is crashing. Ken from BI had worked on mine all day, it was solid for about 31/2 hours then he popped back in did something and now I am back to it crashing every 2-10 min☹️. I had just told @VorlonCD that I was GTG and then it started crashing again!! Arrgg.

**Comment by Tinbum1** [comment]
I did have a short spell of crashing around the 5.3.7.x era but the 5.3.8.x have been ok.

**Comment by MissMusic** [comment]
Mine were running if i turned AI-tool off, but crashed instantly (within 10s) if i started AI-tool again. I thought it was the MQTT-record messages because that's how the two programs interact, but as @VorlonCD mentioned it could have been from running camera decoding and the GPU version of DeepStack on the same machine.
