### ISSUE TITLE
Actions do not trigger

### ISSUE THREAD

**Issue by YOZZOPANOZZO** [VorlonCD/bi-aidetection#152]
I should mention that I had to compile  the project myself since the precompiled one would not connect to deepstack (something about it being partially started).
Once compiled, it works fine as far as processing the images and detecting, but when there is a match in the image, the mqtt trigger I've set does not fire ( the mqtt config is not the culprit here since it does work when I click "Test" in the mqtt configuration, but does not when clicking "Test" in the Action configuration page)

Could this be releted with this error? ( iI get this every time a image is processed)
( I am not using  blue iris with this setup , I followed [this ](https://www.reddit.com/r/homeassistant/comments/kajp58/reolink_cameras_ai_tool_home_assistant_free/)guide which uses Ispy to capture images and a mqtt server in Homeassitant.
![Capture](https://user-images.githubusercontent.com/54823311/105594164-60c48680-5d93-11eb-88cf-a1cfa65d4ec0.PNG)

I downloded DeepStack from [here](https://github.com/johnolafenwa/DeepStack/releases/download/0.2-beta/DeepStack-Installer-CPU.2021.01.beta.exe)

**Comment by VorlonCD** [comment]
You have to update all the NuGet packages before compile - Project menu > Manage nuget > Update anything available, then recompile.   My guess is the SQLite packages are out of date.

If that doesnt help I would have to see the log from the beginning of the session up to the first set of errors.

**Comment by YOZZOPANOZZO** [comment]
I updated everything and ricompiled, but unfortunately nothing changed. As soon as I open it I get two errors.  These are the logs, and when something is detected the mqtt trigger fails to fire
[2 Errors after startup.txt](https://github.com/VorlonCD/bi-aidetection/files/5861028/2.Errors.after.startup.txt)
[Error when failing to notify via mqtt.log](https://github.com/VorlonCD/bi-aidetection/files/5861030/Error.when.failing.to.notify.via.mqtt.log)

**Comment by VorlonCD** [comment]
Never actually tried to compile with "Release" before.    Try switching back to DEBUG/any CPU before compile.  
![image](https://user-images.githubusercontent.com/7512113/105614223-11338a00-5d96-11eb-89c5-5de213c500c7.png)
 
Maybe release is trying to compile a 32 bit app, causing the SQLITE "Incorrect format" error (a conflict between 32 bit and 64 bit):

![image](https://user-images.githubusercontent.com/7512113/105614210-fbbe6000-5d95-11eb-9eac-699efbc6bf8d.png)

Before compile maybe make sure nothing exists in the folder ahead of time?

**Comment by YOZZOPANOZZO** [comment]
That did the trick thank you, the error went away and the mqtt trigger is now working properly. 
Thanks

**Comment by YOZZOPANOZZO** [comment]
That did the trick thank you, the error went away and the mqtt trigger is now working properly.
Thanks
