### ISSUE TITLE
FYI - AI Tool flagged as ransomware by Malwarebytes

### ISSUE THREAD

**Issue by JuraasicCoasterNerd** [VorlonCD/bi-aidetection#153]
Just in case anyone runs across this.

Noticed that I hadn't gotten any updates from AI tool today, so I logged into my server and the EXE was GONE. Come to find out Malwarebytes doesn't like AI Tool and marks it as ransomware. So, @VorlonCD when you going to start asking for bitcoins for the service?

All kidding aside, just leaving this here in case anyone comes across the same issue. 

![image](https://user-images.githubusercontent.com/16529122/105764071-7d43f880-5f24-11eb-8154-91d47009979b.png)

**Comment by VorlonCD** [comment]
Gee i hope no one does a code review and fixes all the bugs. ;)
