### ISSUE TITLE
Processing non stop

### ISSUE THREAD

**Issue by MontySA** [VorlonCD/bi-aidetection#154]
1-Seems there is something wrong. AI tool will process 1 or 2 images after opening then it will just say processing ....jpg and gets stiuck there. 100 images que and thats where its stuck

2-Also seems there is a confidence error where min confidence if you set it anything other than 0 you get errors.
3-Also you can change the confidence range till you blue in the face and its not working. Im getting 85% that its a vehicle but in history says it does not fall with in the range of confidence. No matter what I set it wont fall in the range

**Comment by balucanb** [comment]
Since you did not say if you are running the windows version or Docker or which version of AI-tool it would be hard for the devs to tell you exactly what may be going on. However, I had a similar issue in the past. First I would try to re-install AI-tool and Deepstack. That seems to correct many issues pretty quick. Hope this helps you.

**Comment by MontySA** [comment]
Good Day, apologies. Im running windows. ITs also giving errors "no default camera found. Aborting" I did create a default camera profile and still same error

**Comment by balqosz** [comment]
Hi Monty, what is the AI Tool version you are using? I think you may be using an older version.

**Comment by VorlonCD** [comment]
@MontySA  - Fyi here is the latest version.  Let me know if it works any better.  Although it sounds like you had a deepstack issue, so be sure you are using the very latest version (deepstack was just updated last week I think)
https://github.com/VorlonCD/bi-aidetection/files/5978621/AITool-VorlonCD-v2.0.700.zip
