### ISSUE TITLE
Issues with 2.0.626

### ISSUE THREAD

**Issue by Ryushin** [VorlonCD/bi-aidetection#158]
Modifying a Variable in Camera Settings does not stick. It shows the change.  Closing it and going right back into Variables shows the change did not take place.

Under Camera Settings the [BlueIrisURL] is incorrect.  It's adding https to the detected IP it seems.  For me it's pulling my IPv6 IP and looks something like: ```https://[2001:1234:1234:::10]:80``` but the IP is wrong as well as it has three colons ":"  before the 10 instead of the proper two.

The Camera Settings Test button also does not work unless there is an image for that camera already in the AI Input folder.

It would be good to be able to specify the Blue Iris URL under the main settings.  There is "Blue Iris Server Name" there.  Perhaps add the URL setting there or probably better yet would be to add the Port along with a SSL check box to the Blue Iris Server Name and leave out the whole URL entirely.

I tried deleting the cameras and then the entire AITool folder as well trying to fix it.  Does the AI Tool store the settings in registry?  Starting with a fresh folder detected what seemed like some previous settings.  It would be nice to have all the settings stored in text files.

Thanks for maintaining and extending this tool.  I've just started using it over the last few days.  It's going to bring a whole new level of functionality to Blue Iris which I've also started using over the last month.

**Comment by Tinbum1** [comment]
_Modifying a Variable in Camera Settings does not stick. It shows the change. Closing it and going right back into Variables shows the change did not take place._

Did you click SAVE

**Comment by VorlonCD** [comment]
No ipv6 support yet, use ipv4.   Did hitting save work?

**Comment by Ryushin** [comment]
I click save multiple times.  

Thing is, just closing the variables window and then going right back into it reverts any changes made to it previously.  It is pulling the IPv6 address from the box instead of the IPv4 address.

**Comment by VorlonCD** [comment]
@Ryushin - This one *may* support IPV6.  I put in a lot of work to support it but didnt do very comprehensive testing.    But I think the reason it was switching to IPV6 is because the BLUEIRIS settings for which network adapter/ip to bind to keep getting reset.  I had that happen to me the other day.   But when resolving anything, AITOOL prefers IPV4 if available:
[AITool-VorlonCD-v2.0.700.zip](https://github.com/VorlonCD/bi-aidetection/files/5978621/AITool-VorlonCD-v2.0.700.zip)

**Comment by Ryushin** [comment]
I'm afraid I don't know what to say.  The issues I posted above are still occurring.  I overwrote the files from the zip file.  I deleted a camera and added it back.  Let me know if you want me to delete my AI_Tool folder and start over from scratch.  I know you are focusing on the IPv6 issue but that was actually not the main problem.  The variables are static and I cannot change the [BlueIrisURL].  The [BlueIrisURL] populates with a IPv6 address with the incorrect three colons.   I'm okay with AITOOL with limiting to IPv4 even though my network is dual stack IPv4 and IPv6.  I was actually surprised that AITool even pulled the IPv6 address out.  Heck, my cameras don't support IPv6 (I'll need to email them about that).  Please let me know if there is anything else I can test with.

**Comment by VorlonCD** [comment]
Use the new reset button

**Comment by VorlonCD** [comment]
OH maybe I was confused by your first post anyway!    Clicking the Camera >Actions >**VARIABLES button** is simply for information, you cannot change those values.   It is just to show you an example of what the value would be when the variable expands in other places.

Since AITOOL reads the BlueIris settings directly from the registry, go into BlueIris > Settings > **Web server**, and make sure the LOCAL address is set correctly to IPv4.  And set to "Bind Exclusively".  This is what I was talking about before - mine seems to be constantly re-setting itself to an address I don't want.  Also, the RESET button was for you so that it deletes the registry setting that stores the backup also.

**Comment by Ryushin** [comment]
I'm afraid I don't know what to say.  The issues I posted above are still occurring.  I overwrote the files from the zip file.  I deleted a camera and added it back.  Let me know if you want me to delete my AI_Tool folder and start over from scratch.  I know you are focusing on the IPv6 issue but that was actually not the main problem.  The variables are static and I cannot change the [BlueIrisURL].  The [BlueIrisURL] populates with a IPv6 address with the incorrect three colons.   I'm okay with AITOOL with limiting to IPv4 even though my network is dual stack IPv4 and IPv6.  I was actually surprised that AITool even pulled the IPv6 address out.  Heck, my cameras don't support IPv6 (I'll need to email them about that).  Please let me know if there is anything else I can test with.

**Comment by Ryushin** [comment]
Looks the issues are not issues after all.  Thank you for your work in looking to this.  I appreciate it.

**Comment by VorlonCD** [comment]
Sigh.  I want to support ipv6.  It's kind of the future.

**Comment by Ryushin** [comment]
> 
> 
> Sigh. I want to support ipv6. It's kind of the future.

Then by all means lets support IPv6.  I'm open to testing in anyway.  My Deepstack is also accessible via IPv6.  I emailed Blue Iris support regarding their IPv6 syntax being wrong with three colons.

What would you like me to test that you been working on.

**Comment by VorlonCD** [comment]
Well, you could test ipv6 for deepstack server URL's.   In theory if you dont put [ ] around it in the IP in the URL it should add it for you automatically.

**Comment by VorlonCD** [comment]
Also, why didnt you just set BI to an IPV4 address in the web server settings?

But this copy will convert 3 colons to 2 anyway:
[AITool-VorlonCD-v2.0.720.zip](https://github.com/VorlonCD/bi-aidetection/files/6006524/AITool-VorlonCD-v2.0.720.zip)

**Comment by VorlonCD** [comment]
In theory ipv6 should be supported everywhere for several versions.
