### ISSUE TITLE
Selecting all dynamic masks causes exception

### ISSUE THREAD

**Issue by Tinbum1** [VorlonCD/bi-aidetection#16]
On the Cameras/Details page if you try to select more than one active mask it brings up an exception error.

**Comment by VorlonCD** [comment]
The latest should resolve this.  Let me know

**Comment by Tinbum1** [comment]
Thanks, yes does but operation only carried out on one of the highlighted.

Also finding that history isn't getting deleted automatically. (I had it set at 10 mins and it seemed to work OK then I changed it to 120 and it doesn't. Don't know if that's related or coincidence).
