### ISSUE TITLE
File watcher The semaphore timeout period has expired

### ISSUE THREAD

**Issue by othertortoise24** [VorlonCD/bi-aidetection#161]
I'm current using windows 10, AI Tool 2.0.522 and running docker for windows for my BI container. 

I get this error once a day. Once the error happens the AI tool stops doing recognition on the images. 

 _File watcher  The semaphore timeout period has expired on path 'U:\BlueIris\AI Input'
 File watcher  The specified network name is no longer available on path '\\*LAN ip*\Surveillance\BlueIris\AI Input'_

The path is to a NAS drive that logs in using a surveillance specific user. If i restart the program it starts working again. I thought about trying to run a task to restart my computer every night but I cant figure out how to launch docker for windows and run a container automatically. Also I don't want the computer to not be password protected. 

Any ideas?

**Comment by VorlonCD** [comment]
Look in recent issue posts for a newer release within the last week.   A while before that I posted an update that would automatically retry broken file watcher connections every xx minutes - maybe 10 or 15 but I dont remember what the default was.

**Comment by othertortoise24** [comment]
Thanks for the quick response. Ill try it out and see if it happens again in the next 24 hours.

**Comment by othertortoise24** [comment]
After updating to the latest version I could find the issue continues to persist. I wonder if its something to do with my network or the NAS network folder having problems.

**Comment by VorlonCD** [comment]
I would need any log entries from the CreateFileWatcherAsync, UpdateWatchers, "OnError" and TimerCheckFileSystemWatchers.
By default, it keeps retrying every 300000ms / 5 minutes.   You should see that retry activity in the above functions in the log.
Perhaps rather than a mapped drive letter U: use the UNC path of \\ipaddress\share\ ?

**Comment by othertortoise24** [comment]
I'm getting an error for the UNC file path also. 
![Screenshot 2021-02-09 084507](https://user-images.githubusercontent.com/46113637/107701579-f73ae800-6c6d-11eb-8c0c-9432a76ab309.png)

**Comment by VorlonCD** [comment]
@othertortoise24 - I did fix at least one bug related to this so it may work a bit better.   Basically I had to stop more than one thread trying to re-try the file watcher connection when it has an error:
[AITool-VorlonCD-v2.0.700.zip](https://github.com/VorlonCD/bi-aidetection/files/5978621/AITool-VorlonCD-v2.0.700.zip)

If the connection keeps breaking I would chat with support for your device

**Comment by othertortoise24** [comment]
I updated and still had the problem last night. The program tried to reconnect several times but couldn't. I will look at options for my device because its probably not an issue with AI tools at this point. Thanks for the followup and putting your time in to improve the program!
