### ISSUE TITLE
Deepstack not reachable

### ISSUE THREAD

**Issue by YOZZOPANOZZO** [VorlonCD/bi-aidetection#162]
I copied a working configuration from a machine to another one and installed Deepstack, but I'm getting this error now.  I can reach Deepstack's at localhost:80 though
![Immagine 2021-02-05 230728](https://user-images.githubusercontent.com/54823311/107094709-cdb23480-6807-11eb-9899-1ba3b523dfea.png)

**Comment by balqosz** [comment]
Hi... may be those ips are in bad format  nnn.nnn.nnn.nnn?

**Comment by YOZZOPANOZZO** [comment]
Sorry, I'm not too sure what your are referring to 😅, what ips?

**Comment by balqosz** [comment]
Sorry, I think the image has been edited. 

I was referring to this image:

![image](https://user-images.githubusercontent.com/24378221/107104741-b40dee80-6801-11eb-9336-b573bfc4b4d9.png)

I don't know, may be the log viewer is showing those address wrong..

192.168.2..1 should be 192.168.2.1 perhaps?
or 192.168.2.\1 should be 192.168.2.1... 

But I'm not sure it they are wrong, or the log viewer is showing them in that way..

**Comment by YOZZOPANOZZO** [comment]
Yes, There I tried to connect to a deepdstack server running on a different machine, just to see were the problem was. The ip was correct, it's just the log that shows it that way, no idea why it says that it's not vaild. I  cropped that part out because I thought it was not releted to the python.exe error I'm getting

**Comment by VorlonCD** [comment]
When deepstack for Windows starts, it opens 2 copies of Python.exe.   (3 for FACE option).    If 2 copies are not opening then deepstack for windows is either not the latest version OR the python instances are starting and then crashing.   This file will give you the error if they are crashing:

C:\Users\username\AppData\Local\DeepStack\logs\stderr.txt

Never seen that ip address weirdness, but the next version may be a little better at dealing with weird urls/ip addresses.   Also, maybe the configuration from the other machine isnt valid on this machine in some way?

![image](https://user-images.githubusercontent.com/7512113/107124321-3aade480-6871-11eb-885a-a0e01cba5864.png)

**Comment by YOZZOPANOZZO** [comment]
Hi, thank you for the quick reply, this is the content of the file you metioned: 
Traceback (most recent call last):
  File "C:\DeepStack\intelligencelayer\shared\detection.py", line 19, in <module>
    import torch
  File "C://DeepStack\windows_packages\torch\__init__.py", line 127, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C://DeepStack\windows_packages\torch\lib\asmjit.dll" or one of its dependencies.

I did installed python, and that ddl file is in the directory...

**Comment by VorlonCD** [comment]
You dont need to install python since deepstack folder already has it.
Try uninstalling python.   If still not working, uninstall/reinstall Deepsack for windows.   Heh I said deepsack.

Also if using the GPU version, try the CPU version.    

I think I've seen in the Deepstack forums someone was able to update several important deepstack components such as Torch, but I would avoid doing that until you know its working with out of the box components.  Then if trouble, ask in deepstack forums.

**Comment by GreenblingGSR** [comment]
@YOZZOPANOZZO Did you find a solution to this? I have the same issue.

I have:
new install of Windows 10
fresh download of "DeepStack-Installer-CPU-2021.02.1" installed.
fresh download of "AITool-VorlonCD-v2.0.626" installed.

I am getting the same errors.

**Comment by GreenblingGSR** [comment]
@VorlonCD 

I dont know what I am talking about. So I could be way wrong.
Does it matter that the file the code is looking for starts with starts "C://" instead of "C:\"

**Comment by YOZZOPANOZZO** [comment]
I did not unfortunately, I tried uninstalling python as Vorlon suggested and copying a known working deepstack installation from another machine but I'm still getting that error. Could it be because some deepstack's dependences that are missing? Not too sure to be honest.

**Comment by GreenblingGSR** [comment]
@YOZZOPANOZZO 

I got it working!

I was lying in bed last night and I remembered something...

I have another instance of deepstack + AI Tool  running that I set up a long time ago on another computer.
I remembered I had trouble with setting up that instance also.
To get that instance running I had to read through 70+ pages of forums to find the solution. 
Someone had mentioned that we had to install Visual C++.
So I jumped out of bed and installed "VC_redist.x64.exe" 
https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

I rebooted the computer and everything started working!

**Comment by YOZZOPANOZZO** [comment]
Yeah that was it! That solved it for me too! Thanks! 
I guess this solves it. Thanks again everyone.

**Comment by VorlonCD** [comment]
@YOZZOPANOZZO - ok, thanks for letting us know!!

At the very least this update should handle URL's better and may have prevented the weird broken URL screenshot you originally posted:
[AITool-VorlonCD-v2.0.700.zip](https://github.com/VorlonCD/bi-aidetection/files/5978621/AITool-VorlonCD-v2.0.700.zip)
