### ISSUE TITLE
Feature Request - minimum object size

### ISSUE THREAD

**Issue by xjustbmw** [VorlonCD/bi-aidetection#163]
Any plan to add the filter min / max height / width for detected objects based of  deepstack response ? ie: y_max - y_min , x_max - x_min ? 

in my case so far:
- huge tree shadows detected as human 
- cats in certain positions detected as human as well 
both with high confidence.

running deepstack beta gpu version on medium. the high mode triggers even more false alerts.

thanks

**Comment by VorlonCD** [comment]
Done - See new Prediction Tolerances screen.    To find out the prediction size and percentage look in History tab >Prediction Details screen:
[AITool-VorlonCD-v2.0.700.zip](https://github.com/VorlonCD/bi-aidetection/files/5978621/AITool-VorlonCD-v2.0.700.zip)

![image](https://user-images.githubusercontent.com/7512113/107891745-9a019980-6eee-11eb-9e88-eb792ae0ea2c.png)

Prediction details screen:
![image](https://user-images.githubusercontent.com/7512113/107891780-c61d1a80-6eee-11eb-9d21-c2975f21b326.png)

**Comment by xjustbmw** [comment]
amazing. thanks

**Comment by xjustbmw** [comment]
i think we have a little bug
![negativeCapture](https://user-images.githubusercontent.com/46851277/107932504-5195ba80-6f86-11eb-9e3e-970482b87d5f.PNG)

For some of the detected objects , Rectheight is having a negative value

**Comment by xjustbmw** [comment]
this seems to be only for 'relevant' objects. irrelevant are not affected by this

**Comment by xjustbmw** [comment]
it works for new detected images. all good :)

**Comment by VorlonCD** [comment]
This one should also update PercentOfImage for older entries, along with a few other changes I just posted to other issue threads:
[AITool-VorlonCD-v2.0.716.zip](https://github.com/VorlonCD/bi-aidetection/files/5992844/AITool-VorlonCD-v2.0.716.zip)
