### ISSUE TITLE
Deepstack Unauthorized

### ISSUE THREAD

**Issue by Johannp02180** [VorlonCD/bi-aidetection#164]
I'm getting an unauthorized error, everything was working fine up till a week ago. 
<img width="1091" alt="Screen Shot 2021-02-09 at 6 16 50 PM" src="https://user-images.githubusercontent.com/11222092/107441375-2123cb80-6b03-11eb-9da5-f96af15d1a3c.png">

**Comment by Johannp02180** [comment]
It seems that in the Deepstack console its processing the images tho

**Comment by VorlonCD** [comment]
The latest versions dont require any authorization:
https://forum.deepstack.cc/t/deepstack-february-2021-release-fixes-for-jetson-windows-native-and-docker-versions/724
