### ISSUE TITLE
Feature Request: URL trigger on detection type

### ISSUE THREAD

**Issue by Radical4Fish** [VorlonCD/bi-aidetection#165]
in actions you can have different things happen with different type detections IE: person ; C:\example\YOYO.WAV | bird ; C:\example\TWEET.WAV

it would be great if we could also do this with trigger URL's I use Homeseer home automation and what I would use this for is detecting the stork that comes in to my pond and eats my koi. 
so I would like to sent normal trigger to BI on via URL: on all detections to record the event, but on Brid trigger a url from my homeseer server to turn on the sprinkler at the pond and save my fish

if this is already an option I have not been able to find how to set it up (been searching for a few hours)

Thanks in advance for any help

**Comment by Nierka4** [comment]
Do you use MQTT? When triggered I send MQTT with [detections] and camera name message. Then in node red if its person or car in the driveway alexa will announce it. 
You could  easily trigger different Homeseer device/event with mqtt depending on detections.
![Capture](https://user-images.githubusercontent.com/22866191/107680838-fbfa9e80-6c63-11eb-9878-ae54369c6ee7.PNG)
![Capture2](https://user-images.githubusercontent.com/22866191/107680846-fef58f00-6c63-11eb-9c6e-cae745514144.PNG)

**Comment by Radical4Fish** [comment]
yes that would work but then I would need another service and im not using MQTT now(already a very fragmented system and this would just be one more failure point) this is where I will go if no other option is available.
what I'm looking to do is in url trigger as I can send homeseer json request to do stuff (like this 10.47.1.58/JSON?request=controldevicebyvalue&ref=541&value=100 that command turns on my 3d printer for example)
so what I would like is to have the ability to:
---http://localhost:88/admin?trigger&camera=porchsteps&user=xxxx&pw=xxxxx
---bird ; http://xx.xx.xx.xx/JSON?request=controldevicebyvalue&ref=577&value=100
then when anything trip the first line runs
if bird is detected both urls get called


![image](https://user-images.githubusercontent.com/35976359/107703192-2d796700-6c70-11eb-9cc4-42b2e9ae97d3.png)

**Comment by VorlonCD** [comment]
Done.   use "person,car ; RESTOFURL" format:
[AITool-VorlonCD-v2.0.700.zip](https://github.com/VorlonCD/bi-aidetection/files/5978621/AITool-VorlonCD-v2.0.700.zip)

**Comment by Radical4Fish** [comment]
@VorlonCD You rock Thanks

**Comment by Tinbum1** [comment]
> 
> 
> Do you use MQTT? When triggered I send MQTT with [detections] and camera name message. Then in node red if its person or car in the driveway alexa will announce it.
> You could easily trigger different Homeseer device/event with mqtt depending on detections.
> ![Capture](https://user-images.githubusercontent.com/22866191/107680838-fbfa9e80-6c63-11eb-9878-ae54369c6ee7.PNG)
> ![Capture2](https://user-images.githubusercontent.com/22866191/107680846-fef58f00-6c63-11eb-9c6e-cae745514144.PNG)
This sound really good, any chance of posting the flow for this?

**Comment by Nierka4** [comment]
There you go @Tinbum1 
[flows.zip](https://github.com/VorlonCD/bi-aidetection/files/6015633/flows.zip)

**Comment by Tinbum1** [comment]
Thank you so much.
