### ISSUE TITLE
Getting Notification for Object in Mask

### ISSUE THREAD

**Issue by xdreamwalker** [VorlonCD/bi-aidetection#166]
I am getting a notification, Telegram/Pushover, for an object that is in both the masked area and Objects for notifications. It seems that the objects in the Action settings for notifications are taking priority over the masked out areas.

I have some mailboxes masked out as they keep getting detected as people.
I have People and Car set as relevant objects.
I have People set as an object I'd like to get a notification for.
When a car comes into the street and the mailbox gets labeled as a person I get a Pushover notification even though the mailbox is masked out.

![Capture](https://user-images.githubusercontent.com/24192512/107784602-a680c900-6d19-11eb-906a-b688d228fbb8.PNG)

**Comment by VorlonCD** [comment]
I may have fixed it - say tuned for an update in a few days

**Comment by VorlonCD** [comment]
Ok, let me know if this is fixed.   I have no idea why someone didnt report this earlier.
[AITool-VorlonCD-v2.0.700.zip](https://github.com/VorlonCD/bi-aidetection/files/5978621/AITool-VorlonCD-v2.0.700.zip)

**Comment by xdreamwalker** [comment]
That's done it. I did not get a Pushover notification for this image. 👍
![Screenshot_20210215-094511](https://user-images.githubusercontent.com/24192512/107960526-c2cb7280-6f72-11eb-9ad4-2dcb722f452f.png)
