### ISSUE TITLE
Add JSON formatted output options

### ISSUE THREAD

**Issue by linuxkidd** [VorlonCD/bi-aidetection#168]
For integration into home-automation tools like HomeAssistant, json formatted output makes parsing much easier since it's a built in function of the software.

Possibly template names could be '[SummaryJson]', '[DetectionsJson]', '[AllJson]' (for inclusion of all possible data).

Sample for an '[AllJson]' output:
```
{
  "fileName":"/images/FrontDoor_20200523-075000.jpg",
  "basename":"FrontDoor_20200523-075000.jpg",
  "name": "Front Door",
  "analysisDurationMs": 236,
  "detections":[
    {
      "confidence":0.9681682,
      "label":"dog",
      "y_min":31,
      "x_min":125,
      "y_max":784,
      "x_max":1209
    }
  ],
  "summary": "dog (97%)",
  "state": "on"
}
```

**Comment by VorlonCD** [comment]
@linuxkidd - How is this working?
[AITool-VorlonCD-v2.0.759.zip](https://github.com/VorlonCD/bi-aidetection/files/6016864/AITool-VorlonCD-v2.0.759.zip)

**Comment by linuxkidd** [comment]
JSON looks good..

Is there a way to get an 'ALL' output that only shows matched relevant items?  I noticed this in some of the other outputs too..  The messages contain every match, not just the relevant ones.  Possibly add [AllRelevantJson] or similar.. :)

Thanks for your prompt work on this!

**Comment by VorlonCD** [comment]
enable History tab > Settings > Show only relevant objects.   It hides non-relevant globally.

**Comment by linuxkidd** [comment]
@VorlonCD Thanks, that works.. it may be worth adding a separate selection in the Actions settings as a more obvious control element. :)

**Comment by tommyjlong** [comment]
Oh wow!  I was just about to ask if it was possible for MQTT to have JSON output (also for Home Assistant).

**Comment by tommyjlong** [comment]
I've been playing with the `AllJson` for a couple of days.  I was getting masked objects showing up in MQTT until I set the "Show only relevant objects" as mentioned above.   Only other suggestion I would make is to add a timestamp to the MQTT message or something so that the message can be tied back to a log entry.

For anyone else using Home Assistant, here are a few sample templates that can be tried in the Developer's Tools for `AllJson` (in this example, `camera_json` is the received MQTT message):
```
Filename is {{camera_json.fileName }}
Predictions are {{camera_json.predictions}}
1st Label is {{camera_json.predictions[0].label}}
2nd Label is {{camera_json.predictions[1].label}}
{% set ns = namespace(found = false) %}
{%  for foo in camera_json.predictions %}
  {{foo.label}}
  {% if foo.label == 'Car' and foo.confidence >=10 %}
    {% set ns.found = true %}
    true
  {% endif %}
{% endfor %}
{{ns.found}}
```
Thanks for your work on this :)

**Comment by VorlonCD** [comment]
I'll add the date/time for a build sometime this weekend.  Anything else?   Its easy to add more.
Also adding the "Show only relevant objects" checkbox right in Actions to make it more obvious.

**Comment by VorlonCD** [comment]
A few updates for AllJson - Time, Cameraname and AIServername:
[AITool-VorlonCD-v2.0.845.zip](https://github.com/VorlonCD/bi-aidetection/files/6071586/AITool-VorlonCD-v2.0.845.zip)
