### ISSUE TITLE
Add delayed 'Off' action

### ISSUE THREAD

**Issue by linuxkidd** [VorlonCD/bi-aidetection#169]
For integration into home-automation tools like HomeAssistant, a delayed 'off' state would be useful when using the AITool input as a 'motion' detection binary.  Configurable 'Off' delay would be good for maximum flexibility.

Sample off JSON message:
`{ "state": "off" }`

**Comment by VorlonCD** [comment]
You mean through mqtt?   So AITOOL would respond to on or off command?   Need a bit more detail.

**Comment by linuxkidd** [comment]
Hi @VorlonCD ... So, after a 'trigger' topic is fired, would like to have a configurable delay, so that if subsequent triggers are not detected, a cancel message is fired.

e.g. Detected a cat - Trigger Topic/message fired
6 seconds after last cat trigger, send Cancel topic/message

**Comment by linuxkidd** [comment]
One possible option for this is to provide an option to send the 'Cancel' topic/message ( or URL ) after the 'Cooldown' period has expired.

**Comment by VorlonCD** [comment]
I think I already added this a few months ago?

In AITOOL.SETTINGS.JSON you will see "ActionCancelSeconds" and it defaults to 30.   If you need to change it, close the program, then edit.

Then in logs, if you have a CANCEL action set up for URL or MQTT you will see lines like these in the log:

- EXTENDING cancel action time for camera
- Cancel action queued for camera
- Removed cancel action in queue for camera

**Comment by linuxkidd** [comment]
Thanks!
