### ISSUE TITLE
Correct tab order of fields

### ISSUE THREAD

**Issue by linuxkidd** [VorlonCD/bi-aidetection#170]
When entering values in open fields in the UI, it is common for experienced users to utilize the Tab key ( and Shift-Tab ) to move forward / backward through the fields.  Current tab order of fields seems nonsensical and results in poor user experience.

**Examples:**
- Click to place cursor in the 'Name' field of a Camera settings
- Press Tab -> 'Enabled AI Detection' highlighted (good)
- Press Tab again -> Highlight skips the 'Input file begins with' row, skips 'Input Folder' row fields, goes to 'Person' in 'Relevant Objects section'
- Continuing to press Tab shows a seemingly random order after all 'Relevant Objects' are cycled through.

Similarly, on the 'Actions' view, the Tab order seems completely random

**Expected results:**
If one places the highlight / cursor on the top left most field, pressing Tab would advance the highlight / cursor position from left to right, then advancing down to the next row, left most field and advancing to the right from there, etc.

Once all input fields have been cycled through, the action buttons should be highlighted again, in order from left to right.

**Comment by VorlonCD** [comment]
This should be mostly fixed:
[AITool-VorlonCD-v2.0.702.zip](https://github.com/VorlonCD/bi-aidetection/files/5984425/AITool-VorlonCD-v2.0.702.zip)
