### ISSUE TITLE
[Feature Req] Add "Pause" Function to History Tab

### ISSUE THREAD

**Issue by MaleNurse** [VorlonCD/bi-aidetection#173]
I tend to scroll through my history every so often to look for images to add to my custom training set (missed ID's etc). Whenever there is a new event, though, the history jumps to the bottom to display the new image. When having to scroll through 2000 images on a windy day, this can get a bit taxing. It would be nice if either there was a button to pause this action, or the action is paused auto-magically when an image other that the most recent is selected.

Thanks for you work!

**Comment by VorlonCD** [comment]
Does this work?  History tab > settings > disable Auto refresh.

**Comment by MaleNurse** [comment]
Oh god, I don't know why my eyes skipped over that and I didn't see that. So sorry for having made you you have to type that out... 


![picard-meme-facepalm](https://user-images.githubusercontent.com/12175293/108092112-3a5fd700-7031-11eb-957a-44409968fdd2.jpg)

**Comment by VorlonCD** [comment]
No problem!

![image](https://user-images.githubusercontent.com/7512113/108099689-f251ac00-7052-11eb-9334-e88ad23f6aa1.png)
