### ISSUE TITLE
Program did not shutdown gracefully - AITool Version 2.0.703.7716

### ISSUE THREAD

**Issue by Village-Guy** [VorlonCD/bi-aidetection#174]
When run as a service, despite a clean log, this error is logged and reproducible:

Program did not shutdown gracefully.  Last log entry was 'not set', 'checkpoint: HistoryUpdateTimer: 16/02/2021 16:11:29'

**Comment by VorlonCD** [comment]
**Before** running the GUI, **STOP** the service first.   This is the recommended way to do it.  I think the error is caused by not doing it this way?    Have it run as a "True" service is still on my mental list.  Along with all the squirrels.

**Comment by Village-Guy** [comment]
Fair enough, so long as you are aware of the error message.  I only flagged it because the message was as I seem to remember different to the last release in October.
