### ISSUE TITLE
Mislabelling of "Success" and Cooldown Times

### ISSUE THREAD

**Issue by MaleNurse** [VorlonCD/bi-aidetection#175]
While the configured cooldown time is being respected in terms of alerts, images in the history that were actually skipped b/c of cooldown are listed as successes. I think this may be due to history thinking the cooldown time is shorter than it actually is. On images labelled "skipped" in history, the top banner says the cool down is 22s when it's actually 45s, and the images that are captured 22-45s after an alert are labelled as alerts in the history, even if they are only a few seconds apart themselves. Images and logs are attached here:
![cam settings](https://user-images.githubusercontent.com/12175293/108091762-dd642100-7030-11eb-983a-6bce0956bada.jpg)
![History](https://user-images.githubusercontent.com/12175293/108091765-ddfcb780-7030-11eb-8740-0aebe2c29d45.jpg)
[Log Mislabel.txt](https://github.com/VorlonCD/bi-aidetection/files/5990062/Log.Mislabel.txt)

**Comment by Tinbum1** [comment]
@VorlonCD I seem to remember right at the very beginning of this VorlonCD fork of AITool some time settings were in practice half the actual setting- could this be related?

**Comment by VorlonCD** [comment]
This is in the code from @gentlepumpkin 's original code for this, and I just left it that way.   I'm sure there are references to it somewhere in the monster ipcamtalk forum post.

```
// check if camera is still in the first half of the cooldown. If yes, don't analyze to minimize cpu load.
//only analyze if 50% of the cameras cooldown time since last detection has passed
double halfcool = cam.cooldown_time_seconds / 2;
```
I dont think other cooldown settings are cut in half, just the main one.

**Comment by MaleNurse** [comment]
That's interesting. It's a good idea to cut down on load, but I guess I was surprised that any images were analyzed during cooldown, or that those images marked as "success" didn't have an associated push alert. I mean it's not a big deal either way since it's not really bringing the load that much above the baseline (some cameras tend to go nuts on windy days and it analyzes all of those) and it's not annoying me with any extra alerts. It's really just a visual thing when going through the history.

I did search through the ipcamtalk thread after @VorlonCD mentioned it and maybe it came [from the comments related to someone mentioning](https://ipcamtalk.com/threads/ai-motion-detection-with-blueiris-an-alternate-approach.48406/post-468053) that the cooldown was being enforced after irrelevant detections. Oddly searching the thread didn't come up with many result related to "cooldown" or "cool down" and had nothing for "halfcool", though.

**Comment by VorlonCD** [comment]
I would need to be convinced it was a good idea to remove the "half cool" feature since it has been in the code forever.  People may be expecting it to be this way.

**Comment by MaleNurse** [comment]
@VorlonCD Definitely not saying get rid of it. If it were me, all that would change is maybe an extra cue or changing in cueing on the history screen to indicate if an alert was sent (maybe bolding the line or changing background/font colors). The only reason I even noticed the discrepancy was that I was using it to audit behavior on the latest build, and when I saw two extra "successes" so close together and without associated alerts pushed it just stoked a bit of curiosity. But as I said, this isn't actually affecting functionality so even if you were so inclined, it's sorta low priority.

**Comment by Pilotguy20** [comment]
I played with cool down times as well.  I was getting a lot of skipped images.  I set them to a very short time.   I need it to keep hitting the URL to keep the HD stream running during detection.  It works well.   I one issue I run into some times is it keep firing telegram.  I have que service checked and the cameras and triggers are doing what I need them to do.  But if there is a lot of activity telegram get way behind with a backlog of alerts.  It would be nice to have a separate cool down time for each section on this page.  
In my instance, I would want it to always process the image and always trigger the url. But have a 60-90 second cool down time on telegram.  

This is an awesome program all and all.

**Comment by ExcelsiorEyer** [comment]
> I played with cool down times as well. I was getting a lot of skipped images. I set them to a very short time. I need it to keep hitting the URL to keep the HD stream running during detection. It works well. One issue I run into some times is it keep firing telegram. I have que service checked and the cameras and triggers are doing what I need them to do. But if there is a lot of activity telegram get way behind with a backlog of alerts. It would be nice to have a separate cool down time for each section on this page.
> In my instance, I would want it to always process the image and always trigger the url. But have a 60-90 second cool down time on telegram.
> 
> This is an awesome program all and all.

I second the idea of cooldown timer to apply only for the telegram alerts. It would be good if BI continues to get trigger messages from AI Tool as it keeps processing detected objects.

**Comment by VorlonCD** [comment]
You have been able to set "**pushover_cooldown_seconds**" and "**telegram_cooldown_seconds**" in **AITOOL.Settings.JSON** file for a number of versions, its not in the UI yet.   Just close the tool before modifying the file directly.   Here is latest in any case:

[AITool-VorlonCD-v2.0.988.zip](https://github.com/VorlonCD/bi-aidetection/files/6176514/AITool-VorlonCD-v2.0.988.zip)
