### ISSUE TITLE
Deleting default camera deletes the second camera in the list and retains the default after pressing save

### ISSUE THREAD

**Issue by Village-Guy** [VorlonCD/bi-aidetection#178]
As per title

**Comment by VorlonCD** [comment]
I force Default to come back because it is needed for somethings, but yeah I see what you mean it does delete something it shouldnt.

**Comment by VorlonCD** [comment]
@Village-Guy  - let me know how this one works:
[AITool-VorlonCD-v2.0.759.zip](https://github.com/VorlonCD/bi-aidetection/files/6016864/AITool-VorlonCD-v2.0.759.zip)

**Comment by Village-Guy** [comment]
@VorlonCD - Works for me

**Comment by Village-Guy** [comment]
FYI 
I now get this message when AITOOL is started while the service is running:
DEBUG> (Found a DEFAULT camera for 'None': 'Default')

**Comment by VorlonCD** [comment]
Should be harmless.  "None" is used when logging isnt logging about something happening with a specific camera.
