### ISSUE TITLE
Error: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by xdreamwalker** [VorlonCD/bi-aidetection#179]
Just now I noticed that I have a 'run away' error. There were over 30,000 error logs all with the same message:

Object reference not set to an instance of an object. [NullReferenceException] Mod: <RunTriggers>d__44 Line:257

I'm on 2.0.703.7716. I closed AI Tool and started it again and now it's running fine. It looks like the error has something to do with the default camera. I'm going to try to just remove that camera as I have every BI camera already in AI Tool.
Thank goodness only the first error was sent to Pushover... ;) 

![image](https://user-images.githubusercontent.com/24192512/108214932-bd029800-70fe-11eb-8e04-025093878fcc.png)

**Comment by xdreamwalker** [comment]
This happened again. Same error text, but the camera is one of my real cameras. I did get a BI notification, but without an image. So it appears the trigger worked partially

**Comment by VorlonCD** [comment]
I kind of suspect corruption in the config file (or it didnt migrate correctly from the last version), but at least this quick update will help narrow it down a bit more if it happens again:

[AITool-VorlonCD-v2.0.721.zip](https://github.com/VorlonCD/bi-aidetection/files/6010477/AITool-VorlonCD-v2.0.721.zip)

If it does, I may need to see the log entries around the error.

**Comment by xdreamwalker** [comment]
I've been running this version for 5-6 hours now and so far the errors have not come back.

**Comment by VorlonCD** [comment]
I didnt reall fix anything related to it, just added better error checking for it if does happen again.

**Comment by xdreamwalker** [comment]
Gotcha. I'll keep an eye on it and let you know what it does.

**Comment by xdreamwalker** [comment]
While it didn't 'run away' and create several thousand errors, there is one from last night.
![Capture](https://user-images.githubusercontent.com/24192512/108594301-44dae300-7347-11eb-992e-fea35b81fde2.PNG)
[AITool.[2021-02-19.5].log.zip](https://github.com/VorlonCD/bi-aidetection/files/6014859/AITool.2021-02-19.5.log.zip)

**Comment by VorlonCD** [comment]
This one any better?
[AITool-VorlonCD-v2.0.759.zip](https://github.com/VorlonCD/bi-aidetection/files/6016864/AITool-VorlonCD-v2.0.759.zip)

**Comment by xdreamwalker** [comment]
Installed. I'll keep an eye on it.

**Comment by xdreamwalker** [comment]
I did not see the error at all yesterday.

**Comment by Tinbum1** [comment]
I was seeing that error quite a lot but haven't seen it for a while now.

**Comment by xdreamwalker** [comment]
After running for a few days I have not seen this error again.

**Comment by VorlonCD** [comment]
ok, great
