### ISSUE TITLE
Error: LastCamImage not a valid path.... Working though?

### ISSUE THREAD

**Issue by sminker81** [VorlonCD/bi-aidetection#182]
Just want to say first that this app is awesome, and thanks for all your hard work. Its working near flawless with the Deepstack GPU windows version, MQTT, etc... I will be buying you a beer or 12.

Getting a weird error. It appears to be working, since the file is being placed in the specified location. Im only testing one camera right now. 

App version 700. This was doing it on a previous version also. Its the last error Im getting after updating to your most recent.

Could it be the file location naming? Im using the original AI app file location, since I have it installed as a service and dont feel like messing with it. Its working, so why bother lol.

<img width="693" alt="Screen Shot 2021-02-17 at 7 02 07 PM" src="https://user-images.githubusercontent.com/76228732/108288774-d46b7080-7152-11eb-9cda-5b6589abbb6e.png">
<img width="558" alt="Screen Shot 2021-02-17 at 7 02 32 PM" src="https://user-images.githubusercontent.com/76228732/108288779-d59c9d80-7152-11eb-93fd-ab42dbba1925.png">
<img width="581" alt="Screen Shot 2021-02-17 at 7 03 13 PM" src="https://user-images.githubusercontent.com/76228732/108288781-d59c9d80-7152-11eb-9145-fcbab02a25a6.png">

**Comment by VorlonCD** [comment]
Looks like I do a check to see if it looks like a valid folder and it will fail if the folder has a DOT in it.   So that would be why its failing.  (I just wanted to make sure someone didnt put a FILENAME.EXT in the FOLDER setting).

So just change . to _ or similar.

**Comment by VorlonCD** [comment]
This one removes the restriction that the folder cannot have a period in the name:
[AITool-VorlonCD-v2.0.720.zip](https://github.com/VorlonCD/bi-aidetection/files/6006524/AITool-VorlonCD-v2.0.720.zip)

**Comment by sminker81** [comment]
Thanks. I appreciate that. I literally just changed the directory and redid the service install like 5 minutes before you posted that lol.
