### ISSUE TITLE
Object Confidence Limits by Object

### ISSUE THREAD

**Issue by rtman238** [VorlonCD/bi-aidetection#185]
Is there a way to set  the object confidence limits by object? At night dogs at a certain angle are detected as a person with a low confidence level. Setting the dog to 40% and the person to 60% would solve this issue.

**Comment by Yonny24** [comment]
Great idea.

**Comment by VorlonCD** [comment]
@rtman238 - Done and done  (For everything except SOUND and URL TRIGGER options anyway):

[AITool-VorlonCD-v2.0.845.zip](https://github.com/VorlonCD/bi-aidetection/files/6071586/AITool-VorlonCD-v2.0.845.zip)

![image](https://user-images.githubusercontent.com/7512113/109710471-b3037f00-7b6b-11eb-9e84-e709b5dfdb1e.png)

**Comment by rtman238** [comment]
You're awesome!

**Comment by rtman238** [comment]
I am finding a couple of bugs with this form.

1. When selecting an item that already exists in the table above, changes made in the detail area are not applied to the table.
2. I assume that entering an object more than 1 time allows you to change confidence levels based on the schedule entered for each. If you later decide to delete 1 of the duplicates, the one highlighted will not necessarily be the one that is deleted. The highest priority is deleted first. That is a minor issue.

**Comment by rtman238** [comment]
This is working in 942.
