### ISSUE TITLE
[Feature Request] Add MQTT online, offline, and LWT options

### ISSUE THREAD

**Issue by linuxkidd** [VorlonCD/bi-aidetection#186]
In most MQTT systems, you can device the following messages:

* Online message
* Offline message ( sent when shutting down cleanly )
* Last Will & Testament ( Server triggers this after a specified timeout from the client, assuming it has died uncleanly )

Each of the above should allow for a configurable topic and message payload.

Thanks!

**Comment by VorlonCD** [comment]
This has been in the product for a month or so (just not officially released on github page, but any recent build should have the feature.

See:
https://github.com/VorlonCD/bi-aidetection/issues/131

**Comment by linuxkidd** [comment]
Great!  Is there a re-transmit interval for the online status?  This is useful for tools that start monitoring the MQTT feed after AITool is already running...

**Comment by linuxkidd** [comment]
In closer examination, I see the Online is retained... this is likely sufficient.  Thanks!
