### ISSUE TITLE
[Feature Request] Manual mask per object type.

### ISSUE THREAD

**Issue by MissMusic** [VorlonCD/bi-aidetection#192]
I have the issue that some parts of the frames, like houses, are recognized as trucks in some lighting conditions. If the detection is not constant, so the dynamic filter wont filter all detections. To not get false positives i add some manual masks but i would like to be able to mask for only a specific object or objects. I have tried to filter them out with higher confidence limits but DeepStack seems really confident some times so i start to filter out a lot of positive detections while still getting false ones.

For example, i would like to be able to add a manual mask rectangle that only makes the "truck" object detected in it irrelevant, but still triggers for say a person or any other camera-enabled object identified in the same area.

**Comment by VorlonCD** [comment]
This version lets you "ignore" the mask if a specific relevant object was detected.   Like if you want to mask out cars going by on the road but still want to alert on people.   Will that work?
[AITool-VorlonCD-v2.0.988.zip](https://github.com/VorlonCD/bi-aidetection/files/6176514/AITool-VorlonCD-v2.0.988.zip)

**Comment by MissMusic** [comment]
Thank you! It's probably good enough for me, i shall try it out.
