### ISSUE TITLE
DeepStack server URL saving as typing causing errors

### ISSUE THREAD

**Issue by MaleNurse** [VorlonCD/bi-aidetection#199]
As I modify the URL in the server settings, the URL saves itself without the save button being clicked. This is causing a new error nearly every keystroke as the program cannot find the incorrect address. This happens when creating a new record and modifying an existing one. The "autosave" only seems to be affecting the URL portion of the record.
![Screenshot 2021-03-12 073917](https://user-images.githubusercontent.com/12175293/110975806-0e283500-8315-11eb-9a69-43daf60b6bf1.jpg)

**Comment by VorlonCD** [comment]
Fixed?
[AITool-VorlonCD-v2.0.930.zip](https://github.com/VorlonCD/bi-aidetection/files/6135867/AITool-VorlonCD-v2.0.930.zip)

**Comment by MaleNurse** [comment]
That did the trick, thank you!
