### ISSUE TITLE
Computer lost power and now the AI tool no longer allows me to navigate.

### ISSUE THREAD

**Issue by jplivingston08** [VorlonCD/bi-aidetection#200]
The window feels zoomed in.  Awesome tool but hoping that someone can tell me an easy fix.  I even downloaded the files again and no change. Screenshot attached. 
![Capture](https://user-images.githubusercontent.com/58711463/111088474-c3b5dc80-84fd-11eb-95d7-fe276461f379.PNG)

**Comment by VorlonCD** [comment]
Quite a few builds since then, just all posted to forum threads.   Here is the latest:
https://github.com/VorlonCD/bi-aidetection/files/6137695/AITool-VorlonCD-v2.0.942.zip

**Comment by jplivingston08** [comment]
Thank you.

**Comment by VorlonCD** [comment]
Oh, a more recent version than above:
[AITool-VorlonCD-v2.0.988.zip](https://github.com/VorlonCD/bi-aidetection/files/6176514/AITool-VorlonCD-v2.0.988.zip)
