### ISSUE TITLE
Latest Version

### ISSUE THREAD

**Issue by DM-AU** [VorlonCD/bi-aidetection#201]
Hi,

Firstly thanks for the awesome software and maintaining it.

Secondly can you link me to the most recent version please? The latest release is from October last year and I know you have created new versions in some issues/support. I have been getting a few errors and before I go looking into it I would like to update.

Currently I have Version 2.0.582.7689 from 20/01/2021.

Thanks
David

**Comment by VorlonCD** [comment]
There is always one in recent issue threads.   Here is the latest:
https://github.com/VorlonCD/bi-aidetection/files/6137695/AITool-VorlonCD-v2.0.942.zip

**Comment by DM-AU** [comment]
Thanks

**Comment by chiller86** [comment]
Would be nice to update to a stable version in releases more often. I get there is always going to be bugs or new features on each release but it's hard to find the latest. I was a version behind (1.x) before you posted your latest 2020 one. Either way keep it up this will definitely turn in to something more than you expected. Thank you.

**Comment by VorlonCD** [comment]
Your a version behind?   I"M a version behind.

**Comment by sstratoti** [comment]
https://github.com/VorlonCD/bi-aidetection/issues/221#issuecomment-812885167

**Comment by pburnsworth** [comment]
Thanks for all of your hard work with AI Tool, it is an awesome tool and is greatly appreciated. I attempted to run the latest version that you linked in this thread, but when I click on the cameras tab AI Tool crashes. I followed the directions to extract and copy. Is this a known bug?

**Comment by VorlonCD** [comment]
Latest is always here, not in releases:
https://github.com/VorlonCD/bi-aidetection/tree/master/src/UI/Installer
