### ISSUE TITLE
No enabled camera with the same filename, cameraname, or prefix found for 'None'

### ISSUE THREAD

**Issue by dwertz1** [VorlonCD/bi-aidetection#202]
Just updated to the latest version 2.0.943.7743 from 2.0.526 (I think).

When I click on the cameras tab the application closes.  I get the debug message via my Telegram notification of:

No enabled camera with the same filename, cameraname, or prefix found for 'None'

Any idea?

**Comment by dwertz1** [comment]
I reverted to an older build 2.0.701.7715 and I can view the camera list now.

**Comment by VorlonCD** [comment]
can you get me the recent log file from \AITOOL\_SETTINGS\Logs folder?    To make sure the log is from the new build, re-install the latest build and try to replicate the crash again.  Keep a backup of the whole folder of course.

**Comment by dwertz1** [comment]
[aitool.[2021-03-15].log](https://github.com/VorlonCD/bi-aidetection/files/6143064/aitool.2021-03-15.log)

**Comment by VorlonCD** [comment]
weird, no useful error.  Try hitting Settings tab > Reset button.   It will make a backup of the _SETTINGS folder if you need to revert back to it

**Comment by dwertz1** [comment]
Tried that, still crashes when clicking on the cameras tab.  Here is an updated log FWIW:
[aitool.[2021-03-15] 1.log](https://github.com/VorlonCD/bi-aidetection/files/6144996/aitool.2021-03-15.1.log)

**Comment by dwertz1** [comment]
I reverted back to 2.0.701 for now.
Is this what the default camera settings should look like? (screenshot)

![image](https://user-images.githubusercontent.com/47992883/111236302-e3fe9d80-85c8-11eb-9ed6-65a305f917d8.png)

**Comment by VorlonCD** [comment]
What is weird is I reset and dont have a problem.    I suppose if you still have an old **CAMERAS** subfolder from original version of AITOOL it may be causing something unexpected to happen.    Try renaming or removing as it it no longer used.   (But it will try to import cameras from there if it exists)

If you delete the Default camera, it will come back with all default settings.   (It is now required)

But this one may have fixed the error.  If not, I added a bunch more error logging:
[AITool-VorlonCD-v2.0.955.zip](https://github.com/VorlonCD/bi-aidetection/files/6145550/AITool-VorlonCD-v2.0.955.zip)

**Comment by dwertz1** [comment]
Upgraded to 2.0.955 and all is well!  Thank you!
