### ISSUE TITLE
MQTT cancel's

### ISSUE THREAD

**Issue by cchiapusio** [VorlonCD/bi-aidetection#203]
I stopped getting MQTT cancel updates when I upgraded from 700 to 930 and the problem persists at 942.  Do I need to nuke my configuration and rebuild from scratch?

It would also be good if the MQTT 'test' would also send a cancel at the configured time limit.
I see MQTT retain option in the JSON, is that implemented/honored now and will it be brought up to the UI eventually?

**Comment by VorlonCD** [comment]
Retain does get honored, and the build below has it in the UI.   Test doesnt trigger a cancel to be queued, but if you right-click over a history item that doesnt have a detection and click "Test Detection again" it should test it.  Maybe.  Probably.

I may have also fixed MQTT action queue issue.

[AITool-VorlonCD-v2.0.943.zip](https://github.com/VorlonCD/bi-aidetection/files/6144806/AITool-VorlonCD-v2.0.943.zip)

For troubleshooting cancel action queued items, search log for:
* Cancel action queued for camera
* EXTENDING cancel action time for camera
* Removed cancel action in queue for camera

Although in this case I dont think any of those would have shown up.

**Comment by VorlonCD** [comment]
A few more MQTT tweaks.  Let me know how it works:
[AITool-VorlonCD-v2.0.955.zip](https://github.com/VorlonCD/bi-aidetection/files/6145550/AITool-VorlonCD-v2.0.955.zip)

**Comment by cchiapusio** [comment]
I tried with 943 last night and started with 2.0.956.7745 this morning and only got an intermittent cancel message.  I have even tried setting up a clean install and could not get a cancel message sent. Even looking in the logs and filtering MQTT shows only the detection message getting sent, cancel message getting queued... but never sent.

It appears the 'perform cancel actions' runs but there is no record of the MQTT cancel topic being sent.

search: MQTT|cancel

`

Date | Func | Detail | Level | Source | AIServer | Camera | Image | Idx | Depth | Color | ThreadID | FromFile | Filename
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
3/16/2021 4:12:04 PM | Connect | MQTT: Connecting to server '192.168.10.4:1883' with ClientID 'AITool-5404A64DD466', Username 'hass', Password '****'... | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | None | 449 | 4 |   | 15 | False | AITool.[2021-03-16].log
3/16/2021 4:12:04 PM | Connect | MQTT: ### CONNECTED WITH SERVER '192.168.10.4:1883' ### - Result: Success, '' | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | None | 470 | 7 |   | 7 | False | AITool.[2021-03-16].log
3/16/2021 4:12:04 PM | Connect | MQTT: Sending 'Online' message... | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | None | 471 | 7 |   | 7 | False | AITool.[2021-03-16].log
3/16/2021 4:12:04 PM | PublishAsync | MQTT: Sending topic 'BlueIris/sensor/amcrest1/ai' with payload 'Person (59%)' to server '192.168.10.4:1883'... | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | None | 472 | 6 |   | 8 | False | AITool.[2021-03-16].log
3/16/2021 4:12:04 PM | PublishAsync | MQTT: ...Sent in 120ms, Reason: 'Success' (0 - '') | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | None | 473 | 6 |   | 7 | False | AITool.[2021-03-16].log
3/16/2021 4:12:04 PM | RunTriggers | Cancel action queued for camera 'amcrest1hd', waiting 5 seconds... | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | amcrest1hd.20210316_161204361.jpg | 475 | 5 |   | 7 | False | AITool.[2021-03-16].log
3/16/2021 4:12:05 PM | RunTriggers | EXTENDING cancel action time for camera 'amcrest1hd', waiting 5 seconds... | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | amcrest1hd.20210316_161204865.jpg | 506 | 1 |   | 7 | False | AITool.[2021-03-16].log
3/16/2021 4:12:05 PM | RunTriggers | EXTENDING cancel action time for camera 'amcrest1hd', waiting 5 seconds... | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | amcrest1hd.20210316_161205372.jpg | 557 | 3 |   | 9 | False | AITool.[2021-03-16].log
3/16/2021 4:12:06 PM | PublishAsync | MQTT: Sending topic 'BlueIris/sensor/amcrest1/ai' with payload 'Person (30%)' to server '192.168.10.4:1883'... | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | None | 615 | 3 |   | 7 | False | AITool.[2021-03-16].log
3/16/2021 4:12:06 PM | PublishAsync | MQTT: ...Sent in 1ms, Reason: 'Success' (0 - '') | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | None | 616 | 3 |   | 5 | False | AITool.[2021-03-16].log
3/16/2021 4:12:06 PM | RunTriggers | EXTENDING cancel action time for camera 'amcrest1hd', waiting 5 seconds... | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | amcrest1hd.20210316_161205878.jpg | 618 | 2 |   | 5 | False | AITool.[2021-03-16].log
3/16/2021 4:12:06 PM | RunTriggers | EXTENDING cancel action time for camera 'amcrest1hd', waiting 5 seconds... | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | amcrest1hd.20210316_161206407.jpg | 663 | 3 |   | 8 | False | AITool.[2021-03-16].log
3/16/2021 4:12:07 PM | RunTriggers | EXTENDING cancel action time for camera 'amcrest1hd', waiting 5 seconds... | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | amcrest1hd.20210316_161206931.jpg | 714 | 4 |   | 5 | False | AITool.[2021-03-16].log
3/16/2021 4:12:07 PM | PublishAsync | MQTT: Sending topic 'BlueIris/sensor/amcrest1/ai' with payload 'Person (66%)' to server '192.168.10.4:1883'... | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | None | 779 | 3 |   | 8 | False | AITool.[2021-03-16].log
3/16/2021 4:12:07 PM | PublishAsync | MQTT: ...Sent in 0ms, Reason: 'Success' (0 - '') | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | None | 780 | 3 |   | 18 | False | AITool.[2021-03-16].log
3/16/2021 4:12:07 PM | RunTriggers | EXTENDING cancel action time for camera 'amcrest1hd', waiting 5 seconds... | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | amcrest1hd.20210316_161207436.jpg | 782 | 2 |   | 18 | False | AITool.[2021-03-16].log
3/16/2021 4:12:08 PM | DetectObjects | (5/6) Performing CANCEL actions: | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | amcrest1hd.20210316_161207941.jpg | 810 | 2 |   | 13 | False | AITool.[2021-03-16].log
3/16/2021 4:12:08 PM | DetectObjects | (5/6) Performing CANCEL actions: | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | amcrest1hd.20210316_161208463.jpg | 849 | 2 |   | 13 | False | AITool.[2021-03-16].log
3/16/2021 4:12:08 PM | CancelActionJobQueueLoop | Removed cancel action in queue for camera 'amcrest1hd', after 1.0456925 seconds | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | amcrest1hd.20210316_161204361.jpg | 862 | 0 |   | 8 | False | AITool.[2021-03-16].log
3/16/2021 4:12:09 PM | DetectObjects | (5/6) Performing CANCEL actions: | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | amcrest1hd.20210316_161208985.jpg | 893 | 1 |   | 13 | False | AITool.[2021-03-16].log
3/16/2021 4:12:09 PM | IsRelevant | RelevantObjectManager: Skipping 'MQTT' because objects were not defined to trigger, or were set to ignore: Relevant='(NONE)', Irrelevant='Refrigerator', Caused ignore='(NONE)', Not Enabled=(NONE), Not Time=(NONE), No Threshold Match=(NONE)  All Triggering Objects='Person, Bear, Elephant, Car, Truck, SUV, Van, Bicycle, Motorcycle, Bus, Dog, Horse, Boat, Train, Airplane, Zebra, Giraffe, Cow, Sheep, Cat, Bird', 1 predictions(s), Enabled=21 of 25 | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | None | 900 | 7 |   | 20 | False | AITool.[2021-03-16].log
3/16/2021 4:12:09 PM | DetectObjects | (5/6) Performing CANCEL actions: | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | amcrest1hd.20210316_161209493.jpg | 936 | 1 |   | 15 | False | AITool.[2021-03-16].log
3/16/2021 4:12:09 PM | IsRelevant | RelevantObjectManager: Skipping 'MQTT' because objects were not defined to trigger, or were set to ignore: Relevant='(NONE)', Irrelevant='Refrigerator', Caused ignore='(NONE)', Not Enabled=(NONE), Not Time=(NONE), No Threshold Match=(NONE)  All Triggering Objects='Person, Bear, Elephant, Car, Truck, SUV, Van, Bicycle, Motorcycle, Bus, Dog, Horse, Boat, Train, Airplane, Zebra, Giraffe, Cow, Sheep, Cat, Bird', 1 predictions(s), Enabled=21 of 25 | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | None | 946 | 6 |   | 20 | False | AITool.[2021-03-16].log
3/16/2021 4:12:10 PM | DetectObjects | (5/6) Performing CANCEL actions: | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | amcrest1hd.20210316_161210001.jpg | 975 | 2 |   | 13 | False | AITool.[2021-03-16].log
3/16/2021 4:12:10 PM | DetectObjects | (5/6) Performing CANCEL actions: | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | amcrest1hd.20210316_161210523.jpg | 1013 | 2 |   | 15 | False | AITool.[2021-03-16].log
3/16/2021 4:12:11 PM | DetectObjects | (5/6) Performing CANCEL actions: | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | amcrest1hd.20210316_161211046.jpg | 1051 | 2 |   | 15 | False | AITool.[2021-03-16].log
3/16/2021 4:12:11 PM | DetectObjects | (5/6) Performing CANCEL actions: | Debug | AITOOLS.EXE | Deepstack_Objects:192.168.10.4:5000 | amcrest1hd | amcrest1hd.20210316_161211576.jpg | 1089 | 2 |   | 17 | False | AITool.[2021-03-16].log

`

**Comment by VorlonCD** [comment]
I may have found the bug, but at the very least there is better logging if you still have trouble:
[AITool-VorlonCD-v2.0.988.zip](https://github.com/VorlonCD/bi-aidetection/files/6176514/AITool-VorlonCD-v2.0.988.zip)

**Comment by cchiapusio** [comment]
In basic testing, this is fixed.  I'll report back in about 24 hours on results from the real world.

**Comment by cchiapusio** [comment]
MQTT cancels are reliably being sent after 'Action Cancel Second'.  Thank you for your hard work.
