### ISSUE TITLE
AI server settings for object detection and 1 custom model?

### ISSUE THREAD

**Issue by Yonny24** [VorlonCD/bi-aidetection#206]
Hi. 
Now you have done the magic of enabling the custom model to be run in parallel with object detection I need some advice on the server settings.
Not too sure how to set this up in Edit AI Server IRL section.

Is this right or have I got the settings wrong? Basically, I've got the standard object detection running and created a custom model also.
I want every snapshot analyzed by both.

Thanks a lot. Keep up the amazing work!!

![image](https://user-images.githubusercontent.com/64428686/111930696-44458180-8a98-11eb-978c-e604e10bc6a2.png)

**Comment by VorlonCD** [comment]
I would have done it the other way around, but the way you have it **should** work.
In your MAIN deepstack server set IT to link with Custom.    Nothing enabled in Custom except maybe "Use only as linked server" so that it is never used by itself.

**Comment by Yonny24** [comment]
Thanks!
So it would be set this way:

Main server :

![image](https://user-images.githubusercontent.com/64428686/111999686-f8c4bf00-8afb-11eb-8d0a-e91df1c301ab.png)

and second custom model server:

![image](https://user-images.githubusercontent.com/64428686/111999766-0bd78f00-8afc-11eb-86ad-7f720e5895e3.png)

**Comment by Yonny24** [comment]
Nope that didn't work.

Changed the second server custom to this:

![image](https://user-images.githubusercontent.com/64428686/112000273-97e9b680-8afc-11eb-8924-10b28efd34a6.png)

**Comment by VorlonCD** [comment]
Nope:
Main: enable "link / combine" and check your custom server
Custom:  Enable "Use ONLY", and uncheck everything else.

**Comment by Yonny24** [comment]
Perfect seems to work that way now. I had to untick the greyed-out server drop-down, even though the main tick box was unticked for the custom. Well not sure if that is clear but processes all images now.

The other way round seemed to work but as you said better this way.

Thanks again!
