### ISSUE TITLE
Static Mask Ignored v2.0.988

### ISSUE THREAD

**Issue by rtman238** [VorlonCD/bi-aidetection#207]
I have a mask drawn around a mailbox that DeepStack identifies as a person. With 988 the mask is not applied with or without Dynamic Masking enabled.

**Comment by Tinbum1** [comment]
Have you checked mailbox is enabled in;

![image](https://user-images.githubusercontent.com/66704787/111991647-7264a900-8b0c-11eb-882d-9c17a28ffb68.png)

**Comment by rtman238** [comment]
My person is set the same as your #1 above. I have a mask setup for the object that shows it covered with the opaque yellow. My understanding is that no object should be recognized in the area of the drawn mask. It appears to me that this mask is no longer being applied.

**Comment by Tinbum1** [comment]
Apologies just realized I read it as a dynamic mask by mistake. 

Might be worth showing screen shot of image with mask. 

You could try - look in the history tab for it, right clicking on it /prediction details, right click /create static mask.

**Comment by VorlonCD** [comment]
Sometimes BI spits out different resolution images.  Not sure why.   But a new image mask has to be created for EACH one.   In the mask editor, hit SCAN, then see if there is more than one resolution listed - if so, edit the mask for each:
![image](https://user-images.githubusercontent.com/7512113/112004662-60790b00-8af8-11eb-8ed5-4cd3754d30ce.png)

Otherwise, I would need screenshot of History tab > select missed item > Prediction Details screen (Make sure all the MASK related columns are showing), and maybe the section of the LOG where it missed the mask if you can find it.

**Comment by rtman238** [comment]
When I scan I find 2 resolutions, 2688X1536 and 1008X576. I have BI set to drop the jpeg quality down to 50% in the daytime and back to 100% after dark but it appears they are all the same resolution when I check the file properties. I do not believe there are any 108X576 images in the AiInput folder. I will get some results from the log later today.

**Comment by rtman238** [comment]
Here is the masked area. The mask is on a 2688X1536 image.

![image](https://user-images.githubusercontent.com/79340363/112077216-00ab5000-8b4a-11eb-9626-51323e56f34f.png)

I triggered the camera and the mailbox was identified as a person.

![image](https://user-images.githubusercontent.com/79340363/112077103-bcb84b00-8b49-11eb-8caf-239d7793bedd.png)

Prediction object details. I think I have all the mask columns.

![image](https://user-images.githubusercontent.com/79340363/112078962-546b6880-8b4d-11eb-95ea-558b2fcf92f7.png)


Log for this image below.

![image](https://user-images.githubusercontent.com/79340363/112077720-12d9be00-8b4b-11eb-9081-963eea6e83d3.png)

![image](https://user-images.githubusercontent.com/79340363/112077824-3f8dd580-8b4b-11eb-964d-649e53e2c43e.png)

Below is the log from an image earlier using v2.0.943 showing image masked.

![v2 0 943 Mask Log](https://user-images.githubusercontent.com/79340363/112078139-da86af80-8b4b-11eb-98a7-de8c4fff60b0.JPG)

Let me know if you need more information.

**Comment by Tinbum1** [comment]
I would put a rectangular mask around the mail box- I think that's probably the problem.

I set my min confidence at about 62% which seems to get rid of most false alerts and not miss any positive ones.

**Comment by VorlonCD** [comment]
I fell for the same thing and I wrote the software.   I ask myself why do people keep getting detected behind masks in my driveway?  Because I told it to!

This means the ignore mask feature was enabled for the object:
![image](https://user-images.githubusercontent.com/7512113/112146566-1ce2d780-8bb2-11eb-90fc-28ff58a2522e.png)

And this is the setting:
![image](https://user-images.githubusercontent.com/7512113/112147020-9bd81000-8bb2-11eb-92cc-5c44a3351c20.png)

We can blame Tinbum because he suggested that feature :)

**Comment by rtman238** [comment]
Thanks for the feed back from both of you. 

So my assumption of how the process works is different than you described which explains why the person was ignoring the mask. My assumption was that the mask was applied to the image before sending to DeepStack. This would prevent DeepStack from recognizing any object in the masked area. Defining the mask by drawing on the image probably should be limited to rectangles to simplify the process of detecting the object. My logic in having the person ignore the mask was concerning Dynamic Masks. If a car pulls into he driveway and parks I would still like the person object to ignore the newly created Dynamic mask. I can make it work now that I have a better understanding. Another option would be to add a second set of settings for the custom mask.

You are able to add some incredible features so perhaps a feature to add would be to allow the user to create and name the static masks and apply the relevant object per defined mask. They could draw the rectangle and then name and save it. Give the user the option to enable or disable the mask which would allow the possibility of another program enabling and disabling the mask. Add a schedule to enabled or disable the mask for users that would not enable or disable with an URL or MTQQ. This would be useful for cars parked during specific times. You could draw the mask large enough to avoid issues that reflections cause off the parked vehicles. Enable this when home and disable when away.

**Comment by VorlonCD** [comment]
Would it help to have each object be able to either ignore the IMAGE MASK or the DYNAMIC mask separately?  Right know both are equally ignored.

Controlling masks and other things via MQTT is on the list.   Please provide as much detail as you can about how you would like this feature to work.

In BI > Trigger > Motion sensor, you can use ZONES to mask an area, then enable Blackout=Blackout masked areas.    This way you just see a black area in the actual image and no one can see the area.  Although deepstack will sometimes still think a square area void of any pixels looks like an object :)

**Comment by rtman238** [comment]
Thanks for the tip about BI blacking out a masked area.

It would be helpful to be able to have an object be ignored by the Image mask and not ignored by the Dynamic mask. The picture with the mailbox is an example. In the image mask I would ignore people but if a truck pulls up and a person gets out they are not recognized until they move away from the vehicle that is Dynamically masked. In that situation I would want person to ignore the Dynamic mask but not the Image mask.

I think it is very useful to be able to have different threshold settings and active time ranges for Relevant objects and the multiple actions. I can see how someone would want AiTool to detect and log objects without triggering.

I believe for the Dynamic mask there are some redundant settings. I wonder if enable, trigger, and the threshold settings are necessary for the masks. The active time is very useful and Ignore Mask is essential.

I would like the ability to create multiple Image masks. These would be managed independently of other Image masks and the Dynamic masks. The Image masks should have the ability to be enabled or disabled. The current screen the Custom button opens would need a box to name the Image mask perhaps the enable box could be on this screen and the settings for the mask to set the active time range and which object ignore the mask. The other option for the Image mask management would be to populate these masks list under masking settings. If you choose that route it would be best to move the enable Dynamic masking to the masking settings so that the Image masks would be enable at the same place that the Dynamic mask is enabled. The first option may require the least effort to implement. With multiple image masks I would create 1 mask to ignore cars that I would enable via MQTT when home. I would create a second mask to ignore objects that are detected as person. I have another camera where I would create 2 masks, 1 to ignore person and another to ignore bushes that are detected as animals.

To enable or disable the Image masks you would either use json or MQTT. The image masks would be enabled or disabled depending on day or night and home/away. They would also be enabled with the active time settings for those who cannot activate via MQTT of a Web command.

By eliminating some of the redundant settings for the masks this might simplify the logic for what objects to log and trigger. If an object is found in an area that is unmasked whether Image or Dynamic you would refer to the rules in the Relevant Objects and Actions. If an object is in a masked area and Ignore mask is false you would not trigger for that object. You would apply the same logic above to all masks until you found the  relevant object in a masked area and ignore mask was false.

I hope this is helpful.

Thank you so much for such a great program. I am glad to help anyway I can.

**Comment by Tinbum1** [comment]
That sound good, but I would leave enable, trigger, and the threshold settings settings in.  For example different thresholds are useful for different times of day. I set my night time ones lower as detection is not so good.

**Comment by rtman238** [comment]
@Tinbum1 I agree that the enable per object should be left in the masks. I could see that when an object is added to the list for the mask it comes in disabled. If you want the object ignored by the mask you would then enable it. I agree that trigger and thresholds are useful but I would have those only in the relevant objects section. Setting different thresholds based on a schedule or triggering objects based on a schedule still could be accomplished under relevant objects. By having these settings duplicated in several areas I suspect that there will be users who can't get objects to trigger or fire alerts because they have have more restrictive settings on the mask section. For example if I have the min threshold for a person set at 70% under relevant objects and I have the min threshold set at 75% under the Dynamic mask and DeepStack has identified the person with a confidence of 72% that is not in a masked area, will AiTool trigger because the of the settings in relevant objects or will it be overridden because of the 75% threshold in the Dynamic mask and not trigger?

**Comment by Tinbum1** [comment]
It all does get pretty complicated- I've been caught out as well at times. :)

**Comment by VorlonCD** [comment]
The main Relevant objects for the camera is the "gatekeeper".   Everything has to get past that first.   Then you can further refine in Dynamic mask objects, telegram objects, etc.   Is there a better way of handling this?

**Comment by Tinbum1** [comment]
To me the more options the better so it works for everyone however diverse the application. At the same time though it has to be fail safe for those that want something simple that simply works. The defaults all seem to work well and also give that flexibility. Perhaps an option of a simple and an advanced mode button? Sorry!!

**Comment by rtman238** [comment]
I haven't put much thought into this but you could pass the image through the masks, then through relevant objects and then to the Actions. Otherwise you it would go through Relevant Objects to Masks and then branch off to Actions with the other branch going back to Relevant Objects.

Here are a few changes I would make.

•	Trigger and Thresholds should only be managed under Relevant Objects and Actions. I can see where you would want stricter thresholds for receiving a text or email. 
•	Ignore mask should be removed from off of the Relevant Object and Actions. This would be necessary if you apply separate mask settings for Image and Dynamic.
•	Trigger and Thresholds should be removed from the masks. The masks should be used to include or ignore objects that DeepStack detects. I do not see a benefit to manage the trigger and threshold under the masks.
•	Ignore mask should be left on each mask configuration page with separate settings for Dynamic and Image Masks. Work toward multiple Image Masks enabled/disabled remotely.
•	ActiveTimeRange should be as it is now for Relevant Objects, Actions, and Masks.

**Comment by VorlonCD** [comment]
A few minor changes:

- Feature: In Relevant objects, you can now independently control if you ignore Image or Dynamic masks.
- Anything other than the main/default Relevant object list will have its objects min/max threshold and ignore mask settings restricted by the same object found in the main camera list (the gatekeeper).  Also Ignore image mask and dynamic mask will be grayed out if it is not the main cameras mask

[AITool-VorlonCD-v2.0.1021.zip](https://github.com/VorlonCD/bi-aidetection/files/6216062/AITool-VorlonCD-v2.0.1021.zip)

**Comment by rtman238** [comment]
I found an issue where the Dynamic mask settings are displayed differently between cameras. Is this expected?

![image](https://user-images.githubusercontent.com/79340363/112738258-49d71780-8f2f-11eb-8bb2-695175151b48.png)

![image](https://user-images.githubusercontent.com/79340363/112738266-65dab900-8f2f-11eb-905a-d6fab5d802d5.png)

The NW camera currently has 2 Dynamic masks and I did adjust the Image mask.

**Comment by rtman238** [comment]
The program may be handling the masks correctly but that it inconsistent that the ignore image mask settings a different for the main camera and the Dynamic mask.

![image](https://user-images.githubusercontent.com/79340363/112738755-da175b80-8f33-11eb-8bb2-795543499ad1.png)

![image](https://user-images.githubusercontent.com/79340363/112738768-f9ae8400-8f33-11eb-9fea-c653eda13db4.png)

**Comment by VorlonCD** [comment]
this should be a little more consistent, and those columns are grayed out when you dont have the CAMNAME\Default camera select since it doesnt make sense (It only passes the mask test in CAMNAME\Default)
[AITool-VorlonCD-v2.0.1032.zip](https://github.com/VorlonCD/bi-aidetection/files/6218150/AITool-VorlonCD-v2.0.1032.zip)

**Comment by rtman238** [comment]
This looks really good. Thanks for your hard work!
