### ISSUE TITLE
Object Priority Not Changing

### ISSUE THREAD

**Issue by rtman238** [VorlonCD/bi-aidetection#215]
With v2.0.988 the object priority in the masks and the default does not change as the object is moved up or down in the list. If you sort the objects by priority they will no longer move up and down in the list.

**Comment by VorlonCD** [comment]
Fixed:
[AITool-VorlonCD-v2.0.1014.zip](https://github.com/VorlonCD/bi-aidetection/files/6207947/AITool-VorlonCD-v2.0.1014.zip)

**Comment by rtman238** [comment]
Thanks for the quick reply.
