### ISSUE TITLE
Get an error connecting to blue iris..

### ISSUE THREAD

**Issue by malosaa** [VorlonCD/bi-aidetection#217]
I can access it locally without an pascode or username.. 
it is hoster on my other pc and no restrictions.. 

any idea's ? 

 `  Give the current user (DESKTOP-S7AI4BS\Home Security System) access to '192.168.1.8': Attempted to perform an unauthorized operation. [UnauthorizedAccessException] (In BlueIris.RefreshBIInfoAsync:121 > BlueIris<>c__DisplayClass15_0<RefreshBIInfoAsync>b__0:121 > Win32.RegistryKey.OpenRemoteBaseKey(RegistryHive hKey, String machineName, RegistryView view) > Win32.RegistryKey.Win32ErrorStatic(Int32 errorCode, String str))`

**Comment by VorlonCD** [comment]
if you cannot browse to \\192.168.1.8\SomeShareName then AITOOL would not be able to remotely access the blue iris registry settings either.    You should be able to add a "Home Security System" user on the BlueIris machine (windows users not BI users) and give them admin rights.  Or maybe only read-only is all that is needed.   You also have to have the "Remote Registry Service" enabled/running on the BI machine.

**Comment by malosaa** [comment]
Hi @VorlonCD 

thanks for the reply.
Actually it works normal now, its just that error on the start-up.
I think it is because i don't use it on my same pc.
Yes, i can access \192.168.1.8\SomeShareName  normal.

Well i ignore that error and the tool works just fine. 

We can close this issue as it works normal
