### ISSUE TITLE
Ability to save Deepstack's annotated images to folder

### ISSUE THREAD

**Issue by aesterling** [VorlonCD/bi-aidetection#22]
Similar to @Bisquit4407's request, please add the ability to export/save the marked-up alert image from Deepstack and save it out to a folder on the file system. We're interested in the image that includes the boxes around the detected object and text "Person (87%)." The option to "use the original filename" as well as "append text ____ to the original filename" would be great.

The BI dev said he supports using this image as the alert image for BI and push notifications. Thanks!

**Comment by VorlonCD** [comment]
Added ability to customize filename - no merging of markups yet
https://github.com/VorlonCD/bi-aidetection/releases

**Comment by VorlonCD** [comment]
@aesterling  - This version lets you merge the detection's into the image before sending/copying.  And lets you customize the filename.  Let me know how works.
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5235773/AITOOL-VORLONCD.zip)

**Comment by aesterling** [comment]
@VorlonCD this is awesome, thank you! The feature is a great addition.

However, the merged jpg that's saved appears to have heavier image compression when compared to the image displayed in Gentle Pumpkin's original AI Tool interface. Please view the below images full size for comparison. (It's especially noticeable around the red box, text, and color.) Is it possible to save a less-compressed version?

Screenshot from GP's AI Tool interface:
![GP_AITool_Interface_Screenshot](https://user-images.githubusercontent.com/18314707/93490279-e60fca00-f8cd-11ea-835e-322a5621aa42.png)

JPEG saved from your release in the comment above:
![Driveway_AI 20200917_091712227](https://user-images.githubusercontent.com/18314707/93489386-15720700-f8cd-11ea-9e7b-67f9c4bac295.jpg)

**Comment by VorlonCD** [comment]
@aesterling  - When you merge the detection annotations into a new jpeg file and re-compress it, it is unlikely to have the same detail on the objects compared to just overlaying them on screen like the UI does.   Jpeg uses a 'lossy' compression which does not preserve 100% of the image detail when resaving.   Everytime you resave the quality gets a little worse depending on the jpeg compression level setting.   PNG on the other hand is "lossless" compression, so each save results in the same quality, just a much larger image file.

You can experiment with increasing the alpha in the settings JSON file, it may help:  **RectIrrelevantColorAlpha** and **RectRelevantColorAlpha**.   Try setting closer to 255 which is completely solid.   0 would be invisible.

My next update later today will have a new Camera.**Action_image_merge_jpegquality** setting that you can set directly in the JSON file.   It defaults to 90 in your version and 80 in the new version to make the file smaller for sending/copying.  I think BI defaults to 50, but I always set mine to 90.   100 being least compressed/best quality.

**Comment by aesterling** [comment]
@VorlonCD Understood, thank you. Changing the RectRelevantColorAlpha to 255 in the JSON helped a lot with visibility. I'm looking forward to the jpeg quality setting in your next release :)

I'd like the annotation text is as legible as possible, but recompression of the camera image is understandable. 

Thank you again for all the work on this. We all appreciate your time!

**Comment by VorlonCD** [comment]
The latest with the ability to change the jpeg compression is up there

**Comment by aesterling** [comment]
Downloaded, installed, and working great!

In the JSON file, I set the jpegquality to 100 and the RectRelevantColorAlpha to 255. I also changed the RectRelevantColor to yellow instead of red, which appears a bit more forgiving after JPEG compression.

Thanks again for the work!

**Comment by MYeager1967** [comment]
Any chance this could be made to save the file twice? Once with the given filename and once with something like cameraname-latest?
