### ISSUE TITLE
Object-specific masks

### ISSUE THREAD

**Issue by aesterling** [VorlonCD/bi-aidetection#220]
I want to mask out certain areas of the image for specific objects only.

In my example screenshot below you can see it incorrectly identifies my deck as a truck. I still want to find trucks in front of the garage door, but not in front of the deck. I can't mask out the deck because I want to identify humans and dogs in that area. Confidence limit isn't an option because AI Tool will often identify an actual truck at the garage but with very low confidence, so I want to keep that low.

Could a solution be multiple colors or layers in the "Draw Mask" window, with the ability to select which object types honor each mask color? @classObject Or does a different approach make more sense?

Is this already achievable in another way? Please let me know. Thanks!

![Screen Shot 2021-03-29 at 10 28 04 AM](https://user-images.githubusercontent.com/18314707/112860733-b2321000-9079-11eb-9bb2-4d26cb95400e.png)

**Comment by Tinbum1** [comment]
You could increase the threshold for truck above 25% min.

**Comment by aesterling** [comment]
Thanks, @Tinbum1 :) Unfortunately, it often identifies actual trucks coming in/out of the garage with pretty low confidence, too, so I'd like to keep the threshold low to not miss actual trucks. I tried that initially but missed a number of events, so that's what led me to post this. Thank you, though!

**Comment by Tinbum1** [comment]
Are you using the latest version of Deepstack? I find my confidences are normally in the range 50 to 90%. If i recall correctly with older versions they did seem to be lower and in a smaller range. (Not saying you ideas are bad, by the way).

**Comment by Tinbum1** [comment]
PS With the latest version you should be able to ignore the mask for people.

**Comment by VorlonCD** [comment]
Right, put an image mask where your "Truck" object is, then set PERSON to "Ignore image mask":
https://github.com/VorlonCD/bi-aidetection/files/6218150/AITool-VorlonCD-v2.0.1032.zip

**Comment by aesterling** [comment]
Thank you both. 

I installed v2.0.1032 but it crashes when I try to maximize it from the system tray. Then I installed v2.0.1025 but didn't see the option to "Ignore image mask" plus kept getting a number of "unhandled exception" errors. 

Is "Ignore image mask" only available in v2.0.1032 and newer? Would love to try it out.

I'll check for Deepstack updates tonight. Thanks!

**Comment by VorlonCD** [comment]
what are the crashes in 1032?   That version splits "Ignore mask" to "Ignore Image mask" and "Ignore dynamic mask".

Try this for 1032:

1) Re-download
2) Right-click > Unblock the ZIP file (**before extracting!!!**)
3) Backup existing AITOOL folder, and delete all the DLL/EXE files from the main folder (leave _SETTINGS)
4) Copy the new files in place

Otherwise I would need logs, screenshots, etc for the crashing
