### ISSUE TITLE
AI Tool crashes while adding a camera. Also relevant objects button returning error on click. Not working :(

### ISSUE THREAD

**Issue by govindsnair** [VorlonCD/bi-aidetection#225]
![Error 1](https://user-images.githubusercontent.com/59764764/113468468-0e26db00-9464-11eb-9dd2-c4f2c2225e5e.JPG)

AI Tool crashes while adding a camera. Also relevant objects button returning error on click. Not working :(

**Comment by pocketgeek** [comment]
This has something to do with "bool restrict = !this.cam.IsNull() &&
this.cam.DefaultTriggeringObjects.TypeName != this.TypeName;" on line 239
of ClsRelevantObjectManager.cs, but I'm not so good at reading c#.  I
changed it to "bool restrict = false;" and now it'll let me add cameras
without error with the caveat that the defaults aren't applied.  Easy to
deal with though.

--
Curtis Edge

**Comment by govindsnair** [comment]
Perfect. Thanks buddy. 👍

**Comment by VorlonCD** [comment]
This fixes:
[AITool-VorlonCD-v2.0.1036.zip](https://github.com/VorlonCD/bi-aidetection/files/6252956/AITool-VorlonCD-v2.0.1036.zip)

**Comment by govindsnair** [comment]
Thanks dude...!
