### ISSUE TITLE
Control BlueIris via MQTT

### ISSUE THREAD

**Issue by edalquist** [VorlonCD/bi-aidetection#23]
A great next step to Issue#8 would be using MQTT to trigger BlueIris instead of HTTP URLs. That would also let use avoid having to allow basic HTTP auth on the webserver.

https://wiki.instar.com/Software/Windows/Blue_Iris_v5/INSTAR_MQTT/#controlling-blueiris-through-mqtt details the MQTT commands.

**Comment by VorlonCD** [comment]
You should be able to do this now by erasing the trigger URL and enabling mqtt action with connection to blueiris server.

**Comment by edalquist** [comment]
ack, I'll give that a try. It looks like I'd only be able to publish to a single topic though so doing trigger + flag (needs to publish to two different topics) wouldn't be possible yet right?

**Comment by VorlonCD** [comment]
Havent implemented multiple mqtt servers yet (if needed??) but if you put multiple topics and payloads on each text box, it will trigger all of them.   Like "topic1 | topic2", "payload1 | payload2"
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5250531/AITOOL-VORLONCD.zip)

**Comment by edalquist** [comment]
Awesome, I'll give that a try today. I doubt (famous last words) multiple mqtt server support is needed as the whole point of a local server is a single pubsub router for all your things.

**Comment by VorlonCD** [comment]
Ok, so when you control BI you dont have to set BI as a server in settings?   Or you DO set to BI and it forwards any messages it doesnt handle?   I dont think I'm as MQTT literate as I should be.

**Comment by edalquist** [comment]
BI is a MQTT client, just like AITool is now. You point both at a MQTT broker (server) which handles the pubsub aspects of the message queue system. In my case I'm using Mosquito MQTT with Home Assistant. Both BI and AITool connect to it and can use it as a way to communicate between each other. Additionally Home Assistant can watch the MQTT topics, react to them and publish to them to control things.

**Comment by VorlonCD** [comment]
Is this working ok now?  Or does a separate option really need to be configured to trigger BI via mqtt or url?

**Comment by edalquist** [comment]
Just verified it works! I'll see if I can do a writeup on how to setup AITool and use MQTT to tigger BI so none of the HTTP/Auth stuff is needed.

**Comment by youzer-name** [comment]
I'm trying to do the same thing and when I test the MQTT with the pipe separated topics it ignores the pipe and runs the whole topic together. Using a direct copy & paste of what edalquist posted above I see an MQTT message with a topic of "ai/cameraname/moiton | BlueIris/admin" coming through under my subscription to "ai/#" in MQTT.fx No message comes through under the BlueIris subscription. Am I missing something about how to enter the multiple topics and payloads? I'm using a space, a pipe, and a space between each one (" | ").

**Comment by edalquist** [comment]
What version (from overview tab) are you running?

**Comment by youzer-name** [comment]
I was running the latest release, but I just tested it in a pre-release 1.67.8.24326 9/25/2020 1:30:53 PM and the test button works with multiple MQTT topics.

**Comment by MYeager1967** [comment]
Does the BlueIris/admin topic need to be cancelled?

**Comment by jdom** [comment]
This is great. @edalquist, is there a write up for setup instructions to integrate via MQT ? I believe at this time gentlepumpkin's post in ipcamtalk is really outdated. We should probably have docs directly in markdown in this repo, so we keep them up to date (as possible) with the current state of things.

**Comment by jdom** [comment]
A minute after going back to the readme, I noticed https://github.com/VorlonCD/bi-aidetection/blob/master/mqtt.md just beside it, so sorry about the question, I'll look into those instructions now. Thanks, and great work, everyone

**Comment by ipeterski** [comment]
Hey. Is there a setting to tell AI Tools /*when to submit a cancel request, or how is it told to send the cancel... query is the resset from blue iris go to ai tools? no point in going bi > ai tools > mqtt > blue iris.. i can just have the close mqtt directly to the master.

(i have cloned cameras,.. despite weeks of efforts.. i cannot seem to get AI tools and bi to work off 1 camera and NOT see all the false alerts in my screen.. ) 

anyways.. ywah. my comment was merly, what triggers the "cancel" in ai tools.. the ai or bi?

Thanks

**Comment by ipeterski** [comment]
kind of a follow up,

hi, so i was watching the mqtt for the trigger and cancels.. my cameras are not getting a cancel request.. so i watched as a car drove , ai tools send a trigger command, yet it never sent the cancel,,, the cancel fields are red text, and not black, not sure if that means anything.. i will have a look in the config to see anything, but not sure how the cancel fields are activated... and again im refering to the mqtt cancel fields.. the url trigger and cancel work fine. but i would like to utilize the mqtt..

thanks in advanced.
--Stickers

**Comment by edalquist** [comment]
I have cancel setup but AITool only cancels if it gets an image with no match.

My setup looks like:
* CameraFoo (onvif) - subscribed to on-camera motion detection (I do this to save server CPU) when triggered it triggers the (ai) camera
* CameraFoo (ai) - Disabled unless triggered, uses BI motion detection, saves a snapshot every 3s when triggered.
* CameraFoo (live) - 24/7 recording, trigger resets after 30s of no new triggers.

AI Tool watches the (ai) camera snapshot folder and on a hit it triggers the (live) camera via MQTT. Each new hit in AI Tool triggers the camera again keeping the alert going until either a miss in AI Tool **or** the 30s timeout passes.

**Comment by VorlonCD** [comment]
@edalquist - Does this do the trick?

Prior to this update, the only time a trigger cancel would be called is if **another** image is analyzed and found to have nothing found.   

NOW, after each triggered event, if you have any cancel URL's or MQTT configured, a cancel event is 'queued' and a cancel will be sent in 30 seconds (Controlled via 'ActionCancelSeconds' in the settings JSON file)

If there are any new triggered events in the mean time, the cancel event time for the camera will be updated/extended.

[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5740194/AITOOL-VORLONCD.zip)

**Comment by edalquist** [comment]
I was fine with the previous behavior where BlueIris just reset the trigger after 30s. This is a handy option to have though.
