### ISSUE TITLE
Object Ignores Dynamic Mask Checkbox Gone in 2.0.1077

### ISSUE THREAD

**Issue by rtman238** [VorlonCD/bi-aidetection#231]
I see that you can set the object to ignore the Dynamic Mask above so I do not know if you intentionally left the Ignore Dynamic Mask checkbox off the form at the bottom of Relevant Objects for the Default settings of a camera.

![image](https://user-images.githubusercontent.com/79340363/114302694-b99ce480-9a8f-11eb-8234-9c34e74b8f15.png)

**Comment by VorlonCD** [comment]
You dont see a scrollbar on the right?     You can take a hold of the splitter here and move it up to display everything:

![image](https://user-images.githubusercontent.com/7512113/114314708-c76f5b80-9ac9-11eb-9769-18125684c645.png)

**Comment by rtman238** [comment]
Sorry about that. I was used to not seeing the scrollbar in the other
versions and I did not look for it.
