### ISSUE TITLE
Bug:  "BlueIris Server Name" in settings tab does not work if dual NIC

### ISSUE THREAD

**Issue by wudwork** [VorlonCD/bi-aidetection#232]
In Settings tab:  BI Server Name complains if its not loopback (127.0.0.1). Under "Actions" in a camera, the variable for BlueIrisServer gets set to the wrong NIC and I get errors. To fix, I have to put the correct NIC IP in place of BlueirisServer in Action strings for each camera.

Fix: Let me write my own URL for "Blue Iris Server Name" in settings tab, don't insist its loopback.

Is this do-able ?

**Comment by VorlonCD** [comment]
You can - use [BlueIrisServerIP] rather than [BlueIrisURL].

[BlueIrisURL] is obtained directly from the BI registry settings, so IT may be wrong...

I bet BI is pointing to the wrong adapter IP in Settings > Web Server.   Mine is constantly being reset!   In fact I just noticed it was wrong now.

**Comment by wudwork** [comment]
Thank you. I could not figure how it got that IP/port was obtained. I checked my BI web server IP and it was indeed the incorrect NIC.  Please close this issue, its resolved.

**Comment by wudwork** [comment]
If the [BlueIrisURL] variable has incorrect value, check BlueIris Settings > Web Server (internal) to see where AItools got it from. If you change it in BI, restart BI (service and/or program) and restart AItools.

**Comment by VorlonCD** [comment]
This version shows you what URL BI is set to and warns if AITOOL ip is not the same as BI ip.
https://github.com/VorlonCD/bi-aidetection/tree/master/src/UI/Installer
