### ISSUE TITLE
Minimize window removes AiTools from screen

### ISSUE THREAD

**Issue by wudwork** [VorlonCD/bi-aidetection#233]
When I click on AiTools icon to MINIMIZE the app window, it seems to remove it from view (not just minimize). I cannot figure out how to bring this back to front so I can work within it. I do see it running in Task Manager and found I must stop it there before I can launch it again and get control.  Last night I minimized it and went to bed, today I see very sporadic history in it after doing above process to start new copy.

Request:  Test the minimize app icon and confirm its not acting right.

**Comment by JuraasicCoasterNerd** [comment]
It minimizes to the taskbar by default. You may need to click the arrow next to your clock to see it. 

There is a setting to change this behavior in recent versions. Look for it in some of the more recent posts.
