### ISSUE TITLE
Escaped character in [Detail] variable

### ISSUE THREAD

**Issue by whyfseeguy** [VorlonCD/bi-aidetection#235]
Is it possible to add something like [DetailEscaped] in AITool? I am using Sighthound for additional face,person detection. The additional results from Sighthound are stored in the [Detail] variable. But I am also sending that data using an http request to a TTS program, an Escaped version is required to make that work.

Thanks.

**Comment by VorlonCD** [comment]
Done.
https://github.com/VorlonCD/bi-aidetection/tree/master/src/UI/Installer

- Added [DetailEscaped] variable
- Added UPDATES button on settings tab to check for updates on github.  It will show you the RELEASE NOTES and let you click the newer version to install it.
- Added ability to migrate settings from last used folder if installed to a different location

**Comment by whyfseeguy** [comment]
Just to confirm that the [DetailEscaped] variable is working in the latest version. Thank you.

Just to note that it is not shown in the variables list screen, it would be nice if it can be added like the other "escaped" variables on the list.
