### ISSUE TITLE
Unable to use AWS Rekognition

### ISSUE THREAD

**Issue by whyfseeguy** [VorlonCD/bi-aidetection#236]
I have setup an AWS account and created an IAM user with Rekognition full access. I download the csv file and renamed it rootkey.csv and placed the file in the _settings folder. When I add the AWS rekognition server to the server list, I got a popup error complaining that I dont have a rootkey.csv file!

Any ides what may be causing this?

The log does not have more info other than what was in the error pop-up.

Thanks.

**Comment by VorlonCD** [comment]
Make sure File Explorer is not hiding file extensions.   You could have **rootkey.csv.txt** in there for example.
Restarted AITOOL?
Does it work regardless of the error?

**Comment by whyfseeguy** [comment]
File extension is OK. I always have show full file name in file explorer. I click the Test button and I got this error:

DetectObjects	  The remote server returned an  (400) Bad Request. [HttpErrorResponseException] (In AITOOL.GetDetectionsFromAIServer:2697 > RuntimeInvokeAsync > RuntimeInvokeAsync:58 > RuntimeInvokeAsync > RuntimeInvokeAsync > RuntimeInvokeAsync:146 > RuntimeInvokeAsync > RuntimeInvokeAsync:98 > RuntimeInvokeAsync:79 > RuntimeInvokeAsync > RuntimeInvokeAsync > RuntimeInvokeAsync:104 > RuntimeProcessExceptionAsync:246 > RuntimeHandleAsync:46 > RuntimeHandleExceptionAsync:92 > Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream):162)	Error	AITOOLS.EXE	Amazon_Objects:us-east-2	default	default.URLTEST.2021-04-25_14-18-11-507.jpg

I also restarted AITool. It still wont accept the rootkey.csv.

**Comment by VorlonCD** [comment]
I guess amazon changed something recently, or you downloaded rootkey.csv from the wrong location?
My file looks like this:

```
AWSAccessKeyId=XXXXXXXXXXXXXXXXXXX
AWSSecretKey=XXXXXXXXXXXXXXXX+XXXXXXXX/XXXXXXXX
```
I guess you could extract those two settings from the file you have and create a new one that looks like mine.

**Comment by VorlonCD** [comment]
The latest should support the new csv file format, but I didnt test it yet.
https://github.com/VorlonCD/bi-aidetection/tree/master/src/UI/Installer

**Comment by whyfseeguy** [comment]
> I guess amazon changed something recently, or you downloaded rootkey.csv from the wrong location?
> My file looks like this:
> 
> ```
> AWSAccessKeyId=XXXXXXXXXXXXXXXXXXX
> AWSSecretKey=XXXXXXXXXXXXXXXX+XXXXXXXX/XXXXXXXX
> ```
> 
> I guess you could extract those two settings from the file you have and create a new one that looks like mine.

Just tried your suggestion of modifying the rootkey.csv file with build 1127. It worked and even faster than deepstack. Albeit I have a 1GB up/down Fibre. 

Thanks.
