### ISSUE TITLE
Error: Could not connect to Blue Iris

### ISSUE THREAD

**Issue by petexa** [VorlonCD/bi-aidetection#237]
I am getting the following error, im on version 2.0.1127.7784
- BlueIris Settings > Web Server > Local IP address is set to a different IP: AITOOL=127.0.0.0, BI=192.168.1.3

So I change the BlueIris Server name and I am getting the following error.
- Got error while reading BlueIris registry: Object reference not set to an instance of an object. [NullReferenceException] (In BlueIris.RefreshBIInfoAsync:140 > BlueIrisUpdateRemotePathAsync:72 > GlobalGetBestRemotePathAsync:614)

**Comment by VorlonCD** [comment]
This should fix:
https://github.com/VorlonCD/bi-aidetection/tree/master/src/UI/Installer

**Comment by petexa** [comment]
All fixed, thank you 👍
