### ISSUE TITLE
Oodles of errors w/ newest release 

### ISSUE THREAD

**Issue by balucanb** [VorlonCD/bi-aidetection#238]
Just updated the files and it went bonkers. Deepstack stuff, to many pictictures so it is timing out, Deepstack not starting correctly etc.  I re booted computer, but no help. I went into the DS tab and re started but still ain't acting Straight. You are well aware I'm to dense to read and understand the logs so sorry 'bout that! :) .

[stderr.txt](https://github.com/VorlonCD/bi-aidetection/files/6372809/stderr.txt)
[stdout.txt](https://github.com/VorlonCD/bi-aidetection/files/6372812/stdout.txt)

Date | Func | Detail | Level | Source | AIServer | Camera | Image | Idx | Depth | Color | ThreadID | FromFile | Filename
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
4/25/2021 14:40:10 | GetDeepStackRun | Deepstack partially running. Only 0 out of 2 copies of python.exe are running. | Info | AITOOLS.EXE | None | ReolinkDWsd | None | 138 | 2 |   | 1 | False | AITool.[2021-04-25].log
4/25/2021 14:40:10 | GetDeepStackRun | Deepstack partially running. Only 1 out of 2 copies of python.exe are running. | Info | AITOOLS.EXE | None | Frontdoorsd | None | 127 | 2 |   | 1 | False | AITool.[2021-04-25].log
4/25/2021 14:40:07 | Shell_Load | APP START complete.  Initialized in 5.0 seconds (4967ms) | Info | AITOOLS.EXE | None | None | None | 107 | 0 | yellow | 1 | False | AITool.[2021-04-25].log
4/25/2021 14:40:07 | LoadSettingsTab | BlueIris Settings > Web Server > Local IP address is set to a different IP: AITOOL=127.0.0.1, BI=172.28.32.1 | Warn | AITOOLS.EXE | None | None | None | 105 | 0 |   | 1 | False | AITool.[2021-04-25].log
4/25/2021 14:40:06 | StartDeepstack | Started in 2351ms | Info | AITOOLS.EXE | None | None | None | 88 | 2 |   | 8 | False | AITool.[2021-04-25].log
4/25/2021 14:40:04 | StartDeepstack | Starting 1 of 1: C:\DeepStack\server\DeepStack.exe --VISION-DETECTION True --MODE Medium --PORT 81... | Info | AITOOLS.EXE | None | None | None | 71 | 2 |   | 8 | False | AITool.[2021-04-25].log
4/25/2021 14:40:04 | StartDeepstack | Starting DeepStack... | Info | AITOOLS.EXE | None | None | None | 70 | 2 |   | 8 | False | AITool.[2021-04-25].log
4/25/2021 14:40:03 | StopDeepstack | Stopping Deepstack... | Info | AITOOLS.EXE | None | None | None | 61 | 3 |   | 8 | False | AITool.[2021-04-25].log
4/25/2021 14:40:03 | InitializeBackend | Starting AITool Version 2.0.1127.7784 built on 4/24/2021 17:37:10 | Info | AITOOLS.EXE | None | None | None | 33 | 0 |   | 4 | False | AITool.[2021-04-25].log

     Skipping image because queue (101) is greater than '100'. (Adjust 'MaxImageQueueSize' in .JSON file if needed): D:\AIinput\ReolinkLSYsd.20210425_140400288.jpg (4-500 times)

   Deepstack returned 'failed to process request before timeout' - http status code 'InternalServerError' (500) in 60002ms: Internal Server Error.

 BlueIris Settings > Web Server > Local IP address is set to a different IP: AITOOL=127.0.0.1, BI=172.28.32.1  (I changed nothing?)

**Comment by VorlonCD** [comment]
This should fix the "Local IP is different" warning:
https://github.com/VorlonCD/bi-aidetection/tree/master/src/UI/Installer

For deepstack, not sure.   Try STOP, then RESET button on deepstack tab.

**Comment by whyfseeguy** [comment]
With the Windows version of Deepstack, I found that starting and stopping Deepstack in multiple succession will cause python and the redis-server to hang. Only way to clear is to reboot.

The official word from Python.org: Especially on Windows, this is good only for learning. I didn’t find it very stable, and even installing basic things like Virtualenv gave me problems.

No issue with the docker version.

**Comment by balucanb** [comment]
Thanks @VorlonCD  I'll give it a try.

**Comment by VorlonCD** [comment]
Also remember if you reduce the number of instances/ports listed on the deepstack tab, you have to manually delete or disable those extra servers in the AI server list otherwise they will be causing constant errors.

I find that more than one deepstack instance is not stable.

**Comment by balucanb** [comment]
Correct. I only run 1. Let the new version run all night, just got up and I only 2 errors, will need to check when they occurred but overall it seems to be OK for now, normally more traffic and such during the day so we will se.

**Comment by balucanb** [comment]
ok I think were good- CLOSED
