### ISSUE TITLE
Feature request: Dynamic Masking for specific objects.

### ISSUE THREAD

**Issue by petermai6655** [VorlonCD/bi-aidetection#24]
Would love to see dynamic masking only for specific objects. For example, in my driveway, when there is a car parked, AITool will create a dynamic mask in that area for the car after a few detections, but when a person is detected in the same area, the tool will trigger.

**Comment by VorlonCD** [comment]
Ok, see how this works:
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5234889/AITOOL-VORLONCD.zip)

**Comment by petermai6655** [comment]
Tested it, and it works.
