### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by Jensilein** [VorlonCD/bi-aidetection#247]
Hello, I was using the pre-compiled version of AITool so far that is available by .zip file. As the latest version is provided by .exe file I wanted to ask how I can update my current installation. What do I have to do in order to keep my current settings? Is there any hint or explanation on that available? Thanks for your support.

**Comment by balqosz** [comment]
Hello, the first install you should manual tell the installer which folder is your current AI Tool. Then next updates will take into account this location. Settings are preserved (but you can make a copy of that folder before installing, just in case)

Greetings
