### ISSUE TITLE
Latest Image not appearing automatically on history for a selected camera.

### ISSUE THREAD

**Issue by theheadturner** [VorlonCD/bi-aidetection#249]
The history is not getting refreshed for a particular camera if we select.

Even after further detection and alerts, the latest images are not automatically appearing in the history , we have to visit some other tab and come back or may have to re-select the camera to get it refreshed.

@VorlonCD If you kindly sort this issue.

**Comment by VorlonCD** [comment]
History tab > History settings > enable Automatically refresh (which should be the default).   Optionally enable the "Follow" option, but then when you are reviewing the list it will keep jumping to the latest.

If still not working, try latest:
https://github.com/VorlonCD/bi-aidetection/tree/master/src/UI/Installer

**Comment by theheadturner** [comment]
> History tab > History settings > enable Automatically refresh (which should be the default). Optionally enable the "Follow" option, but then when you are reviewing the list it will keep jumping to the latest.
> 
> If still not working, try latest:
> https://github.com/VorlonCD/bi-aidetection/tree/master/src/UI/Installer


I tried it but was not working.

Is the source files updated for the latest version of installer ??

**Comment by VorlonCD** [comment]
I just tested, still seems to be working as expected.    I set history tab to show a specific camera, set History filter to "Only Relevant" (But it works without also), and made sure History settings > Auto refresh and Follow were enabled.    New history items are selected and shown.

The overview tab near the bottom should mention version 2.0.1153 if you have the latest version.

Perhaps I'm misunderstanding your issue?

The source code is on the CODE tab at the top of the screen next to this ISSUES tab.   Then you can create a fork of the project, make changes and submit a pull request for me to merge in.

**Comment by theheadturner** [comment]
You correctly identified my issue. I was using Version 1.67 and did some
minor GUI changes.

I am yet to check the Version 2.0. But rather than installer, I will
require the code for doing same GUI changes which I did for 1.67 to suit my
requirements.

If you can help me with the latest code please of version 2.0.

Regards

**Comment by VorlonCD** [comment]
No work is being done on 1.67 and there are MANY changes for 2.0.   I would test the installer first to see if you still need to make the GUI changes since many things where fixed.

But all the code is over on the CODE tab, then CODE button > Download zip

**Comment by theheadturner** [comment]
Thank you so much.

I was about to suggest to you that can't we think of adding a count of
objects appearing in an image.

It will give a summary of objects appearing for an end user.

Also some guidance in integrating custom deepstack models with the AI Tool.

Regards

**Comment by VorlonCD** [comment]
In the latest releases the History tab > "**Prediction Details**" screen lets you see all the individual predictions along with relevancy, size, etc.   Doesnt actually give a count, but lets you easily see all of them in a single list.

And the new version lets you run deepstack windows from within AITOOL on the Deepstack tab.  It supports custom model paths, faces, etc.      

A number of posts here go over configuration:
https://ipcamtalk.com/threads/tool-tutorial-free-ai-person-detection-for-blue-iris.37330/
And here:
https://github.com/VorlonCD/bi-aidetection/issues?q=is%3Aissue
