### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by opa-rudi** [VorlonCD/bi-aidetection#25]
What a super duper tool! I love it so much!!!!!!!!!!!!!

here are some features that I missed:

- defining a specific path/file for masking images
- defining a image/log rotation timer for the processed images and logfile
- processing the url-parameter "manrec" for starting/stopping manual recording via url in BI (only record when AI triggers)

greetings and thanks for your awesome work!!!

**Comment by VorlonCD** [comment]
The aitool.settings.json file has a 'MaxLogFileAgeDays' setting that defaults to 14, and will delete any logs older.   And with the latest release you can also control the max log size before it creates a new one with 'MaxLogFileSize'.  (Its in bytes, and defaults to 5mb)

Can you go into a bit more detail about the other two feature requests?

**Comment by opa-rudi** [comment]
It would be nice if AITool deletes processed images instantly or after a specific time.

**Comment by VorlonCD** [comment]
If you mean the images in a normal 'watched' folder, you can configure BlueIris to delete them after a set amount of time in its settings.

If you mean the AITOOL > Camera settings > Actions > Image copy folder, the next release will have a setting in aitool.setttings.json called 'Action_network_folder_purge_older_than_days' which defaults to 30 days.

I would still need more details on MANREC.

The next version will be a little more flexible with cameraname.bmp mask images.   If it cannot be found in \Cameras\ subfolder it will default to where ever the .JSON config file is.

**Comment by MYeager1967** [comment]
Is it, or would it be possible, to retrigger the camera each time that an object is detected? In other words, I stand perfectly still so that the motion detection says I'm not there, however, the AI sees me and continues to trigger the camera...

**Comment by opa-rudi** [comment]
BlueIris does a loop, because if AI tool triggers, then BI gets triggered by URL (sent by AI Tool) and saves a new image and AI tool does its work again, and again until dynamic masking matches or the object leaves the image. Keep in mind that BI mask works the opposite way of AI Tool mask (masked part in BI is active whereas masked part in AI Tool is inactive).
