### ISSUE TITLE
Deepstack v3.4 not supported.  Install version 2020.

### ISSUE THREAD

**Issue by kozoke** [VorlonCD/bi-aidetection#253]
I'm using deepstack running on unraid. AI Trust runs on a separate windows server with Blue Iris.  I'm seeing this error:
      Deepstack v3.4 not supported.  Install version 2020. https://docs.deepstack.cc/windows/index.html
Not sure what it is and now to stop it?  appreciate any thoughts.

On a side note with regard to the wiki, do I just start drafting some guidance/tips there and we all just collectively edit?  How can I contribute what i've learned from the issues/forums?  I don't code but I can write? :-)

**Comment by VorlonCD** [comment]
Try turning off **Auto start checkbox** on the deepstack tab since you are not using the Windows version.  If that doesnt work, simply install the latest Windows version but dont use it.

By all means, edit away in the Wiki!  I think we can port some of the stuff from the first ipcam forum post.

**Comment by kozoke** [comment]
Update: I switched off all of the selections on the windows tab. (auto start was off).  This worked. Thanks!
