### ISSUE TITLE
Issue with HUGE history

### ISSUE THREAD

**Issue by tkffaul** [VorlonCD/bi-aidetection#255]
@VorlonCD 
I'm pumping alot of images through the software and the history is really stacking up and making the whole tool run very slowly. I've turned the 'maxGUILogItems' down to 100 and that hasn't helped at all... I think its the fact that the history items being 107009 and I'm pumping about 12 images a minute thru the tool. How do I tune it to behave again? The history window goes black during updates as I think I have it overloaded. This tool is great and thanks for your hard work!

**Comment by tkffaul** [comment]
I do get this in my Log Window:
    ---- Log window update took 16242ms to load. 10841 added, 10841 removed, 16952 total. Consider lowering the 'MaxGUILogItems' setting in JSON file (Currently 100)

**Comment by tkffaul** [comment]
I found it... 
"maxHistoryAgeDays"
I pulled this down to 3 days and it trimmed my history off. Its much better now! 

After a few minutes I've been getting a few errors...
I am getting some sqllite errors now...
    StackDepth=8, TID=12, TCNT=37: <xxx>.jpg: not an error [SQLiteException] (In SQLiteHistory.InsertHistoryItem(History hist):278 > SQLiteConnection.Insert(Object obj):1707 > SQLiteConnection.Insert(Object obj, String extra, Type objType):1857 > PreparedSqlLiteInsertCommand.ExecuteNonQuery(Object[] source):3571)

**Comment by VorlonCD** [comment]
Those issues were fixed a while ago but never posted a release.   But the latest version is always here:
https://github.com/VorlonCD/bi-aidetection/tree/master/src/UI/Installer

I dont think you need to lower those settings with the latest, but let me know.

**Comment by tkffaul** [comment]
> 
> 
> Those issues were fixed a while ago but never posted a release. But the latest version is always here:
> https://github.com/VorlonCD/bi-aidetection/tree/master/src/UI/Installer
> 
> I dont think you need to lower those settings with the latest, but let me know.

I'm on version 2.0.1185.7836 built on 6/15/21 so I'm up to date...

**Comment by tkffaul** [comment]
So the history only clears out if you close the program... I have mine running all the time its just stacking up history items. Shouldn't this kinda clear out on its own? So I've set for 3 Days worth of history... but it the software runs for 15 Days.... I have 15 days worth of photo history... but if I close it and re-open... it will strip it down to 3 Days...

**Comment by VorlonCD** [comment]
Never had an issue with it slowing down after days of running.

It will delete history items during the session if something in the watched folders are deleted, so you should correctly have BI either deleting or archiving files to a different folder after xx days to keep the AITOOL history clean for a long running session.

And you likely have too many images being created, so maybe cut down the "When triggered each m:ss.s" setting to 4 seconds or less?  Or reduce motion sensitivity?

And if you turn off History settings > Follow, and Auto refresh it will speed things up.

**Comment by VorlonCD** [comment]
Ok, it now cleans the history every 24 hours, controlled in AITOOL.SETTINGS.JSON setting called 'HoursBetweenCleaning'
https://github.com/VorlonCD/bi-aidetection/tree/master/src/UI/Installer

**Comment by tkffaul** [comment]
@VorlonCD The setting 'HoursBetweenCleaning' wont stay in the settings.JSON file. Everytime I add it or try to modify it, as soon as i start the AI tool, it removes the setting.

**Comment by VorlonCD** [comment]
You have to be completely out of AITOOL.EXE before making the change to the JSON file.   After closing, double check in Task Manager > Details tab.

**Comment by tkffaul** [comment]
So I'm running 2.0.1201.7854 from 7/3/21 5:15 and i can reboot the system and put the entry in... open the AI tool and as the tool loads it wipes the entry out of the file. So after I'm all up and running the entry is gone.

**Comment by VorlonCD** [comment]
Sorry, bug.   Fixed in the latest.   The setting is now 'HistoryHoursBetweenCleaning':
https://github.com/VorlonCD/bi-aidetection/tree/master/src/UI/Installer

**Comment by tkffaul** [comment]
Sorry to be a pain... but it works... but now i get a bunch of "When trying to delete database entry, RowsDeleted count was 0 but we expected 1."

**Comment by VorlonCD** [comment]
fyi the latest version from yesterday should fix that

**Comment by tkffaul** [comment]
Sorry Also found this:
       Could not remove from in-memory database: <Name of File>

**Comment by tkffaul** [comment]
So i turned the Hours between cleaning down to 2 just to test and the previous error is gone, but i do still get lots of:
       Could not remove from in-memory database: <File Name>

**Comment by VorlonCD** [comment]
The latest fixes that one also

**Comment by tkffaul** [comment]
Just wanted you to know that the new updates seem to work perfectly!
