### ISSUE TITLE
AITool Should periodically re-test failed servers

### ISSUE THREAD

**Issue by clarkhaskins** [VorlonCD/bi-aidetection#259]
Currently, every time I restart Deepstack(or restart the machine it's running on) I wind up having to re-enable the server within AITool. I get wanting to disable it if it fails continuously, but it really should be periodically checked to see if it has come back like once a minute or every few minutes.

Thanks!

**Comment by VorlonCD** [comment]
I thought it was doing that but I was ra-ra-wrong.   The following variables in AITOOL.SETTINGS.JSON control this behavior now:

```
URLResetAfterDisabledMinutes = 60;  //If any AI/Deepstack URL's have been disabled for over this time, all URLs will be reset to try again
MinSecondsBetweenFailedURLRetry = 30;   //if a URL has failed, dont retry try more often than xx seconds
MaxErrorsInARowBeforeDisable = 60;
```
https://github.com/VorlonCD/bi-aidetection/tree/master/src/UI/Installer
