### ISSUE TITLE
Thoughts- object variance %

### ISSUE THREAD

**Issue by Tinbum1** [VorlonCD/bi-aidetection#26]
I find that I have to set the object variance pretty high (20%) for most of my cameras as the images detected are often quite small and far away. This is OK but then if an image detected is large and close to the camera this variance % is going to cover a large area.

Would it be an idea that, say, 2 object variance % could be set and which ever is used base on a 'settable' detected image area.

**Comment by classObject** [comment]
@Tinbum1 Still researching ideas to help with distant object variances. I'm currently testing out an idea to create a scale factor for smaller objects that will allow for more variance based on the object size.

**Comment by Tinbum1** [comment]
Thank you so much. Giving it a try.
