### ISSUE TITLE
Improved Night Detection 

### ISSUE THREAD

**Issue by Village-Guy** [VorlonCD/bi-aidetection#261]
I understand that there are 'models' specifically intended to improve night vision detection.  Is there any interest in adding functionality to enable daytime and night time models based upon time of day or even better dusk/sunrise?
We already have the functionality to support more than one incidence of Deepstack so this could be seen as an extension of it, i.e one incidence for day and another for night.

**Comment by VorlonCD** [comment]
In AITOOL, you have been able to set any AI URL to only be active certain times of the day for quite some time.   You can actually use 'dusk-dawn', 'dawn-dusk', 'sunrise-sunset', 'sunset-sunrise' if you dont want to use an hourly range.   I've been using the new Ex Dark custom model at night now for a month and it seems to work pretty good.  Except it doesnt detect as many types of objects.
https://github.com/OlafenwaMoses/DeepStack_ExDark

**Comment by Village-Guy** [comment]
Brilliant and thank you for taking the time out to respond.   I have not updated in a while and have completely missed this feature update.  Needless to say I'm doing an update this evening.

**Comment by Village-Guy** [comment]
The dusk-dawn facility is brilliant.  The only issue I have now is initialising the Dark.pt from within my windows docker installation. Does anyone know the syntax for initialising the Dark Model from within Windows/docker?
Unfortunately it appears the Windows and Linux examples are not applicable.

**Comment by VorlonCD** [comment]
I dont know the docker syntax without researching, but If you wanted to run the latest deepstack for windows outside of docker, the DEEPSTACK tab in AITOOL lets you run both pretty easy.  (As I recall the custom model filename is case sensitive)

![image](https://user-images.githubusercontent.com/7512113/124630933-e1160a00-de50-11eb-9d5d-fa076f27adc7.png)

**Comment by Village-Guy** [comment]
Thanks for that very useful info.  Up until now I have religiously been using Docker as the Deepstack developers stated it was the most efficient solution to run within a windows environment.  Perhaps it is time to consider change!  
I spent several hours this morning and a few last night researching the docker command line for custom models and failed miserably. I will install the Windows version and compare execution times.  Thanks again for your help, your dusk-dawn functionality is truly amazing.

**Comment by Village-Guy** [comment]
I followed your lead and installed Windows DeepStack.  It works just fine but dark mode is a disaster for me.  The original version detects me in very low light pretty much 90% of the time.  Dark mode seems to capture me less than 10% of the time and frequently thinks I'm a table LOL

**Comment by VorlonCD** [comment]
I'm...not a table?

**Comment by VorlonCD** [comment]
I'll try to remember and do a walk around test tonight but I think it seemed ok the last time I checked.

I assume you added "People" (vs person) to the detected object list?

When deer or foxes run through it detects as a Dog but I would expect that.

That dark model may have only been trained on low light not actual black and white/IR

**Comment by Village-Guy** [comment]
Good point! My testing has all been carried out using BW/IR.  I have been testing today using colour samples off the web and it does produce better results.  Perhaps a combined analyses?
Yes, I did enable all the additional objects.  Seemed odd to me that they did not include 'person'.
