### ISSUE TITLE
[Feature Request] Use without BlueIris

### ISSUE THREAD

**Issue by TheOfficialMrBlah** [VorlonCD/bi-aidetection#263]
I use the tool (v2.0 latest build in UI/Installer) without BlueIris. For this I wrote a short script that saves images from the camera in a directory and deletes them again regularly.

- Therefore, it would be a great feature to have an option to switch off the BlueIris connection.

For example, I always get an error message in the settings when saving because my (non-existent) BlueIris server cannot be found.

**Comment by VorlonCD** [comment]
This should do the trick.  No option, but I prevent the error if BI is not installed.
https://github.com/VorlonCD/bi-aidetection/tree/master/src/UI/Installer

**Comment by TheOfficialMrBlah** [comment]
Yes, it works, there is no more error message.

Thank you very much!
