### ISSUE TITLE
Cancel action

### ISSUE THREAD

**Issue by balqosz** [VorlonCD/bi-aidetection#265]
Hi Vorloncd!

 When I write a value in action cancel seconds in one of my cameras, this value replicates to the rest of them. Is this a global setting, per camera setting or bug?

![image](https://user-images.githubusercontent.com/24378221/126177840-6044dabe-e5e5-4fad-b053-8fb643dca911.png)

**Comment by VorlonCD** [comment]
Its a global setting.

**Comment by balqosz** [comment]
Thx for clarification.

Best regards.
