### ISSUE TITLE
Telegram Message - request aborted - could not create ssl/TLS secure channel

### ISSUE THREAD

**Issue by xanthos84** [VorlonCD/bi-aidetection#267]
hi, is this tool working under Windows 7?
Because I get following when sending out Telegram messages:

    Could not upload image C:\img\image1.20210724_065246593_AITOOLTEST_28944,5205078.jpg to Telegram with chatid '*********': The request was aborted: Could not create SSL/TLS secure channel. [WebException] (In ClsTriggerActionQueue.TelegramUpload:1383 > BotMakeRequestAsync)

Under Windows 10 it was working fine...
Thanks

**Comment by VorlonCD** [comment]
I dont test on Win7, but search for "internet options" in the control panel or start menu, then click the ADVANCED tab and enable "Use TLS 1.2" and "1.3"

**Comment by VorlonCD** [comment]
And maybe try forcing a Windows Update.  Or just let it upgrade to Win10
