### ISSUE TITLE
Enhancements to variables

### ISSUE THREAD

**Issue by aesterling** [VorlonCD/bi-aidetection#27]
Please let me know if this request should be directed elsewhere.

There are a few adjustments or additions to the variables list that would help make the data more easily digestible. I'm passing this data to BI via the Trigger URL for push notification text and trying to make the info as "pretty" as possible for the non-techy family members to read.

Is it possible to _add_ these modified variables to the list of current ones, so as not to affect existing users?  

- Object names in Title Case (For example, Person rather than person, Dog rather than dog)
- Confidence percentage that _doesn't_ include surrounding parenthesis. (For example, I want to use the confidence percentage in the text of a push notification without parenthesis around the value.)
- Confidence percentages as whole numbers, without tenths or hundredths values. (For example, 79% rather than 79.84%) Same comment about this value where it appears in the annotated image, below the bounding box.

Thank you in advance for considering.

**Comment by aesterling** [comment]
P.S. the variables were originally discussed in the ipcamtalk megathead the [bottom of page 30](https://ipcamtalk.com/threads/tool-tutorial-free-ai-person-detection-for-blue-iris.37330/page-30#post-455989), and [top of page 31](https://ipcamtalk.com/threads/tool-tutorial-free-ai-person-detection-for-blue-iris.37330/page-31), but didn't include all the adjustments I requested above.

**Comment by VorlonCD** [comment]
Ok, I just implemented this but without new variables in the new push.   Yet anyway.

See "DisplayPercentageFormat" setting in Json settings file.   For your request you can change it from the default:

({0:0.00}%)
to:
{0:0}%

And I'm now forcing all object names to be case title in any case.   I'm sure I'll find out if someone has done case insensitive checks against object names out there. :)

**Comment by VorlonCD** [comment]
@aesterling - is this working how you need it to?

https://github.com/VorlonCD/bi-aidetection/releases

**Comment by aesterling** [comment]
Awesome work, once again, @VorlonCD. Sorry for my delayed response! These changes are working nicely in the AI Tool interface, but the merged/annotated JPEG still shows percentage with the tenths or hundredths values. (99.97%) The title case works properly in the merged JPEG.

**Comment by VorlonCD** [comment]
@aesterling - DOH!!   This fixes for image merging:
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5250680/AITOOL-VORLONCD.zip)

**Comment by aesterling** [comment]
:) Will download and test shortly! Thank you!

**Comment by aesterling** [comment]
Hmm, still showing the tenths/hundredths values on the merged JPEG.

Please forgive my ignorance, but am I updating the tool correctly?

1. I download the release ZIP. (in this case, from your [comment](https://github.com/VorlonCD/bi-aidetection/files/5250680/AITOOL-VORLONCD.zip) above.)
2. I right-click > Properties > "Unblock" then unzip the contents. 
3.  Next I stop the running AI Tool, copy the contents from the unzipped folder to my AI Tool folder (C:\ai_tool) and overwrite the existing files.

Can I keep the AITool.exe.config and AITool.Settings.json files from the previous version to avoid re-configuring those settings, or do they need to be deleted and recreated from scratch?

Before leaving this comment, I deleted all the files and replaced them with the contents of the ZIP. I then changed the DisplayPercentageFormat in the JSON file to {0:0}%. It appears as expected in the AI Tool interface, but still with the decimal place digits in the merged JPEG.

Thanks!

**Comment by VorlonCD** [comment]
That is the correct procedure, and you can keep your last json file, they should always be forward compatible, not always back.
That is my exact format setting here, and it reflects the change in merged files that were copied.   You wont of course see the "merged" changes when viewing history tab.

**Comment by VorlonCD** [comment]
@aesterling - I didnt know about that!   Very nice.    The push I made to the code just now should fix the imagepath issue - let me know.

**Comment by VorlonCD** [comment]
I also just added a new [ImagePathEscaped] variable for use with that.  Seems to work great!   I can see the merged annotations in BI now.

**Comment by aesterling** [comment]
Awesome, I always have to wait for you to compile, but looking forward to testing it!

I'm having some trouble and wondering if the JPEG is still being written to disk when BI tries to grab it. The same URL works fine when I load it in my browser, but not from AI Tool. Will keep testing!

**Comment by VorlonCD** [comment]
How is this latest version working with image copying and &jpeg=[ImagePathEscaped]?

[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5330198/AITOOL-VORLONCD.zip)

**Comment by aesterling** [comment]
The annotated and merged image shows up as my alert image in BI! ...and then BI immediately crashes. Looking into that problem, but AI Tool is working as intended!
