### ISSUE TITLE
is it possible to use custom model on deepstack?

### ISSUE THREAD

**Issue by yeahman45** [VorlonCD/bi-aidetection#275]
Deepstack overall runs pretty well during the day but during night, it is much more inaccurate.
I stumbled on this custom model : https://pythonrepo.com/repo/OlafenwaMoses-DeepStack_ExDark-python-deep-learning
I am wondering if it is possible to use this custom model in addition to the default current model? 
or if it is not possible maybe schedule switching model depending on time of the day?

**Comment by MissMusic** [comment]
Yes?
![image](https://user-images.githubusercontent.com/35969207/131643638-a1a7278e-0a1c-4903-88b6-cd7e9690436a.png)
As you can see, you can add the same deepstack instance multiple times with different URL:s to trigger different custom models. There's also the option to add time-ranges for each server. I have not tried it myself, but i would assume it works fine.

**Comment by yeahman45** [comment]
nice thx man
