### ISSUE TITLE
UnauthorizedAccessException (ip blue iris)

### ISSUE THREAD

**Issue by malosaa** [VorlonCD/bi-aidetection#278]
How to give permission ?

Give the current user (DESKTOP-S7AI4BS\Home Security System) access to '192.168.1.8': Attempted to perform an unauthorized operation. [UnauthorizedAccessException] (In BlueIris.RefreshBIInfoAsync:121 > BlueIris<>c__DisplayClass15_0<RefreshBIInfoAsync>b__0:121 > Win32.RegistryKey.OpenRemoteBaseKey(RegistryHive hKey, String machineName, RegistryView view) > Win32.RegistryKey.Win32ErrorStatic(Int32 errorCode, String str))

regards

**Comment by VorlonCD** [comment]
It is not required, but AITOOL wont be able to see BlueIris settings such as lists of camera names, etc.

Simply add a new user called 'Home Security System' to the machine BI is running on:
https://support.microsoft.com/en-us/windows/create-a-local-user-or-administrator-account-in-windows-20de74e0-ac7f-3502-a866-32915af2a34d

**Comment by malosaa** [comment]
@VorlonCD 

i did do that but doesnt work.

so if its not required i leave it as is.

**Comment by VorlonCD** [comment]
The user would have to have the same username + password on each machine.   On top of that, you may need to make sure the "Remote Registry Service" is set to always run and might have to disable the firewall.  I think its disabled by default.
