### ISSUE TITLE
Feature request - mode setting for custom model

### ISSUE THREAD

**Issue by Yonny24** [VorlonCD/bi-aidetection#281]
I have 2 deepstack servers running.

Is there any way of setting Mode medium for one and High for the other? I had this previously when running in docker as containers but now moved to windows to reduce the extra cpu taken up my docker desktop.

I can't find a way on the AI tool. Maybe by command line? 
The ai tool sets the mode to both and has no visible option to have different settings for a custom model

Many thanks

**Comment by Yonny24** [comment]
@VorlonCD ok thanks for the update.
This would be a fantastic feature on your tool.

**Comment by marrobHD** [comment]
Unfortunately I get a timeout on 2.1.1 when specifying modes for the custom models. There's also no way to left the mode(s) field clear.

**Comment by VorlonCD** [comment]
The deepstack python scripts are apparently CASE SENSITIVE, so it needs Medium, Low, High.  I was forcing to upper case.  Fixed in next build.

**Comment by marrobHD** [comment]
I've tried Medium and Low...

**Comment by VorlonCD** [comment]
Right but was forcing Medium to be MEDIUM, so fixed in a bit...

**Comment by MissMusic** [comment]
Seriously!?!

Sorry for bumping, i just wanted to say THANK YOU Vorlon!  I have been unable to run Deepstack on High with my custom models, deepstack started but just timed out on all requests. Using --MODE High <-(not in uppercase) and it runs like a dream. I have been running in default mode the whole 2021 just because of this FML.

**Comment by VorlonCD** [comment]
Heh yeah I poked precariously around in the python code and found the modes and probably a lot of other things are case sensitive.
