### ISSUE TITLE
Interface cut off at bottom of History tab

### ISSUE THREAD

**Issue by aesterling** [VorlonCD/bi-aidetection#29]
I'm running [v1.77](https://github.com/VorlonCD/bi-aidetection/releases/tag/1.77) and the bottom of the History tab is cut off so I cannot access the checkboxes for "Only Relevant Alerts" and "Only False/Irrelevant Alerts." Below are two screenshots (default window size and maximized) where you can barely see the first checkbox visible. My screen resolution is pretty low at 1920x1080, if that's relevant.

![Screenshot 2020-09-19 164723](https://user-images.githubusercontent.com/18314707/93689854-39ce0f00-fa98-11ea-94ce-b47a3ce0e93d.png)

![Screenshot 2020-09-19 164744](https://user-images.githubusercontent.com/18314707/93689844-1905b980-fa98-11ea-9f76-0cc114cd7408.png)

In addition, for some reason, I'm seeing "All Cameras" listed twice in the filter list. Once at the top and once at the bottom. I assume this is a config error on my end, but please let me know how to remove the duplicate.

<img width="503" alt="Screen Shot 2020-09-19 at 04 28 25 PM@2x" src="https://user-images.githubusercontent.com/18314707/93689906-9e896980-fa98-11ea-9140-f988705e801d.png">

Thank you again for all the great work!

**Comment by VorlonCD** [comment]
I need to refactor this at some point.  For now, move mouse just above the name of the camera and you can see a resize splitter bar to make the filter section bigger.   Not sure how All cameras got in there twice, thanks for letting me know

**Comment by aesterling** [comment]
I promise I tried that before creating an issue! :) I just tried it again and found it this time.

Thanks again!

![Screen Shot 2020-09-19 at 05 03 56 PM@2x](https://user-images.githubusercontent.com/18314707/93690111-53705600-fa9a-11ea-916d-31db011b21d1.png)

**Comment by aesterling** [comment]
Sorry I didn't search the closed issues where this was previously discussed. Will do for future issues!
