### ISSUE TITLE
Getting a double percentage symbol %% for object confidence with AI Tool and BI notifications

### ISSUE THREAD

**Issue by aesterling** [VorlonCD/bi-aidetection#293]
Hello, I recently started getting a double percentage character in the memo field from BI notifications with AI Tool. Did anything change in AI Tool that may have caused this? Suggestions of where I can fix it? Thanks in advance! Currently running v2.8.1206 (7/10/2021) with BI 5.5.2.5. 
![IMG_5732](https://user-images.githubusercontent.com/18314707/142044034-d2223d65-f9f8-419c-8b54-c68813198193.PNG)
![Screen Shot 2021-11-16 at 12 25 52 PM](https://user-images.githubusercontent.com/18314707/142044057-bb16fb87-a6c3-4cc7-a250-3c2df2443193.png)

![Screen Shot 2021-11-16 at 12 23 07 PM](https://user-images.githubusercontent.com/18314707/142044075-27450fcc-3a09-40ae-aa62-08ed4aa33bc8.png)

**Comment by VorlonCD** [comment]
If the memo appears correct in BI Alerts list but not when using &MEMO its very likely a BI issue.  

I recently updated a few things, but you would have had to install it.  And nothing changed with the [variables] in AITOOL.

Changes:
https://github.com/VorlonCD/bi-aidetection/commit/56e643cf988ba0d7755c7cb4fbb938b2c14aade1

2.1 Installer:
https://github.com/VorlonCD/bi-aidetection/tree/master/src/UI/Installer

**Comment by aesterling** [comment]
Thanks, I've reached out to BI support asking about this. I will reply here and close the issue if it's resolved.

**Comment by aesterling** [comment]
BI support appears to have fixed this in one of the recent updates. Closing this issue now. Thanks!
