### ISSUE TITLE
  Error: Input path () & 'Copy alert images to folder' path may not be the same.

### ISSUE THREAD

**Issue by rtman238** [VorlonCD/bi-aidetection#294]
I updated from 2.0.1206 to 2.1.1.0 and in the log I get "Update Camera   Input path () & 'Copy alert images to folder' path may not be the same." I get this error at startup as well as after each time a triggering object is identified. Under the camera settings/MQTT Copy I have a path set to copy the alert.

**Comment by VorlonCD** [comment]
if both paths are empty, this error will happen.  Fixed shortly in next release.   Even if you dont use it, a temp fix is to add any path to the Camera Actions > Copy Alert Images To Folder.   Enable it, add the path, and disable it.

**Comment by rtman238** [comment]
Thanks. New release resolved this.
