### ISSUE TITLE
2.1.4 causing Telegram API error

### ISSUE THREAD

**Issue by rshide** [VorlonCD/bi-aidetection#295]
Updated to 2.1.4 yesterday and have been receiving the following error every minute.  Alerts are still being posted to Telgram.  I've tried disabling the alerts and the error continued to appear with alerts disabled.  I've also made sure that I only have a single instance of AI Tool running.

`  Telegram API  [409] Conflict: terminated by other getUpdates request; make sure that only one bot instance is running`

**Comment by VorlonCD** [comment]
You are sure Task Manger > Details tab didnt have another instance of AITOOL running, such as a SERVICE?   
Or could another tool be using your Telegram API Token?   Both would cause that error.

The latest version I just posted will handle that better and there is a setting you can disable listening for telegram commands from AITOOL if required:

2.1.5:

- Add min/max/avg stats SIZE to all relevant objects - View in relevant object manager.  This way you can tell how big or small certain objects ever get and limit them better.
- Fix Telegram errors:  I found that when my Internet went out there was a telegram.bot bug where it would repeat an exception many times a second, so I rate limited it to one every 2 minutes if it is a duplicate message.
- Telegram:  Only start listening for reply command messages if there is not another instance of AITOOL running on the same machine (like as a service).   Try to prevent 'Telegram API [409] Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'
- Telegram:  AITOOL.SETTINGS.JSON now has a setting called "telegram_monitor_commands" so you can disable listening to the telegram chat commands.  You may need to do this if using AITOOL or another telegram app on another machine using the same Telegram TOKEN.
- A few more basic remote control commands via Telegram:   PAUSE, START, MUTE,  UNMUTE, VOLUMEUP, VOLUMEDOWN, VOLUMESET LEVEL, RESTARTCOMPUTER

**Comment by rshide** [comment]
Thanks, no luck resolving this.  I went ahead and created a new bot and token and I'm not seeing the same issue.
