### ISSUE TITLE
AITool startup / warm up delay

### ISSUE THREAD

**Issue by Mrdindon** [VorlonCD/bi-aidetection#297]
Hi,
Is it possible to add some sort of delay config where AITool would wait before looking for "Default input path" ?
I'm using a network mapped drive and sometime after a reboot AITool wont kick in because the mapping was not completely done.
BlueIris does not seem to complain on it's side and will just recover once mapped but AITool will just not recover from it until restarted.

**Comment by VorlonCD** [comment]
I can add that for the next version, but all you need to do is use the UNC path rather than mapped drive letter to prevent that from happening.   (\\servername\share\camimages)

**Comment by Mrdindon** [comment]
I'm already using unc.
The thing is the storage is running truenas on another vm. I configured my BI vm (with AITool) to start delay after 60 sec but sometimes truenas needs to clean his storage and that makes the share available a bit later depending on the works it needs to do. Thats why I was thinking of adding a delay within AITool or maybe a retry X time in X seconds ? Dunno what is the easiest / more practical to do..

**Comment by VorlonCD** [comment]
Oh it already does this.   When there is an error trying to initialize the file watcher, it will retry every 5 minutes by default.  So you should see it kick in eventually?

See 'FileSystemWatcherRetryOnErrorTimeMS' in AITOOL.SETTINGS.JSON if you want to lower that value.
