### ISSUE TITLE
UI Issues / minor improvement

### ISSUE THREAD

**Issue by SHerms** [VorlonCD/bi-aidetection#3]
@VorlonCD Thanks for doing all this awesome work on this AI bridge program. I just grabbed the latest release and tried it out.

I noticed 2 minor UI issues. One is on the history tab. The filter options are gone. I've had this issue before and I was able to resize it somehow and it would show the checkboxes. But I can not get it to show anything other than the drop down for camera filtering.
![Screenshot from 2020-09-01 12:45:27](https://user-images.githubusercontent.com/15882787/91883648-b9637d80-ec52-11ea-9660-ebf19e87d47c.png)

The other issue I noticed the buttons on the settings tab under masking shrink when the window is smaller. Don't think it is really needed as there is enough room to display them. Also noticed the checkbox for sent alert messages to telegram gets cut off.

![Screenshot from 2020-09-01 12:45:47](https://user-images.githubusercontent.com/15882787/91883638-b5376000-ec52-11ea-902c-21cf7fc4dbdd.png)

The only improvement I was thinking that would help speed up adding cameras is under the settings tab add a blue iris login name and password. This would let you fill in the full trigger path completely. As it is now the text box doesn't resize and it is hard to see the end of the string. I only noticed it because I had to replace the user and password for the trigger URL. Had to copy and paste the string in to notepad to see the whole thing. If it was populated from the settings info it would work automatically without needing any modifications.

Thanks again!

**Comment by VorlonCD** [comment]
I'm going to eventually re-do the History tab to make it faster.   For now, just move the splitter by grabbing here:

![image](https://user-images.githubusercontent.com/7512113/91884750-9df97200-ec54-11ea-8430-ec04ff83ffe2.png)

If the latest version doesnt fix the Camera tab UI, I'm assuming in windows display options you have it set higher than 100% scaling?     If you cant set that lower, then make a shortcut to AITOOL.EXE, go to properties > Compatibility tab and experiment with DPI settings.

https://github.com/VorlonCD/bi-aidetection/releases

**Comment by SHerms** [comment]
Thanks for the screenshot with the arrow. I was able to resize the filter area. Maybe setting a default value so it shows everything when the user first opens the application? Now that I resized it, it seems to of remembered the size. I just tried the latest version, the camera tab UI buttons only shrink when I make the window size small.
