### ISSUE TITLE
Error with "Start with user login (Non-Service)"

### ISSUE THREAD

**Issue by aesterling** [VorlonCD/bi-aidetection#30]
I'm currently running [v1.77](https://github.com/VorlonCD/bi-aidetection/releases/tag/1.77) with the "Start with user login (Non-Service)" checkbox checked, but I'm getting the following two messages immediately after login. (I have my user set to auto-login after boot.)

<img width="557" alt="Screen Shot 2020-09-19 at 04 31 16 PM@2x" src="https://user-images.githubusercontent.com/18314707/93690000-70585980-fa99-11ea-89b1-4d94e2f9410a.png">

and after I click "Yes" then this appears:

<img width="547" alt="Screen Shot 2020-09-18 at 10 27 19 AM@2x" src="https://user-images.githubusercontent.com/18314707/93690002-7fd7a280-fa99-11ea-949f-9aa9aef9eb67.png">

Apologies if this has been discussed and addressed on the forum. I didn't see an answer, but I assume it's a very simple fix I'm just not aware of.

**Comment by VorlonCD** [comment]
For first message, make sure **before** you UNZIP that you right-click > properties > Unblock.
For second, it is most likely harmless - Hmm I wonder how you change the "start in" folder for items that start from the RUN registry entry?  I put that in to troubleshoot when the app may be loading DLL files from a folder other than the AITOOL folder, but maybe it doesnt matter anyway.

**Comment by aesterling** [comment]
The second message prevents AI Tool from running until I've clicked OK. I haven't found a way to bypass it. Same result if I attempt to use Task Scheduler to launch AI Tool.

UAC prompt is no longer a problem. Thanks.

**Comment by VorlonCD** [comment]
Fixed:
* Disable Error about start in folder not being the same - rather, if started with a different startin path than the exe is running from I do a SetCurrentDirectory to force it to be correct.   This may avoid potential dll file conflicts

[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5252343/AITOOL-VORLONCD.zip)

**Comment by aesterling** [comment]
Thank you, that fixed the second error. All good now. Feel free to close this if you'd like, I don't know if it's proper etiquette to close it myself.
