### ISSUE TITLE
dynamic mask counter

### ISSUE THREAD

**Issue by opa-rudi** [VorlonCD/bi-aidetection#300]
I don´t know if I am doing something wrong, but when I set up a dynamic mask with "create mask after 1 detections", aitool counts up to 2 detections until it creates a mask. Is this a normal behavior?

**Comment by VorlonCD** [comment]
This is expected.  I dont see what the confusion is about "create mask **AFTER** 1 detection's".    The first detection would never create a dynamic mask. (nor would you ever want it to, that defeats the purpose of alerting on object detection).    As soon as the second one is detected, a mask is created.

If you want a permanent mask, use "Image mask" not dynamic mask.  Or right-click a detected mask and make a STATIC mask

**Comment by opa-rudi** [comment]
But I can´t create a dynamic mask after the first detection. The dyn mask is created when the counter is 1, so there are minimum 2 detections. First detection is starting with 0 and the second with 1 and then creating the mask. Am I wrong?

**Comment by opa-rudi** [comment]
static mask would never fire.

**Comment by VorlonCD** [comment]
The dynamic mask wouldnt be created until the second time the object was detected.

If even a static mask doesn't work, then regular dynamic masking probably wouldn't work either.    

Maybe BlueIris is creating images at different resolutions?   That is a common issue and will interfere with Masking in general.

Go to Camera > Draw mask > Custom button:    Hit SCAN button and see if it finds **more than one resolution**.   If so, you would have to create a mask for each resolution.  Or somehow prevent BI from sending images from its main camera stream AND the substream.
