### ISSUE TITLE
İspy agent setting

### ISSUE THREAD

**Issue by byfaruk** [VorlonCD/bi-aidetection#306]
Hello...
Can you help me how to set ispyagent instead of aitool blueiris

**Comment by byfaruk** [comment]
@VorlonCD

**Comment by VorlonCD** [comment]
never used it.  But if it has the feature to spit out new JPG images on every movement, you would watch that folder with aitool just like you do with blueiris.

**Comment by byfaruk** [comment]
I want to use more than 1 deepstack. I installed deepstack on ubuntu server, but how about aitool settings?

**Comment by VorlonCD** [comment]
The deepstack "tab" in AITOOLS is only for the "Windows" version of deepstack.  I feel like I should say sorry??  :)

Otherwise in Settings > AI Server URLs, you would have to configure the URL for each of the deepstack URL's you have configured on Ubuntu.
