### ISSUE TITLE
Telegram chat id 

### ISSUE THREAD

**Issue by byfaruk** [VorlonCD/bi-aidetection#311]
Can I send pictures in different folders to different telegram channels? @VorlonCD

**Comment by VorlonCD** [comment]
You might be able to with a camera set up per folder?   I would need more detail.

**Comment by byfaruk** [comment]
yes, I have one camera per folder. I need to telegram token and id to be different
@VorlonCD

**Comment by VorlonCD** [comment]
Each camera lets you specify a different Chat ID, but not Token.

**Comment by byfaruk** [comment]
Can you update to specify token? :) @VorlonCD

**Comment by VorlonCD** [comment]
The telegram engine I use only takes a token when I initialize it.    So I cant easily assign a token per camera unless I consume a lot of extra memory by initializing a instance of the telegram engine per camera.   So, since no one else has has asked for this feature I'm not going to attempt it.
