### ISSUE TITLE
Not a Issue- Just a Question

### ISSUE THREAD

**Issue by balucanb** [VorlonCD/bi-aidetection#326]
Just wondering- Do you plan on releasing any new updates or is it a compile your own deal now? Hope not because I have no idea how to do that! :)  I am running 2.2.24, working fine, just curious. Thanks and still love your work!

**Comment by VorlonCD** [comment]
I'll probably only release an update if something is broken or there is a really good easy to implement feature.

**Comment by balucanb** [comment]
Cool beans
