### ISSUE TITLE
Separate "Triggering Objects" for Telegram is not working

### ISSUE THREAD

**Issue by nefh** [VorlonCD/bi-aidetection#330]
Hi!
I use AITool to trigger main camera streams to record whenever it might be something interesting in the view with low prediction threshold (40%), to not have a chance to miss anything important. In the same time, I would like to be notified via Telegram when any actually confirmed activity is happening at my doorstep. Therefore I set separate, higher values (75%) in Triggerring Objects table for Telegram action. Unfortunately, this does not work. I am getting frequently messages with recognized objects below 75% but above 40% - for sending Telegram messages it is still getting values from the Default Triggering Objects table.

**Comment by arthmost** [comment]
Hi! I'm still facing exactly the same issue. And don't have any solution sadly. 

My post: https://github.com/VorlonCD/bi-aidetection/discussions/329

**Comment by VorlonCD** [comment]
Try what I just suggested here:
https://github.com/VorlonCD/bi-aidetection/discussions/329
