### ISSUE TITLE
Statistics Reset

### ISSUE THREAD

**Issue by Village-Guy** [VorlonCD/bi-aidetection#37]
Not sure if there is currently a way to reset stats as clearing it in the camera files no longer works.  Would it be possible to have a reset button on the stats page?

**Comment by VorlonCD** [comment]
The stats tab is dynamically generated from the history.csv file.   So the only way to reset is to delete history.csv and start fresh.

The stats on the camera tab could be easily reset with a button if needed.   You can manually reset by closing the app, editing the json file and setting these to 0 wherever you find them (multiple instances, one for each camera)

stats_irrelevant_alerts
stats_alerts
stats_false_alerts
