### ISSUE TITLE
Static masks still being shown.

### ISSUE THREAD

**Issue by Tinbum1** [VorlonCD/bi-aidetection#40]
Some of my static masks don't seem to be working.  I'm getting telegram messages and they are showing up in the history tab but then they are not showing in the cameras/details/history window. I already have a static mask set up for them in the cameras/details/active masks. I will provide further details when i have bit more time tomorrow.

**Comment by VorlonCD** [comment]
Let me know if this is still happening in the latest push with better distant object support.   Otherwise will need mo detail - note that you can CTRL-C to copy each mask info details into the clipboard which may be needed.

**Comment by Tinbum1** [comment]
![image](https://user-images.githubusercontent.com/66704787/94606992-36eecd80-0293-11eb-9ceb-e65d6bb0a776.png)
![image](https://user-images.githubusercontent.com/66704787/94607058-5259d880-0293-11eb-882c-8022ba5fb1f8.png)

I would expect the image to appear in the dynamic mask history box at the top if there is no dynamic mask. But in this case there is a mask but the image has still come through.

**Comment by Tinbum1** [comment]
The image has come through after the mask was set up but it also does not show in the dynamic mask history top window.

![image](https://user-images.githubusercontent.com/66704787/94608097-c779dd80-0294-11eb-9f06-fc272f4e01a9.png)

![image](https://user-images.githubusercontent.com/66704787/94608214-f728e580-0294-11eb-85f1-16e316a9f30f.png)

**Comment by VorlonCD** [comment]
Dont blink?!

**Comment by Tinbum1** [comment]
Ok now.
