### ISSUE TITLE
Feature: Separate settings/logs/etc from app

### ISSUE THREAD

**Issue by jdom** [VorlonCD/bi-aidetection#41]
Consider separating the settings, cameras, history, logs (all dynamic files) from the app folder itself. This would allow just getting the latest version of the app and running, it, without making sure to copy all the files from the previous version of the app, nor making sure you over-write the right files.
A good option is to put stuff under the user folder (there's good APIs to help create an app folder inside the user's profile). The user profile would be an issue if you plan to run as a service.
Alternatively, at least put all the files inside a specific folder (if you make that configurable, then sure, you can put this setting alone along side the app), or a sub-folder that you can copy in its entirety.
Today the experience is that you need to copy the `cameras` folder as well as some other files in the root folder, which is error prone.

**Comment by VorlonCD** [comment]
The way it works now is basically a "portable" mode where you can have side by side versions with different settings for testing.   If it wasnt set up that way you couldnt go back and forth easy because settings change from release to release.

I agree settings should usually be in %appdata% and plan on putting an an option for that

**Comment by jdom** [comment]
Yeah, I thought that you might want to keep it portable until it's more stable. That's why my alternative suggestion was to limit these user files to a single folder, so that they are easier to copy over to a new version, instead of digging in different folders

**Comment by VorlonCD** [comment]
The latest build has everything in the executable folder - the log, the settings json file and the SQLITE3 history database (rather than \cameras\history.csv)

**Comment by jdom** [comment]
right, but would you consider putting everything in a subfolder instead? this could be the `cameras` folder (or some more generic name, but that would include the cameras configuration also). This way no need to dig between all the DLLs and potentially miss something, as well as copying the `cameras` folder.
Anyway, not a huge deal, just a suggestion.

**Comment by VorlonCD** [comment]
Oh I see what you mean, good suggestion

**Comment by VorlonCD** [comment]
This has been implemented for a few builds.   Everything goes to \_Settings subfolder unless you set "SettingsPortable=false" in the JSON file in which case it moves everything to an %appdata% subfolder.
