### ISSUE TITLE
Idea, detections are hidden when behind a custom mask

### ISSUE THREAD

**Issue by Tinbum1** [VorlonCD/bi-aidetection#42]
At the moment the program still logs detection's in the mask history even if they are hidden behind a custom mask. Might it be a good idea that these are not stored making it easier to go through the relevant dynamic mask detail history and also reducing the size of the json file. It may also reduce processing time? or perhaps not.

**Comment by Tinbum1** [comment]
Also on the Dynamic mask Detail tab/ active masks, when you click on a mask it shows the mask on the image with a description of what it is. Would it be possible to add the 'key' so the mask can be easily identified.


![image](https://user-images.githubusercontent.com/66704787/95001244-03c47b00-05c0-11eb-8a73-c40db1995d80.png)

**Comment by VorlonCD** [comment]
Sure, look for it in the next update

**Comment by Tinbum1** [comment]
Thank you.

**Comment by VorlonCD** [comment]
Back to your original suggestion, not storing masked items (and potentially false detection) may save some time loading the database but I cant say how much.  You would sacrifice the ability to troubleshoot detection's.  The latest version is faster, do you think it is worth creation an option for it?

**Comment by Tinbum1** [comment]
Yes, option is great idea. It would help reduce the masks in the Dynamic mask history and active page. I'm getting dynamic masks created for items hidden behind custom masks.

**Comment by VorlonCD** [comment]
Right now the dynamic mask routine is run BEFORE the check if something is masked with the old style image mask.   Perhaps it should be the other way around?

**Comment by Tinbum1** [comment]
That sounds logical to swap it.

**Comment by VorlonCD** [comment]
these features working for you ok?

**Comment by Tinbum1** [comment]
Yes brilliant , thank you.

This program is just getting better and better all the time. Thank you for all your hard work and incorporating all our suggested features and the ones your coming up with.
