### ISSUE TITLE
Craches daily

### ISSUE THREAD

**Issue by MissMusic** [VorlonCD/bi-aidetection#44]
I experience a lot of crashes. I'm running release 1.77.

Latest crash was this morning.

Event logg shows:
Application Error:
Faulting application name: AITool.exe, version: 1.67.8.0, time stamp: 0x5f677d79
Faulting module name: clr.dll, version: 4.7.3661.0, time stamp: 0x5f054591
Exception code: 0xc00000fd
Fault offset: 0x0000000000053f4a
Faulting process id: 0x2cf8
Faulting application start time: 0x01d694b2166f43ff
Faulting application path: C:\AI.Tool.1.67\Release\AITool.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report Id: 041f9749-f2eb-4374-a987-860d7ee2f3bb
Faulting package full name: 
Faulting package-relative application ID: 

I have now enabled "Log Everything", and also realized the log is overwritten on restart of AITool, I'll save it after next crash before restarting.

Anyone else experiencing instability?

**Comment by Tinbum1** [comment]
I have done in the past when processing loads of images, but I think Chris has fixed it with his latest commits.

**Comment by VorlonCD** [comment]
@MissMusic - Let me know how the latest is working for you.   Should be faster and more stable than the last version.
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5295116/AITOOL-VORLONCD.zip)

**Comment by MissMusic** [comment]
@VorlonCD Thanks, I just updated, I'll report back if i have any more issues.
