### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SHerms** [VorlonCD/bi-aidetection#47]
Last night was the first time I've ever ran in to this issue. I'm assuming it got overloaded. During the time it crashed BI was creating a bunch of images. 

Crash report attached:
`
Log Name:      Application
Source:        Application Error
Date:          9/30/2020 5:20:34 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP
Description:
Faulting application name: AITool.exe, version: 1.67.8.0, time stamp: 0x5f5ea760
Faulting module name: mscorlib.ni.dll, version: 4.8.4220.0, time stamp: 0x5f03a9e2
Exception code: 0xc00000fd
Fault offset: 0x003f8565
Faulting process id: 0x2090
Faulting application start time: 0x01d68ea3870a98fe
Faulting application path: C:\Users\shane\source\repos\bi-aidetection\src\UI\bin\Release\AITool.exe
Faulting module path: C:\Windows\assembly\NativeImages_v4.0.30319_32\mscorlib\00b9a45b7a0e1b0c1507b52befccdc63\mscorlib.ni.dll
Report Id: 2ccf572c-36fc-470c-b6c3-42cad63db0bd
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-09-30T09:20:34.705112800Z" />
    <EventRecordID>12726</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP</Computer>
    <Security />
  </System>
  <EventData>
    <Data>AITool.exe</Data>
    <Data>1.67.8.0</Data>
    <Data>5f5ea760</Data>
    <Data>mscorlib.ni.dll</Data>
    <Data>4.8.4220.0</Data>
    <Data>5f03a9e2</Data>
    <Data>c00000fd</Data>
    <Data>003f8565</Data>
    <Data>2090</Data>
    <Data>01d68ea3870a98fe</Data>
    <Data>C:\Users\shane\source\repos\bi-aidetection\src\UI\bin\Release\AITool.exe</Data>
    <Data>C:\Windows\assembly\NativeImages_v4.0.30319_32\mscorlib\00b9a45b7a0e1b0c1507b52befccdc63\mscorlib.ni.dll</Data>
    <Data>2ccf572c-36fc-470c-b6c3-42cad63db0bd</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
`

**Comment by SHerms** [comment]
Crashed again. So weird as I've not updated the version in awhile and it was working fine for so long.

![Capture](https://user-images.githubusercontent.com/15882787/94827480-7d991080-03d6-11eb-8c74-e0de174d2445.PNG)

**Comment by VorlonCD** [comment]
Have tried the latest (as of last night I think)?   I think a common source for this kind of crash is the UI being overloaded with updates - in theory that should be taken care of now.

Another user who was having a lot of crashes like that reported that uninstalling and reinstalling his antivirus helped (AVG).   Note if you uninstall it, windows defender should take over and it is really not bad - all my machines use it now and things have been a lot more stable compared to Avast.

**Comment by SHerms** [comment]
I have not tried the latest version. I'll try that today at some point. No antivirus set up. This is a VM running only Blue iris.

**Comment by SHerms** [comment]
Just tried the latest release. Even with the window maximized I can not see the tabs. 

![Capture](https://user-images.githubusercontent.com/15882787/94837556-66602000-03e2-11eb-9d46-83b240f9e750.PNG)

**Comment by VorlonCD** [comment]
designed for minimum of 1080p screen size, try that.

**Comment by SHerms** [comment]
This is what I had to do to view the tabs.

Change resolution to 1280x1024. Open program. Still can't see them, maximize window. They show up fine. Resize window down smaller and it works. 
Change resolution back to 1280x768 and it still works fine. Close program and reopen it and it is broken again.

So the program can fit fine in that size window, but for some reason it is tied to resolution when starting. Can't really run a higher resolution on this VM without the CPU going up.

**Comment by SHerms** [comment]
Still haven't tried the new version yet. Crashes have happened a couple more times. When you get a chance could you make another release? I can no longer compile from source. I'm using the community edition of VS and the trial has expired. Thank you.

**Comment by VorlonCD** [comment]
You probably have the pro version if it expired.  The community version should not be limited like that.

Here is the latest.  Lots of changes for stability, and i totally disabled the HIGH DPI support since so many people are remoting into other systems and having trouble with it.  Will make official release when I get time to put a few more features in.   Let me know how it is working...
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5356177/AITOOL-VORLONCD.zip)

**Comment by SHerms** [comment]
Thanks. Maybe I need to sign in with a Microsoft account to continue using it? I installed the community version. Are there instructions on how to upgrade. Which files we need to copy over? Or should I just reset up the cameras?

**Comment by VorlonCD** [comment]
Looks like you have to sign in to community to go past 30 days:
https://visualstudio.microsoft.com/vs/support/community-edition-expired-buy-license/

For aitool just backup your current folder to be safe and drop the new files in.  That should be it.

**Comment by SHerms** [comment]
Just tried the new version. Resolution is fixed :). Thank you.
I am getting a bunch of errors though.
![Capture](https://user-images.githubusercontent.com/15882787/95619269-54aef600-0a3c-11eb-99c4-1a93c614be02.PNG)

**Comment by VorlonCD** [comment]
just fixed that a little while ago.   Should try to get community vs working though.  Let me know what the solution is if you find it from the link I sent.
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5356969/AITOOL-VORLONCD.zip)

**Comment by SHerms** [comment]
new version seems to of fixed the errors.
