### ISSUE TITLE
Windows environment variables %date% and %time% in MQTT payload

### ISSUE THREAD

**Issue by whyfseeguy** [VorlonCD/bi-aidetection#50]
Hi,

I am trying to include the date and time of the trigger in MQTT message payload with %date% $time%, but it does not appear that they are substituted in the payload, do you know why?

Thanks.

**Comment by VorlonCD** [comment]
It doesnt work because those are not true environment variables.  They can only be used in a batch file script or command prompt.
Type SET and enter in a command prompt to see what you CAN use.
But I can add it for the next version anyway.

**Comment by whyfseeguy** [comment]
That will be great as there is no timestamp in the MQTT messages. I am using the MQTT messages in Home Assistant and it will be really useful to have the timestamp.

Thank you for the wonderful enhancements to the aitool.

**Comment by VorlonCD** [comment]
It should work in this version if you would like to test.
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5330198/AITOOL-VORLONCD.zip)
