### ISSUE TITLE
DRAW MASK

### ISSUE THREAD

**Issue by europer** [VorlonCD/bi-aidetection#51]
Hi,
first of all, thanks a fantastic effort!!!  👍 

I use your last version 1.81 relesed for some days ago, under draw mask I have one of my cam marked the pic since the AI thinks its persons but it just garden blubs so no problem to just mark this area. 
Since the last version some small problem in this draw mask:
1. the dra mask do not give me the full pic but just a part of it so that the mask is not more on the right place
2. the draw maks main frame with all its buttons is not full and when I drag the window out to see all it is not autmaticalyl refrecing  so that point 1 same problem and I dont see all buttons in main windows of draw mask. 

thanks in advance

**Comment by VorlonCD** [comment]
I think that is related to DPI or resolution changes after booting.   Try a reboot or edit AITOOL.EXE.CONFIG and make sure these two settings are configured to disable any high-dpi support:

<System.Windows.Forms.ApplicationConfigurationSection>
    
    <add key="**DpiAwareness**" value="**false**" />
    
    <add key="**EnableWindowsFormsHighDpiAutoResizing**" value="**false**" />
  </System.Windows.Forms.ApplicationConfigurationSection>

**Comment by europer** [comment]
thanks did work for me  :)

Here my setup in the aitool.exe.config file:
  <System.Windows.Forms.ApplicationConfigurationSection>
    <add key="DpiAwareness" value="false"/>
    <add key="EnableWindowsFormsHighDpiAutoResizing" value="false" />
  </System.Windows.Forms.ApplicationConfigurationSection>

**Comment by europer** [comment]
thanks did work for me  :)

Here my setup in the aitool.exe.config file:
  <System.Windows.Forms.ApplicationConfigurationSection>
    <add key="DpiAwareness" value="false"/>
    <add key="EnableWindowsFormsHighDpiAutoResizing" value="false" />
  </System.Windows.Forms.ApplicationConfigurationSection>

**Comment by europer** [comment]
strange, I cant see my text between <system.... and </system...here a screen shot
![Bild111](https://user-images.githubusercontent.com/44968296/95186228-0e526080-07ca-11eb-8104-b6fe077fc384.jpg)
