### ISSUE TITLE
Request - Database management/Purge History after n days

### ISSUE THREAD

**Issue by MissMusic** [VorlonCD/bi-aidetection#53]
With many cameras and a lot of triggers the history database takes a long time to load on startup and also slows down the GUI a lot.
Having the option to purge saved history data after x days would speed up a lot of things, at least in my setup.
History is only relevant for so many days back anyway. The stats could be more interesting over a longer time period, but maybe that data could be saved separately?

**Comment by Tinbum1** [comment]
Isn't here already a setting  in the json file "MaxHistoryAgeDays": 14,

**Comment by MissMusic** [comment]
@Tinbum1 Thanks!
The setting seems to be "MaxLogFileAgeDays" I searched for "history" and couldn't find it.

**Comment by Tinbum1** [comment]
Your perhaps not running the latest commits from yesterday which is already a lot faster.  
"MaxHistoryAgeDays": 14, is definitely a setting in that.
