### ISSUE TITLE
Feature Request: Option to hide annotation labels for irrelevant objects on history tab

### ISSUE THREAD

**Issue by aesterling** [VorlonCD/bi-aidetection#54]
I'd love the option to show annotations for only relevant objects on the history tab, and hide the annotations for irrelevant objects.

For example, my front doorbell camera can see lots of cars parked on the street and draws a box around each one, even though I don't have "Car" selected in the list of Relevant objects. Since there are so many car boxes, they can sometimes cover up the box drawn around a human, which I actually care to see. It'd be great to have to an option to show/hide the boxes and labels for irrelevant objects on the history tab images.

Hope that makes sense. Please let me know if this is already possible and I missed it.

**Comment by VorlonCD** [comment]
done. 
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5368043/AITOOL-VORLONCD.zip)

**Comment by aesterling** [comment]
Works great! Thank you!
