### ISSUE TITLE
Custom Masking - Unhandled exception error

### ISSUE THREAD

**Issue by MnM001** [VorlonCD/bi-aidetection#59]
Hi,

I am trying to draw some custom mask and when I try to save I get an error.

![image](https://user-images.githubusercontent.com/15014858/96073889-fb324580-0ed9-11eb-9a54-71e7ab554d3c.png)

This is happening for all the cameras. I cannot proceed to save any masks because of this.

Using version 

![image](https://user-images.githubusercontent.com/15014858/96073966-1dc45e80-0eda-11eb-8508-052805990b4e.png)

Virtual Windows 10 with latest patches applied.

Thanks

**Comment by petermai6655** [comment]
Same thing happened to me once. I didn't really figure out the problem, but I was able to get it working again my messing with the settings file and camera folder and transfering those files from an older version.

That didn't work on the first try either, so I can't 100 percent narrow down the problem.

**Comment by petermai6655** [comment]
I also tried other things like resetting the program, adding my cameras again, tinkering with various files, and it eventually worked.

In my case, it might've been a conflict/ corruption of my settings file and camera folder that caused the issue.

**Comment by classObject** [comment]
@MnM001 Your bmp file might be corrupt. Try deleting the *.bmp files from the cameras folder. Also, please click on the details  button of the exception and post the stack trace here so I can see a few more details. Thanks!  I will also add more logging to the save so we can capture more details as well.

**Comment by MnM001** [comment]
My bad guys. I thought all is done through the app and not needing the camera folder and the pics.
I have re-instated the camera folder and pics and all works as it should.
