### ISSUE TITLE
No image or box when looking at masks on some cameras

### ISSUE THREAD

**Issue by Tinbum1** [VorlonCD/bi-aidetection#6]
ShowImageMask> Error: Object reference not set to an instance of an object. [NullReferenceException] Mod: ShowImageMask(PaintEventArgs e) Line:85:21

When looking at the dynamic masks in cameras there is no image or box. Only occurring on some cameras.

**Comment by Tinbum1** [comment]
Images and boxes are now showing in the cameras that didn't show anything- could it possibly be because images are now shown in dynamic mask history box. I think the cameras that showed nothing had nothing in the history box..

**Comment by VorlonCD** [comment]
This will only happen if a camera has had no images to process within the current session, but fixed for next build.

**Comment by Tinbum1** [comment]
Great- thanks
