### ISSUE TITLE
custom mask - error

### ISSUE THREAD

**Issue by opa-rudi** [VorlonCD/bi-aidetection#66]
When I draw a custom mask an error message pops up when saving the mask (using current version).

System.Runtime.InteropServices.ExternalException (0x80004005): Allgemeiner Fehler in GDI+.
   bei System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   bei AITool.Frm_CustomMasking.btnSave_Click(Object sender, EventArgs e) in D:\Documents\Projects\_GIT\VorlonCD\bi-aidetection\src\UI\Frm_CustomMasking.cs:Zeile 376.
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by VorlonCD** [comment]
That general error might mean there is a permissions problem saving the bmp file.   Is it being saved in the CAMERAS subfolder?

The latest version will create a proper error LOG entry with the actual filename and error, and a few other things have been fixed for how it determines the right camera file to use.   If you would like to test:

[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5398010/AITOOL-VORLONCD.zip)

**Comment by opa-rudi** [comment]
I have only one main input folder. BI stores the snapshots from all cameras there. aitool takes a snapshot for the mask. but in the meantime BI has cleaned up all the files in the input dir. So aitool does not find the original masking image, right? So do I have to edit the aitools.settings "last_image_file" and set a custom image in a different folder to prevent deletion?

**Comment by VorlonCD** [comment]
AITOOL looks in \AITOOLS.EXE FOLDER\CAMERAS\CAMERANAME.BMP for the mask file.   Newer versions also fall back to \AITOOLS.CONFIG.JSON FOLDER\CAMERANAME.BMP

You should **not** keep aitools or custom mask image files in the same folder BI creates files in.

Last image file is only used as a background image while creating the mask, but the mask gets saved as CAMERANAME.BMP

**Comment by opa-rudi** [comment]
I manually created the folder "Cameras" inside AITool directory and now it creates the bmp for the specific cam and mask and the error has gone. Thank you for your support!

**Comment by Wumfie** [comment]
Thanks, the Cameras folder fixed it! Not sure why it wasn't there for me but thanks anyway.
