### ISSUE TITLE
History deletion

### ISSUE THREAD

**Issue by Tinbum1** [VorlonCD/bi-aidetection#7]
Is the History of objects found supposed to be removed from the list in Dynamic mask detail/History UI after the time set in settings/clear object history in x seconds?

(I'm also struggling to see the grey boxes on the image possibly change to yellow?).

**Comment by VorlonCD** [comment]
Yes, the setting for "Clear object history in xx minutes".  Think they also get removed if not detected for "Remove mask after xx times not visible".    Is it not working correctly?

See latest push notes for how to change the rectangle colors directly in the JSON settings file.

**Comment by Tinbum1** [comment]
Thanks,
My history doesn't seem to be getting deleted.

Many thanks for the color options- brilliant.

**Comment by classObject** [comment]
@Tinbum1  Does your history delete after a camera trigger even if it's past your time limit or does it never delete at all? The reason I ask is the clear history time is only checked after each trigger. If a history object was created at 6:00pm and it's set to delete after 5 mins but there has not been an activation in 1 hour, the object will still be in history.  The name is a little misleading when you can visually see the history now. . . but the results are the same.

**Comment by Tinbum1** [comment]
They don't ever delete. I have history from days ago. I have it set at 60mins and my cameras are set pretty sensitively so AITool  has a lot to do.

**Comment by classObject** [comment]
@Tinbum1 Okay, I believe I know your issue.  There was a bug with how object history gets saved and reloaded. I fixed it this afternoon. Can you build the lastest version to test? You will need to clear your old history before you start. Let me know how it goes.  By the way, 60mins is probably too long for history. It may cause a lot of false masks to get created especially in a sensitive zone.

**Comment by Tinbum1** [comment]
Thanks, Have done and will give it a try. Thanks for everything, this is a brilliant program.

**Comment by VorlonCD** [comment]
@classObject - would it make sense to use System.Threading.Timer in MaskManager.cs rather than relying on cleaning up only when a new image is processed?

**Comment by classObject** [comment]
@VorlonCD  As far as how MaskManager functions, it's essentially the same but I like the idea of a timer because less logic needs to execute during image processing.  I have it implemented but need to test a bit more before I push the changes.

**Comment by Tinbum1** [comment]
Works well. !!
