### ISSUE TITLE
MQTT [confidences] is returning list object

### ISSUE THREAD

**Issue by sstratoti** [VorlonCD/bi-aidetection#71]
When trying to use [confidences] in mqtt payload, it returns something like the following:

System.Collections.Generic.List`1[System.Single]

It displays this even when testing, or clicking the "Click here to see variable replacements" text.

**Comment by sstratoti** [comment]
Build is 1.81 btw. Thanks!

**Comment by VorlonCD** [comment]
It should have only done it on the action/test screen, not when actually being triggered.
but fixed.  How does this work?  (backup existing aitools folder first)
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5410632/AITOOL-VORLONCD.zip)

**Comment by MYeager1967** [comment]
I'm having an issue with the MQTT message not being sent to clear a detection.... Also, what is the newest release available and are all these features being carried forward? I absolutely love this program....

**Comment by VorlonCD** [comment]
Try the latest beta found attached to another recent issue thread from last night.  Make a backup copy of your entire AI folder first and overwrite with the new version.  Yes all features being carried forward.

**Comment by MYeager1967** [comment]
Will try this out this evening. I've been following the back and forth with gentlepumpkin and it looks to me like the two of you are making great advances on this project.

**Comment by MYeager1967** [comment]
Wow. That gives a LOT of logging data. The cancel topic is nice, but it used to simply send none to the same topic when there was nothing detected that was relevant. Not sure why things changed, but it doesn't matter really. :-)

**Comment by VorlonCD** [comment]
you have full control over what the cancel topic and payload is in camera actions dialog.   Also see this for a different approach with BI:  https://github.com/VorlonCD/bi-aidetection/blob/master/mqtt.md

**Comment by MYeager1967** [comment]
No, it's fine. I was just commenting on the fact that it used to send 'none' when there were no relevant detections. I'm perfectly ok with it either way.
