### ISSUE TITLE
Feature Request - Dynamic Mask remove after N non-detections

### ISSUE THREAD

**Issue by Matchlighter** [VorlonCD/bi-aidetection#72]
For background for this request, my assumption of how AITool works is as follows:
1. When an object is detected, log the detection (eg to a DB). (To be removed after `Clear object history in` minutes)
2. When the object is detected `Create mask after` times, add a mask (aka blackout the region-of-detection) via image manipulation on any future images before sending them to DeepStack.
3. After `Remove mask after` minutes, stop adding that mask/blackout to images.

My setup is mostly as defined on the Forum post - BI detects motion and starts saving off images that AITool then picks up and processes. If AITool sees something, it Triggers BI.

I'm however having trouble in cases where there's a parked car in the image and some other motion triggers the flow (and the time between detections is greater than `Remove mask after`). AITool sees and flags the parked car, even if the triggering event isn't actually something I'm interested in. I care about when the car parks, when it unparks, and if a human walks up to or away from the car sometime in the interim, but I don't care about the car if, eg, a cat walks across an entirely different part of the image.

I'm not seeing a current solution to solve this issue, but I'm foreseeing the following possible solution:
If my above assumptions are correct, would it be possible to skip step 2? Basically don't mask the image when sending it to DeepStack, but process the "mask" using the Object History after DeepStack has processed the full image. In my head this would create the opportunity for a "Remove 'mask'/object after N non-detections" option that, in a number of cases (and again in my head), would be a lot better at reducing false-positives.

I'd love to hear your thoughts and if I'm missing something in my thinking. My C# is a bit rusty, but if you don't have time/interest in implementing this, but are otherwise onboard, I may be able to recall/re-learn enough to do a PR with this feature.

**Comment by VorlonCD** [comment]
Try the latest beta to see if it works any better.  It has several updates to dynamic masking - It was not correctly removing masks.

https://github.com/VorlonCD/bi-aidetection/files/5419330/AITOOL-VORLONCD.zip

**Comment by MYeager1967** [comment]
I'm going to try this beta as well, but I have a question concerning the idea of dynamic masking. I have a few things in my yard that DeepStack identifies as people (my wife loves to decorate). I've been partly successful in using the dynamic mask feature but they don't stay masked. I currently have the timeouts set at 240 minutes and 100 missed detections. Am I on the wrong path for having them stay masked?

**Comment by VorlonCD** [comment]
@MYeager1967 yeah that should also be fixed.  You will see a few things have changed in the dynamic mask settings dialog.
Also, you could right-click the mask in Dynamic Mask Details the next time you see it and make it STATIC so it will always apply.

**Comment by MYeager1967** [comment]
What values should I be using to get decent results? Not sure I want to define it as static because then I have to remove it when she takes down her decorations. They don't stay too long. Is 240 minutes too long to retain? Also, under the active masks window, is the counter counting down to zero to clear the mask? That's my assumption, but you know what they say about assuming things. If I understand more about how it works, I'll be better able to tweak it. I see the time the mask was created and the time the object was last seen, so I'm certain that it's updating. 

So far, I'm not seeing any issues with this version... :-)

**Comment by VorlonCD** [comment]
@MYeager1967 - 5 hours seems high.    @classObject ? - he wrote this part of the code.  I'm at 30 mins and probably don't need it that high.   If you know that a small area/object will very commonly be detected, use the Mask Details screen right-click > Make Static.

**Comment by MYeager1967** [comment]
I have it set that long, that's the maximum time it seems to allow. Shouldn't the last seen time updating return the count to it's high level to begin counting down again?

**Comment by classObject** [comment]
@MYeager1967 How is your setup going? Let me answer your last few questions first.  

> If the object is seen again once the counter has reached zero but the mask is still in place, will it reset the counter?

If the counter hits zero and the “Remove mask after xx minutes” has elapsed, the object is flagged to delete. There is a cleanup process that runs every minute to remove any expired masks. If the count is zero and the object is visible again before the cleanup process runs, the counter is increased by one and the remove after time is reset.

>Shouldn't the last seen time updating return the count to it's high level to begin counting down again?

It will add one each time the object is visible until the counter hits it’s maximum value again.  The max value is set in the **xx detections** in the config option:  "Remove mask after xx minutes if object not visible in the last **XX detections.**"  The counter is increased by one each time the object is visible to help improve the accuracy of the masks.

>I think I'm figuring this dynamic mask out. Might need to go a little longer than the 5 hours 

5 hours is a very high number that kind of turns dynamic masks into static masks :)  I understand you are just testing.   My setup is “Remove mask after 2 minute if the object is not visible in the last 4 detections”  The default values should work in most cases but they might need some tweaking based on your lighting, distance, and activity levels.   Lighting is going to be one of the major factors when masks are removed too soon.  If it’s too dark at night the AI will not consistently detected the objects and they will be dropped.  On my todo list is to create a scheduling option so masks will not be removed during defined hours to help anyone with lighting issues.

**Comment by classObject** [comment]
@Matchlighter Have you had a chance to try new version @VorlonCD  suggested? I think this should solve your issues.
https://github.com/VorlonCD/bi-aidetection/files/5419330/AITOOL-VORLONCD.zip

>Basically don't mask the image when sending it to DeepStack, but process the "mask" using the Object History after DeepStack has processed the full image. In my head this would create the opportunity for a "Remove 'mask'/object after N non-detections" .

The image is always sent to DeepStack with out any masks. The masks are created after the image is processed. The lastest version has also has a feature to remove the mask after N detections.

![Screen Shot 2020-10-28 at 2 13 14 PM](https://user-images.githubusercontent.com/16977295/97485228-d9987b80-1927-11eb-93c1-bd6fb208e90f.png)

**Comment by Matchlighter** [comment]
I just updated today. It looks like it should indeed work, but haven't had a chance to play too much.

**Comment by MYeager1967** [comment]
It just keeps getting better. Great work!
