### ISSUE TITLE
[Feature Request] Confidence Limits for Actions

### ISSUE THREAD

**Issue by Wumfie** [VorlonCD/bi-aidetection#73]
Would it be possible to allow users to set Confidence Limits individually for each Action?

Lets say I have telegram, MQTT and Trigger URLs set up in the Actions pane. I would like the trigger URL to trigger with a lower confidence, just to be on the safe side so I dont miss any possible intruders. I would like telegram to trigger with a higher confidence so I dont wake up at 3AM with a false positive and maybe a lower confidence for MQTT to turn the lights on outside.

This would be a really cool feature to see. I could see it working if the main confidence limit was the only one that showed up as relevant in the History tab and the Actions menu worked seperately. Or maybe a preset system for Confidence Limits.

**Comment by Tinbum1** [comment]
I was also thinking possibly per type of item and possibly a day night setting. I find that DeepStack can often detect people where there are none especially at night, though the latest release does seem better. Thoughts?

**Comment by petermai6655** [comment]
@Tinbum1 I also experience the issue of random detections of people at night. Maybe DeepStack could be trained on detections at different lighting conditions?

**Comment by Wumfie** [comment]
Oops my comment never saved.

Yeah so I changed the streams to use full res images for the detection ai and it improved it massively. But still getting a sh*t tonne of false positives at night due to the black and white images.

My hope is that when the ai tools becomes open source in november, people start using much better datasets etc to improve the accuracy. At the moment the deepstack developers seem to care more about other things but the project is still far better than good old motion detection,

It would be really nice to see confidence limits for each individual action although i'm not sure how it would be implemented (what shows up on the history tab etc.)

**Comment by Tinbum1** [comment]
I've put my DeepStack up to high. Not sure if it makes a difference but the processing times between that and medium were not great so thought it's worth a try. Confidence limits of 60 - 100% seem to work well for me.

**Comment by Wumfie** [comment]
Does "high" improve the accuracy or is it the other way around?

**Comment by Tinbum1** [comment]
High improves accuracy but naturally takes longer.

**Comment by Wumfie** [comment]
On further thought, I think this would make more sense to handle throught something like NodeRED externally. While I think that everything to do with Day/Night confidences should stay, alerting me through telegram and turning on lights should really be handled through something external like NodeRED. I do agree more attention should be given to: 
[](https://github.com/VorlonCD/bi-aidetection/issues/74)
As this would allow me to send the client images through Home Assistant instead of blue iris, although back to the tolerances, I think that the day/night system is a good idea and that maybe have custom tolerances for the actions already built in. But at the moment im really considering using something more flexible like NodeRED.
