### ISSUE TITLE
Accessing the image through MQTT

### ISSUE THREAD

**Issue by vanheerdena** [VorlonCD/bi-aidetection#74]
Has anybody managed to pass the actual image data with the MQTT request. My MQTT server is on a raspberry pi and I cannot access the image using the filename and path as passed along in the parameters as it is on a different windows machine. I'm trying to work out how to get the image in Node-Red / Home Assistant when the MQTT triggers.

**Comment by Wumfie** [comment]
Could the ai input folder is set to a public webserver running on the blue iris machine, which the NodeRED is linked to gets the ImageName from the webserver and sends it to your phone?

**Comment by rhatguy** [comment]
I second this request.  Frigate publishes pictures over MQTT.  Its much easier to deal with in Hass.io than trying to get a CIFS share mounted as it can just be setup as a camera inside HA.

https://github.com/blakeblackshear/frigate#mqtt-topics
https://www.home-assistant.io/integrations/camera.mqtt/

**Comment by VorlonCD** [comment]
Ok folks, how is this working?   See 'Send Image' checkbox in Actions.   It will first send the regular payload, then the image.  Let me know if only sending one is more appropriate.  If other apps send both in one message I'll have to figure that out.
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5505609/AITOOL-VORLONCD.zip)

**Comment by rhatguy** [comment]
Seems to be working great.  I'm able to pick up the image in HomeAssistant via MQTT.  It seems a bit odd that the payload and the picture would come in through the same MQTT topic, but it seems to work.  I guess the camera in HA would get the initial payload packet and probably fail to update the picture based on it, then immediately get the picture and update successfully.

Would it be possible to publish the pictures into topics based on what was detected?  Maybe something like the topics below.  This would allow someone to easily setup a latest detection for particular objects, or just the latest detection for any object.  I'm assuming latest would be updated anytime an event is triggered and then at least one, possibly more) sub topics (car, person, ..etc) would also be updated based on what was detected.
/ai/driveway_cam/person/snapshot
/ai/driveway_cam/car/snapshot
/ai/driveway_cam/latest/snapshot

Thanks for your awesome work on this.  This entire project is HUGELY beneficial!


![ai](https://user-images.githubusercontent.com/11964411/98453780-f3597000-212a-11eb-9140-e34b381c3100.JPG)

**Comment by VorlonCD** [comment]
This version should send the payload and image in one message:
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5506907/AITOOL-VORLONCD.zip)

**Comment by VorlonCD** [comment]
Let me know if the last version is still behaving as expected.   Should be one message now.

**Comment by kuradi** [comment]
> This version should send the payload and image in one message:
> [AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5506907/AITOOL-VORLONCD.zip)

its working and sending image but there is no payload. would be possible to keep payload topic as it is and for image a'la ai/[camera]/motion/image ?

**Comment by VorlonCD** [comment]
Still not sure if I got it right, but here is how it behaves now - If you check the send image box AND you have a topic that contains /image, then it will send it.    So this should work and give you a little more control:

Topic:
/topic1/blah **|** /ai/[camera]/image
Payload:
[something] **|** [somethingelse]

Putting in a second payload is needed in this case even though the actual payload will be the image file, not the text payload.

Let me know if there is a better way of handling this - I dont have MQTT set up to play with on my end.
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5520604/AITOOL-VORLONCD.zip)

**Comment by kuradi** [comment]
i have set up mqtt as follows:
topic:
/ai/[camera]/motion | /ai/[camera]/image
payload:
{ "Kaamera": "[Camera]", "Summary": "[Summary]", "Confidence": "[Confidence]" | payload

and im receiving in both topics image and no other data.
![image](https://user-images.githubusercontent.com/31483391/98748841-2fa6fd80-23c3-11eb-9c29-76975c075bac.jpg)

**Comment by VorlonCD** [comment]
@kuradi - I dont think you have the latest?   Try this.
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5524368/AITOOL-VORLONCD.zip)

**Comment by kuradi** [comment]
> @kuradi - I dont think you have the latest? Try this.
> [AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5524368/AITOOL-VORLONCD.zip)

oh yesssssss. yeah its working :)

**Comment by rhatguy** [comment]
Testing with the newer version now.  Is it expected that AITOOL would send MQTT the cancel topic every time it tests an image whether or not the trigger topic was previously triggered?  The log on my MQTT server has an almost constant stream of cancel triggers since I have the motion detection on BlueIris set on a hair trigger to ensure I get even the smallest amount of motion over to AITOOL to run detection against.  I would expect the cancel topic to only be triggered if the trigger was previously set.  That may not be the way it was designed, but just what I was assuming I would see.

**Comment by VorlonCD** [comment]
Thats the same way that the cancel URL works.   Just remove the MQTT cancel topic/payload if you dont want it sent.

Maybe cancel should work differently? Normally you dont send a cancel - just rely on BI's "End trigger unless re-triggered within xx seconds" to stop recording.  But if you are for example using MQTT to turn on a light with motion, then turn it off with no motion that would take a bit of re-architecture to accomplish.  Someone else mentioned they solved it by passing the message through NodeRed since you can set a timer in there.

**Comment by rhatguy** [comment]
Any idea what these messages are?  I don't get them every time an event fires, but I seem to get multiple per day.  Is there something that might be cancelling the async event to send the cancel message?

MQTT: Unexpected Topic ai/Backyard_sd/motioncancel cancel Payload cancel: The operation was canceled. (Operation CanceledException Mod: <<PublishAsyncb_0>d Line 313:45

**Comment by VorlonCD** [comment]
This version fixes that
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5540990/AITOOL-VORLONCD.zip)

**Comment by davide169** [comment]
I'm using this latest version as I wanted access to the images via mqtt but running into an issue.  Before I go playing around with the other versions is there any chance this version is ignoring the object detection settings?  I have them checked and I checked the json config file and they are all there, but still getting notifications for potted plants.

**Comment by sankeerthb** [comment]
@VorlonCD  - thanks for the version fix.  This fixed a lot of issues I was having. 
@vanheerdena @rhatguy  - if possible, can you please share the node-red flow export. I'm trying to cast image onto google cast tv in homeassistant.

**Comment by MagicMountainMan** [comment]
@sankeerthb @vanheerdena @rhatguy I'd also really appreciate if one of you were able to share your Node-Red flow as I'm not able to get the image working. Trying to get the actual detected image displayed in Home Assistant. Thanks!

**Comment by VorlonCD** [comment]
@Tinbum1?

**Comment by sankeerthb** [comment]
@MagicMountainMan  My Usecase is - From my ONVIF Front Doorbell Camera - only for Person detections - Cast as Image to my Sony TV that as inBuilt Chromecast and do more automation. So far, can get detection data from topic - /ai/[camera]/, for the image - I'm working on the topic - /ai/[camera]/image. I'm not successful yet. Maybe write using file out and use cast node. 

@VorlonCD - the latest GA release I see is from Oct. I'm using the AI Tool Ver 2.0.150.7623 built 11/14/20 12:28:31AM posted above. Any other recommended version.

**Comment by Tinbum1** [comment]
'Sorry, I use node red to control my flood lights and don't use an image so cant help.

**Comment by MagicMountainMan** [comment]
So I actually got it to work. I created a MQTT Camera in my configuration.yaml file and (in my use case) I call a screenshot of the 'camera' and send that off as a picture notification to my phone.

**Comment by WhiteNoseThunderPants** [comment]
> 
> 
> So I actually got it to work. I created a MQTT Camera in my configuration.yaml file and (in my use case) I call a screenshot of the 'camera' and send that off as a picture notification to my phone.

@MagicMountainMan could you explain a bit more how you did this?

**Comment by MagicMountainMan** [comment]
@WhiteNoseThunderPants I have this as a camera in configuration.yaml and I followed [this](https://www.home-assistant.io/integrations/camera.mqtt/) documentation.
```
camera:
  - platform: mqtt
    topic: "ai/Front/image"
    name: AI Snapshop Front Camera
```

I use Node-Red and use a service call of camera.snapshot using [this](https://companion.home-assistant.io/docs/notifications/notification-attachments) documentation and including ``{ "filename": "/config/www/images/snapshot_front_camera.jpg" }`` in Node-Red. The snapshot is stored in a directory that is reachable by Home Assistant externally so it's able to pass that file off to a notification that gets sent to my phone.

Having the actual snapshot of the image that actually set off the person detection is really nice as I used to just call a snapshot _after_ Blue Iris had triggered the recording, which almost always missed the person.

**Comment by sankeerthb** [comment]
@MagicMountainMan just a curious question - why creating a MQTT camera, taking a snapshot again, and sending to the phone, The AI-Tool above can directly send the actual detected image with [detections] to Telegram. I have mine sent to a group and the alerts are almost instantaneous for me.

**Comment by MagicMountainMan** [comment]
@sankeerthb I don't want to get notified if it's someone that lives in my house that sets it off. By ingesting the image into Home Assistant I am able to control when I do and don't get notifications. Ex: The front door was just opened because I went to go get the mail, I don't want a notification of me getting the mail.

That's all, just more control so I don't get spammed with pictures of myself or other people in my household.
