### ISSUE TITLE
Crash on doing draw mask custom 

### ISSUE THREAD

**Issue by scadaguru** [VorlonCD/bi-aidetection#75]
I am getting application crash every time when I try to draw custom mask for any camera. I have tried rectangle and/or brash both causes crash when I click ok button on "Custom masking" screen 

![image](https://user-images.githubusercontent.com/46497683/97209918-e5027000-178a-11eb-90c7-300a44e95704.png)

**Comment by Tinbum1** [comment]
I think this has already been covered here. Take a look at past posts.

**Comment by classObject** [comment]
@scadaguru  Please take a look at post: https://github.com/VorlonCD/bi-aidetection/issues/66
Let us know if this solves your issue.

**Comment by scadaguru** [comment]
@Tinbum1 and @classObject thank you so much the reply.
I checked other post and found out that I had no camera folder and once I created error is gone now!
Thanks a lot once again!
