### ISSUE TITLE
Dynamic masking - nothing created

### ISSUE THREAD

**Issue by MnM001** [VorlonCD/bi-aidetection#77]
Hi,

I am using the latest version available (1.81)

I have enabled dynamic masking.
I have a car in the driveway and I thought that a dynamic mask will be created for that.
However, nothing gets created. My settings are:

![image](https://user-images.githubusercontent.com/15014858/97455083-6a944480-1972-11eb-97ac-60e857c145d1.png)

![image](https://user-images.githubusercontent.com/15014858/97455155-7ed84180-1972-11eb-913f-c532c7b36c6b.png)

Not sure if I need to do anything more than the above to enable dynamic masking and have them created.
Is there a specific folder required? Should I have specific images? etc..

I also get this in the logs (which makes me think that is not the case of just enabling dynamic masking via some tick boxes - done some looking around but could not find anything to show what I am doing wrong)

[22:57:27.559]:             GetBestImage> INFO: Mask image file path was blank or NULL. Defaulting to last processed image
[22:57:27.560]:             GetBestImage> (Found image from -last- detected object: D:\AIAlertsNew\Cam8AI.20201028_192801149.jpg)

Thanks

**Comment by VorlonCD** [comment]
That is fixed in the latest beta.   https://github.com/VorlonCD/bi-aidetection/files/5419330/AITOOL-VORLONCD.zip

**Comment by MnM001** [comment]
Thanks - that seem to have fixed it.

What I have noticed in this version is that in the history tab same event is listed multiple times - 2/3/4/5 and even 6 times sometimes.

![image](https://user-images.githubusercontent.com/15014858/97650437-a0314e80-1a94-11eb-82fe-9c331fdca5cb.png)

**Comment by aesterling** [comment]
> Thanks - that seem to have fixed it.
> 
> 
> 
> What I have noticed in this version is that in the history tab same event is listed multiple times - 2/3/4/5 and even 6 times sometimes.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/15014858/97650437-a0314e80-1a94-11eb-82fe-9c331fdca5cb.png)
> 
> 

I've seen similar behavior with multiple identical entries. I'll pay closer attention to it now.

**Comment by Tinbum1** [comment]
It's a bug but nothing to worry about. Chris has fixed it in later commits.
