### ISSUE TITLE
BI crashes when adding &jpeg=g:\alertimages to trigger url

### ISSUE THREAD

**Issue by wilddoktor** [VorlonCD/bi-aidetection#78]
There are 3 things going on here, so I'm not really sure which is causing BI to crash. But in aitool - cameras - actions - settings, I set the following:

Merge Annotations Into Images
Copy Alert images to folder g:\AlertImages [ImageFilenameNoExt]
Add &jpeg=g:\alertimages to trigger url

Then I click Test, and BI crashes. BI also crashes if I copy that trigger url and paste it into a browser.

**Comment by aesterling** [comment]
Try using &jpeg=[ImagePathEscaped] in AI Tool instead. [ImagePathEscaped] will remove spaces etc that aren't "URL friendly." Make sure you're running a recent build of AI Tool that supports it.

**Comment by wilddoktor** [comment]
Thanks @aesterling; that did the trick! I'm finally getting closer to having this thing work as expected!
