### ISSUE TITLE
Create Global Variables for User/Password

### ISSUE THREAD

**Issue by doudar** [VorlonCD/bi-aidetection#79]
Camera setup would be pretty much a two click process if the main application settings included input fields for Username and Password. 

Then all of my camera actions could be left at the new default of `http://[serverIP]/admin?trigger&camera=[camera]&user=[user]&pw=[password]&flagalert=1&memo=[summary]`

vs having to manually edit the current:

`http://[serverIP]/admin?trigger&camera=[camera]&user=ENTERUSERNAME&pw=ENTERPASSWORD&flagalert=1&memo=[summary]`

**Comment by VorlonCD** [comment]
Agree, I want to add that in eventually.   But note the new "Apply To" button that lets you copy the settings to any other camera.

**Comment by doudar** [comment]
Roger, Roger . :)

**Comment by VorlonCD** [comment]
Done.  [Username] and [Password] use Settings tab > Default Credentials settings.

[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5469831/AITOOL-VORLONCD.zip)

**Comment by doudar** [comment]
Wow! Nice!
