### ISSUE TITLE
Feature request: MQTT support

### ISSUE THREAD

**Issue by packetwarrior** [VorlonCD/bi-aidetection#8]
Would love to see MQTT as an alerting option, including the metadata in the payload.

Right now, I'm using EventGhost to translate alerts to MQTT, but this would be much more efficient.

Keep up the great work!

**Comment by VorlonCD** [comment]
I've never used it, can you provide more detail and examples?   Would it need to support AUTH TLS like blue iris?

**Comment by packetwarrior** [comment]
MQTT follows the Publisher/Subscriber model, with the messages organized in topics.  In case of alerting, only the subscriber portion matters.

Check out https://mosquitto.org which even discusses how you can use their test setup to validate your components are working.  From what I can tell, most of the applications I use actually rely on the [Mosquitto libraries](https://mosquitto.org/) to do all the heavy lifting, which is all open source.

Ideally, authentication should be supported, and if possible TLS as well (which should be easier when using the Mosquitto libraries).

**Comment by VorlonCD** [comment]
what does your topic/payload look like?

**Comment by packetwarrior** [comment]
Hopefully these examples make sense:

**AI Tool as a Subscriber** (via EventGhost right now):
**topic**: hostname_eg/aitool/driveway/motion
**payload**: [parameters]

**Blue Iris as a Publisher** (alert):
**topic**: hostname_bi/c_driveway
**payload**: 0 or 1 _(motion started vs stopped)_

**Blue Iris as a Subscriber**
Example of my home automation triggering Blue Iris to record the driveway camera
**topic**: hostname_bi/admin
**payload**: camera=driveway&trigger&memo=garage_door

**Comment by VorlonCD** [comment]
Ok, I expect issues since I havent tested, even with mosquitto, but try dis
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5178878/AITOOL-VORLONCD.zip)

**Comment by packetwarrior** [comment]
wow, that was fast!  Before I continue, please take the file offline, it has some extra data that shouldn't be public.

I didn't have much time to test this, but the first run didn't trigger.  After it processed the first pic, the log showed it saved the settings again, which removed the MQTT entries (probably because there's no GUI entry for them?).

I'll do some more testing tomorrow, but your work is very much appreciated!

**Comment by packetwarrior** [comment]
@VorlonCD  You'll remove the file from the server (or from your editing history), sorry for trouble.

**Comment by VorlonCD** [comment]
Thanks! I removed it last night.   Someone would have needed to be able to find my external IP to make use anyway.

So you would have to edit the mqtt settings in the JSON file when the program is NOT running, otherwise it would have overwritten the settings you manually edited.

I'll need logs if still not working as expected. (stripped of any passwords of course :)

**Comment by VorlonCD** [comment]
I fixed a few MQTT related bugs that certainly would have stopped it from working on your end, but I'm still having a hard time testing - not exactly sure what is expected, and the test servers keep giving 'unable to connect to the remote server' (maybe I abused them or have too many connections) - iot.eclipse.org, broker.hivemq.com, test.mosquitto.org.  Using default port of 1883.

In the new version, see camera > settings > MQTT > Settings screen, and the TEST button

[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5180234/AITOOL-VORLONCD.zip)

**Comment by packetwarrior** [comment]
Alright major progress for sure!

* The Test button in the MQTT Settings dialog box works perfectly (shows [camera] as payload, but that makes sense).
* When I throw a new pic in the directory, it triggers the MQTT alert (so connection's good), however it's being posted to the / topic, and the payload is the content of Params from the previous "Run external program" option, so probably just a bad variable reference?

I did test the test.mosquitto.org server with my MQTT client, which works, but there were so many topics posted, it took a few minutes to load.  Check out https://www.hivemq.com/mqtt-toolbox/ for some of the popular clients.

**Comment by VorlonCD** [comment]
How is this working?  (The test screen will still not resolve [camera] etc)

[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5184040/AITOOL-VORLONCD.zip)

**Comment by packetwarrior** [comment]
Unfortunately, same behavior.  For testing purposes, I saved the settings again, but changed the (disabled) run external program 'Params' text box to the literal string "params value".  In the logs below, you can see it's using that value for both the topic and payload content.
```
[15:38:45.840]:            DetectObjects> x.x.x.x:5000 - The summary:car (99.42%)
[15:38:45.844]:            DetectObjects> x.x.x.x:5000 - (5/6) Performing alert actions:
[15:38:45.846]:                  Trigger>    Copying image to network folder...
[15:38:45.852]:                  Trigger>    -> Image copied to network folder.
[15:38:45.856]:             PublishAsync> MQTT: Sending topic 'params value' with payload 'params value' to server 'mqtt.server:1883'...
[15:38:45.862]:             PublishAsync> MQTT: ### CONNECTED WITH SERVER 'mqtt.server:1883' ### - Result: Success, ''
[15:38:45.868]:             PublishAsync> MQTT: ### SUBSCRIBED to topic 'params value'
[15:38:45.888]:             PublishAsync> MQTT: ...Sent in 31ms, Reason: 'Success' (0 - '')
```

**Comment by VorlonCD** [comment]
Driving me buggy, I dont see any bad variable references.  :)  I can change topic and payload in actions and it sticks.

What if you make sure AITOOL.EXE has been fully closed, then edit AITOOL.SETTINGS.JSON file for the camera in question:

       "Action_mqtt_topic": "topic",
        "Action_mqtt_payload": "payload",

**Comment by packetwarrior** [comment]
The settings are sticking fine (no service configured, and I wouldn't be able to overwrite the executable if it was still running), it's just not using them.  This is pulled from my Settings file, which the UI also reflects:

```
"Action_mqtt_enabled": true,
"Action_mqtt_topic": "ai/[camera]/motion",
"Action_mqtt_payload": "[detections]",
"Action_mqtt_retain_message": false,
```

**Comment by VorlonCD** [comment]
See if this guy is working any better for you.
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5192218/AITOOL-VORLONCD.zip)

**Comment by packetwarrior** [comment]
I think we have a winner here, initial testing looks really good, will do some more checking tomorrow.  In theory, one could also control Blue Iris now, without having to deal with Trigger URLs and web server configuration issues.

Thank you very much for all the extra effort you're putting into this, I know debugging these seemingly minor issues can be a major headache.  Great job!

**Comment by ccmacaluso** [comment]
This featureset would be AMAZING if we could get it into the next release of AITool. Let me know if I can help to test.

**Comment by VorlonCD** [comment]
@ccmacaluso  Try it.  Its in the latest release:
https://github.com/VorlonCD/bi-aidetection/releases

**Comment by edalquist** [comment]
Verified this works for me as well, thanks for adding it!

**Comment by willngogit** [comment]
just stumbled on this fork, awesome work!  quick request, currently, MQTT only fires when there a relevant alert.  Can you make it configurable where it would fire when there's no relevant objects as well?  I'm planning to use this as an occupancy sensor.  it would be good to do a check to make sure there are no persons in the room before turning off the lights.

**Comment by VorlonCD** [comment]
@willngogit - Done.

https://github.com/VorlonCD/bi-aidetection/releases

**Comment by willngogit** [comment]
Wow.. that was quick!

**Comment by VorlonCD** [comment]
@willngogit - tiny bug fix if you already downloaded, re-download.

**Comment by willngogit** [comment]
> @willngogit - tiny bug fix if you already downloaded, re-download.

re-downloaded.  seems to be working.  thanks!

**Comment by VorlonCD** [comment]
This version will use the "Last Will" feature of MQTT.   When it first connects it will send a LWT "**AITool/status**" topic with payload of "**Offline**".   So you should see that message if AITOOL ever crashes and you are using MQTT.    When it connects it now sends "Online" to the same topic.   If you want to change this, close the program, edit AITOOL.SETTINGS.JSON and change "**mqtt_LastWillTopic**" and "**Mqtt_LastWillPayload**" settings.

[AITool-VorlonCD-v2.0.569.zip](https://github.com/VorlonCD/bi-aidetection/files/5826993/AITool-VorlonCD-v2.0.569.zip)

Let me know how it works.
