### ISSUE TITLE
Deepstack 'tab' missing?

### ISSUE THREAD

**Issue by cwhett** [VorlonCD/bi-aidetection#80]
Apologies if this is something stupid on my end, but the AITool main header tab area is missing the "deepstack" tab. I am unsure what is causing this. I have tried using the previous 3 versions of the tool, and I currently am using v2.0 released 3 days ago.

Here are some details in case it matters.

![image](https://user-images.githubusercontent.com/12661865/97876761-43c76c80-1cea-11eb-8ab8-cf63bbe8966e.png)

![image](https://user-images.githubusercontent.com/12661865/97876818-5a6dc380-1cea-11eb-9c05-802bb8e4310f.png)

As you can see, the 'Deepstack' tab itself is missing. I have never been able to see this tab. I am assuming that is the correct area to go so that I can configure multiple servers in order to have backup deepstack ai running in case of single server downtime. I am having issues where if the AITool can't reach the server for 5 tries it just stops trying to send and builds up an infinite queue until I restart the tool. Is there a way to fix this outside of the deepstack tab?

So I guess my questions are:

1.  Should I be seeing a Deepstack tab?
2.  Is that tab where I can set multiple deepstack servers up?
3.  Is that tab where I can set behavior for the AITool if one server has 5 request failures so I don't get a queue buildup and the message the the tool is no longer trying to transmit to the server?
4.  How is the program supposed to handle a server being offline and then eventually coming back online?

Any help would be appreciated! Sorry if this is not the right way to request help I am new to this.

**Comment by VorlonCD** [comment]
The deepstack tab is currently only for the WINDOWS version of Deepstack.    If Windows Deepstack is not installed (manually, by you), the tab will not show.   If you are using the DOCKER version of Deepstack (_**preferred**_) you dont need the tab.  See docker references on the first post for AITOOL on ipcamtalk, and throughout.   The docker version of deepstack is  more recent than windows and is much faster.

If you install deepstack docker version on multiple machines, then you simply reference "server1:port1 **;** server2:port2 ;" etc for the "Deepstack url's" setting.

The primary reason to have multiple deepstack servers is to be able to keep up with a lot of images being generated by multiple cameras.

If a deepstack url fails 5 times it will be disabled.    Then every 60 minutes, the url will be re-enabled and tried again.

**Comment by cwhett** [comment]
Thanks for your fast reply! This project is incredible.

Ok, so for our setup Windows Server is running the AITool with an external Deepstack server running Linux / Docker with deepstack:gpu. In this setup, as you've described, the Deepstack tab is not available and that is correct - I will close this issue.

We have about 30 cameras at this facility and I'm trying to see how extensible I can make this. Is there a way to lower the cooldown for retry of the URL? Or is that a hard coded 60 minute value.

**Comment by VorlonCD** [comment]
Not hard coded - There are a few settings for that in aitool.settings.json - close the app before modifying
