### ISSUE TITLE
AI suddenly stop processing image

### ISSUE THREAD

**Issue by heretocopycode** [VorlonCD/bi-aidetection#82]
I dont know what happen, but AI stop processing image from AI Input Folder

**Comment by VorlonCD** [comment]
When the input folder is on a remote nas or server the network connection will be unstable.   This version will do a better job at trying to re-connect every 5 mins if it failed.
[AITool-VorlonCD-v2.0.700.zip](https://github.com/VorlonCD/bi-aidetection/files/5978621/AITool-VorlonCD-v2.0.700.zip)
