### ISSUE TITLE
[Feature Request] Only add specific identification to summary

### ISSUE THREAD

**Issue by ncrispi** [VorlonCD/bi-aidetection#84]
AI is adding identification of couch, plants, etc into the summary of the video within BI. It would be good to be able to limit the summary to only include specific identification such as Person, Dog, Cat, etc.

**Comment by VorlonCD** [comment]
It already can - either use "[Detection] [Confidence]" variables which will limit to the FIRST detection which is always relevant, or enable History tab > Show only relevant objects.   This will prevent irrelevant objects from appearing in the UI, summary, etc.

**Comment by ncrispi** [comment]
I'm referring to the alerts tab within BI. Under the time, it updates the summary with anything it finds. Currently, it is finding things like train and toilet which are false and I don't care about them. It would be good to exclude those from transferring into BI and being able to only include specific tags like People, Dogs. I don't want to adjust the confidence as the confidence for those is ~45% and people are sometimes around that confidence as well.

**Comment by VorlonCD** [comment]
Right, I believe both of the options I gave will prevent BI from showing what is not relevant.   That info is passed with the @memo=[summary] part of the BI url.   You could replace that with [Detection] [Confidence] or turn off the Show Only Relevant Objects checkbox on history tab.

**Comment by ncrispi** [comment]
Okay; I got that working! Is there a way now to add the memo into the blue Iris push notification that you are aware of? When I try typing &memo into BI alerts, it doesn’t work

**Comment by VorlonCD** [comment]
memo works.   This is what i have on the end of my url:
**&flagalert=1&memo=[summary]&jpeg=[ImagePathEscaped]**
You may need a relatively recent version of BI for all of those settings to work.
Also, you are not allowed to have spaces in the URL, so if you are using:
**&flagalert=1&memo=[Detection] [Confidence]&jpeg=[ImagePathEscaped]**
It needs to have its spaces converted to %20 like this:
**&flagalert=1&memo=[Detection]%20[Confidence]&jpeg=[ImagePathEscaped]**

**Comment by ncrispi** [comment]
That pushes it over to BI memo, but how would I add that memo into the actual blue Iris push notification? That is where I’m stuck

**Comment by ncrispi** [comment]
As an example, in AI Tools I have: '&flagalert=1&memo=[Detection]%20[Confidence]&jpeg=[ImagePathEscaped]
That seems to push the detection and confidence into the clip memo

In Blue Iris: under Alerts I have:
''&CAM' (&TYPE) triggered on '&SERVER' at %X'

How would I add the memo portion into the BI push notification alert?

**Comment by VorlonCD** [comment]
I haven't looked into that side of things.  You would have to dig around the BI manual and maybe log a support case with them.  
https://blueirissoftware.com/BlueIris.PDF

**Comment by iceman73** [comment]
> As an example, in AI Tools I have: '&flagalert=1&memo=[Detection]%20[Confidence]&jpeg=[ImagePathEscaped]
> That seems to push the detection and confidence into the clip memo
> 
> In Blue Iris: under Alerts I have:
> ''&CAM' (&TYPE) triggered on '&SERVER' at %X'
> 
> How would I add the memo portion into the BI push notification alert? Right now when I get push notifications, it just says
> 'FrontCamera' (EXTERNAL) triggered on 'Video' at 11:58 AM
> 
> I am trying to get it to say:
> **[Memo]** seen at 'FrontCamera' (EXTERNAL) triggered on 'Video' at 11:58 AM
> **Person 56%** seen at 'FrontCamera' (EXTERNAL) triggered on 'Video' at 11:58 AM

From what I have researched in the BI manual, this is currently not possible, looks like we need to open a feature Request with Ken at Blue Iris.

**Comment by ncrispi** [comment]
> > As an example, in AI Tools I have: '&flagalert=1&memo=[Detection]%20[Confidence]&jpeg=[ImagePathEscaped]
> > That seems to push the detection and confidence into the clip memo
> > In Blue Iris: under Alerts I have:
> > ''&CAM' (&TYPE) triggered on '&SERVER' at %X'
> > How would I add the memo portion into the BI push notification alert? Right now when I get push notifications, it just says
> > 'FrontCamera' (EXTERNAL) triggered on 'Video' at 11:58 AM
> > I am trying to get it to say:
> > **[Memo]** seen at 'FrontCamera' (EXTERNAL) triggered on 'Video' at 11:58 AM
> > **Person 56%** seen at 'FrontCamera' (EXTERNAL) triggered on 'Video' at 11:58 AM
> 
> From what I have researched in the BI manual, this is currently not possible, looks like we need to open a feature Request with Ken at Blue Iris.

Someone mentioned that if you connect to HA and RED for alerts then you can have additional customization and include the detection and confidence. I am going to try that in the next week or two and see if that helps.

**Comment by aesterling** [comment]
@ncrispi is this what you're trying to do?

![IMG_97460EC95C9E-1](https://user-images.githubusercontent.com/18314707/98754346-1b93d980-238c-11eb-956a-6e989f5435bb.jpeg)

If so, I'm accomplishing it like with this:
![Screen Shot 2020-11-10 at 07 35 11 PM@2x](https://user-images.githubusercontent.com/18314707/98754431-50079580-238c-11eb-8504-51e2bd20b4f2.png)

**Comment by ncrispi** [comment]
> @ncrispi is this what you're trying to do?
> 
> ![IMG_97460EC95C9E-1](https://user-images.githubusercontent.com/18314707/98754346-1b93d980-238c-11eb-956a-6e989f5435bb.jpeg)
> 
> If so, I'm getting it with this:
> 
> ![Screen Shot 2020-11-10 at 07 35 11 PM@2x](https://user-images.githubusercontent.com/18314707/98754431-50079580-238c-11eb-8504-51e2bd20b4f2.png)

Omg thank you!! I could swear that I tried &Memo before... maybe because it was not all caps, it did not work.

THANK YOU!

**Comment by ncrispi** [comment]
@aesterling - One additional question, and not sure if you know the answer, but are you aware of how to do a linebreak with Blue Iris push notifications. I am trying to always have memo on a new line for the push notifications.

**Comment by aesterling** [comment]
Good question. Not sure. I think it was just coincidental in my screenshot, but that'd be cool to specify.
