### ISSUE TITLE
Image Queue Time

### ISSUE THREAD

**Issue by InTheAir17** [VorlonCD/bi-aidetection#87]
Hi,
First off.... love this tool, it has really reduced my false alarms. Since I saw that DeepStack has released a new version I thought I would try it on my license plate (LPR) camera again. I setup a Photon VM with DeepStack in low mode, which is awesome because it responds in around 100ms (from the DeepStack log). What I'm trying to figure out is why the image queue time is high. Below is a typical entry from the AI Tool log.

Total Time:  450ms (Count=396, Min=336ms, Max=813ms, Avg=426ms)|8164|4||19
DeepStack (URL) Time:  143ms (Count=396, Min=65ms, Max=435ms, Avg=99ms)|8165|5||19
File lock Time:  0ms (Count=3, Min=1ms, Max=106ms, Avg=66ms)|8166|5||19
**Image Queue Time**:  **293ms** (Count=396, Min=253ms, Max=387ms, Avg=315ms)|8167|5||19
Image Queue Depth:  1 (Count=396, Min=1, Max=1, Avg=1)|8168|5||19

What is "Image Queue Time" and how can I reduce it? Since the LPR camera is somewhat zoomed in the car isn't in the frame for much more than a second or so, of course this depends on the speed of the car.

Thanks!

**Comment by VorlonCD** [comment]
That is the time from when AITOOL detects the image and puts it in the queue to the time it actually STARTS being processed by deepstack.   I wouldnt call it a bug, but I do see I put in a 250ms delay on purpose as sort of a short cooldown for the deepstack server.   But I dont think its really needed so I'll take it out for the next release.

**Comment by VorlonCD** [comment]
Should be fixed with this one - Let me know.
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5505634/AITOOL-VORLONCD.zip)

**Comment by InTheAir17** [comment]
That did it. Total time is averaging 200ms. Thank-you.
