### ISSUE TITLE
Feature Request: Gracefully close AITool at server / system reboot

### ISSUE THREAD

**Issue by MelvinRC** [VorlonCD/bi-aidetection#89]
First of all, I really appreciate your fork and great work! 

Feature Request: Gracefully close AITool at server / system reboot, now AITool is preventing the system from restarting:

![image](https://user-images.githubusercontent.com/73360301/98464675-d5404e00-21c4-11eb-8cc1-a9d21740bb92.png)

If you choose force restart or Windows has installed some updates the AI Tool shows an error in the log:
"Program did not shutdown gracefully.  Last log entry was 'not set', 'checkpoint: HistoryUpdateTimer: 8-11-2020 13:27:06"

**Comment by petermai6655** [comment]
I schedule a restart of my computer everyday, and I also experience the same issue. I have to force restart, and the same error appears in the log.

**Comment by VorlonCD** [comment]
This one working any better?    I think the DO YOU WANT TO QUIT YES/NO question when you exit was holding it up.
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5506907/AITOOL-VORLONCD.zip)

**Comment by MelvinRC** [comment]
@VorlonCD perfect! Now the system restarts without questions, and after reboot the AITool starts without any error in the logging. 

![image](https://user-images.githubusercontent.com/73360301/98489593-f178d500-222e-11eb-9965-b1a6c265cdb0.png)

Thanks for your lightning fast support =) and keep up the great work!

Greetz,
Melvin
