### ISSUE TITLE
Feature Request: include match data (car, cat, ...) in program parameter

### ISSUE THREAD

**Issue by packetwarrior** [VorlonCD/bi-aidetection#9]
Slightly related to my previous request.  I'm using the 'Run external program option' with parameters, but unless I'm seeing something, I don't see a way of including the match results in a parameter.  Example:

program.exe -parameter1 %objects%

Which would include all the detected objects as a (JSON) string.  Would love to see this feature, and hopefully isn't too difficult to implement.

**Comment by VorlonCD** [comment]
The same variables you can use in the URL string can be used with run parameters:
[camera], [imagepath], [imagefilename], [summary], [detection], [position], [confidence], [detections], [confidences]

**Comment by packetwarrior** [comment]
Fantastic, thanks for the quick response!
