### ISSUE TITLE
Feature Request:  make cooldown time in seconds rather than minutes

### ISSUE THREAD

**Issue by MnM001** [VorlonCD/bi-aidetection#90]
Will be good to have the flexibility of seconds in cooldown time.
At the moment I have set 0.5 for one camera - however the delay itself is not really 30s..most of the time is less than 30s.

Thanks

**Comment by VorlonCD** [comment]
It has been in seconds for a number of builds now:
[AITool-VorlonCD-v2.0.700.zip](https://github.com/VorlonCD/bi-aidetection/files/5978621/AITool-VorlonCD-v2.0.700.zip)
