### ISSUE TITLE
Feature Request: Export Setting

### ISSUE THREAD

**Issue by Kosh42** [VorlonCD/bi-aidetection#91]
Well, as per the title really. A way to export my setting for backup elsewhere, as I'm rather partial to the odd flatten and rebuilt of the virtual machine running my AI Tool.

Many thanks for the awesome work on this tool.

**Comment by VorlonCD** [comment]
Just save the **_SETTINGS** subfolder, it has everything you need.   Window positions and a few other unimportant things are stored in the registry.   Are you a [Vorlon](https://babylon5.fandom.com/wiki/Kosh) too?  :)

**Comment by Kosh42** [comment]
I'd already wiped the machine so have recreated. Not difficult with the new apply to function. TY for your hard work on the tool. Much appreciated.

And of course. Some may say **_the_** Vorlon ;)
