### ISSUE TITLE
Additional relevent objects anomaly

### ISSUE THREAD

**Issue by Village-Guy** [VorlonCD/bi-aidetection#94]
If you remove "Spiny Lumpsucker, Pink Fairy Armadillo, Tasselled Wobbegong" from Additional relevant objects under the camera's tab, it causes aitool to trigger on anything that is recognises! This anomaly is present in build Version 2.0.149.7621 but may be present in other builds.

**Comment by Tinbum1** [comment]
I'm running the same version and it's not doing it with me.

**Comment by Village-Guy** [comment]
Very strange!  Did you restart the app after removing the additional item text?
It's reproducible for me!

**Comment by Village-Guy** [comment]
Whoops hit the wrong button.

**Comment by Tinbum1** [comment]
No I didn't when I had posted but I have since and its still OK.

**Comment by VorlonCD** [comment]
This is "as designed".  Why wouldnt you want to be notified when Spiny Lumpsucker, Pink Fairy Armadillo or Tasselled Wobbegong came in your yard?  :)

I think I see the bug, will try to push get an update in a few days

**Comment by Village-Guy** [comment]
Looks like you have snagged this one in you latest update.  No strange objects being reported after clearing the Additional relevent objects data.

**Comment by Village-Guy** [comment]
Thanks for the fix.
