### ISSUE TITLE
Old camera is still wanted by the tool

### ISSUE THREAD

**Issue by peppelorum** [VorlonCD/bi-aidetection#95]
After renaming a camera the tool still tries to access the old camera somewhere.

This is the what the log says
<img width="915" alt="Screenshot 2020-11-27 at 20 00 28" src="https://user-images.githubusercontent.com/133687/100478419-6f702380-30eb-11eb-844f-ce47a318fc73.png">

This is the cameras I have
<img width="388" alt="Screenshot 2020-11-27 at 20 00 36" src="https://user-images.githubusercontent.com/133687/100478423-7303aa80-30eb-11eb-8c0d-1e4896173006.png">

**Comment by VorlonCD** [comment]
I dont think it happens any longer in the newer builds.   Here is the latest:
[AITool-VorlonCD-v2.0.700.zip](https://github.com/VorlonCD/bi-aidetection/files/5978621/AITool-VorlonCD-v2.0.700.zip)
