### ISSUE TITLE
Allow input files without dot

### ISSUE THREAD

**Issue by MFornander** [VorlonCD/bi-aidetection#97]
I'd like to use the IPCam's motion detection instead of BI.  The Amcrest cameras do not allow for changing the filename and there is no dot in the fixed default path/name.

Leaving the AI Tool "Input file begins with" field blank, still results in a filename match of
.xxxxx.jpg which will not match a file such as "image.jpg"

Request:
Please remove the added dot when matching so leaving blank will find any images.  I will use path to differentiate between cameras.

**Comment by VorlonCD** [comment]
You can already use a wildcard for prefix matching.     Just by putting a * in that field will trigger wildcard matching rather than using the prefix.resetoffile.jpg.    So use CAMERANAME* for example.

Also, when NOT using a wildcard, and no "dot" prefix is found in the filename, it will fall back to matching the camera up with each cameras INPUT PATH.    That only works if your input path is different per camera.

**Comment by MFornander** [comment]
Thanks for the quick reply and awesome work.  I tried the * wildcard and I'm getting this error:
Cannot match 'Z:\b-trash\2020-12-02\001\jpg\18\24\26[M][0@0][0].jpg' to an existing camera.

Z:\b-trash\ is the root where the ipcam is putting its images and the path is based on time.  I have no control over this, just the root.  So AI-Tool is still looking for b-trash to match to a camera an fails.  Any way to just process all the images under the root as specified in UI?

**Comment by MFornander** [comment]
![image](https://user-images.githubusercontent.com/7187414/100951673-41645800-34cc-11eb-8bf4-b9d89eb87cec.png)

**Comment by MFornander** [comment]
BTW the reason I'm doing this is to all BI to not decode the frames and simply save the h265 stream directly to HD.  I'l, then ask the cameras to use their motion detection and save images every 1s to an NFS mount and have AI-Tool look at them and flag the BI stream with an external trigger.

This way there is a little bit of noise since the IPCam motion detection is not that good (lots of false positives) but with AI-Tool running on a separate box/image I can have a separate machine validating the high-res snapshots and tag the BI machine.

Two separate systems with BI being more of a continuous recorder and the AI-Tool with IPCam snapshots being a separat flagger.

**Comment by VorlonCD** [comment]
take out everything from input file begins with, or replace it with any word even if it doesnt match.

That way it should force the camera to be matched based on the INPUT FOLDER path alone.

**Comment by MFornander** [comment]
Empty:
No enabled camera with the same filename, cameraname, or prefix found for 'Z:\b-trash\2020-12-02\001\jpg\18\38\07[M][0@0][0].jpg

"BLAH":
Cannot match 'Z:\b-trash\2020-12-02\001\jpg\18\42\24[M][0@0][0].jpg' to an existing camera.
Object reference not set to an instance of an object. [NullReferenceException] Mod: OnCreated(Object source, FileSystemEventArgs e) Line:607:29
No enabled camera with the same filename, cameraname, or prefix found for 'Z:\b-trash\2020-12-02\001\jpg\18\42\44[M][0@0]
No default camera found. Aborting.

**Comment by MFornander** [comment]
Restarted AI-Tool and tried empty and "any word":

Empty:
![image](https://user-images.githubusercontent.com/7187414/100953558-0a904100-34d0-11eb-9ec2-2351ca839343.png)

"BLAH":
![image](https://user-images.githubusercontent.com/7187414/100953635-390e1c00-34d0-11eb-9cbe-d090a159c9f9.png)

**Comment by MFornander** [comment]
> That way it should force the camera to be matched based on the INPUT FOLDER path alone.

This exactly what I want thanks.

**Comment by MFornander** [comment]
Running 2.0.37.7608 built on 10/30/2020 8:48:57 AM BTW

**Comment by MFornander** [comment]
This shows the best promise after a full restart.  The input field is empty and I get:

![image](https://user-images.githubusercontent.com/7187414/100954360-a53d4f80-34d1-11eb-9284-363d61b5ddc4.png)

**Comment by MFornander** [comment]
Also tried to restart everything (cam, fileserver, ai-tool) but I'm getting these in the log even though the filenames are different.  The ImgQueued keeps rising even though it's "skipping" and finally hits 100 and gives up.

![image](https://user-images.githubusercontent.com/7187414/100955160-39f47d00-34d3-11eb-8a2b-3fb52e775f57.png)

**Comment by MFornander** [comment]
Ok giving up for a while.  Where is the relevant code?  I'm a software engineer with 30+ years of C/C++/C# experiance so maybe I can fix this and submit a MR?

**Comment by MFornander** [comment]
Sorry about this spam first of all.

Digging into your C# code and the detection_dictionary, I realized that the camera was saving multiple images per second so ignore the "Skipping image..." messages since they are indeed correct! :smile: 

Still, I can't see a way to get around the "No enabled camera..." error, even with your tips of leaving the field blank or using *.  Could you try to save an image manually at a path mimicking my path to see if it's my setup or the code?

**Comment by MFornander** [comment]
Figured out that this is a subfolder scanning problem not a naming problem.  Closing this issue since your solution works without subfolders and opening another.

**Comment by VorlonCD** [comment]
Great.   I think I should remove that GetCamera error when it actually finds the camera based on the camera path.
